### ISSUE TITLE
EU Data through EEA API

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#103]
Update, Mar 11: 
- The awesome EEA folks have made an addition for us: The xml now includes the unit in the value_numeric tag:
  {value_numeric unit="µg/m3"}16.25{/value_numeric}

Previous Update: 
- resolved coordinates question.
- noted issue with merging this source with other EU sources

**Country of data source:**  EU/Multi-country, currently reporting: 
![screen shot 2016-03-05 at 2 34 48 pm](https://cloud.githubusercontent.com/assets/13404290/13549960/2484c7f8-e2e0-11e5-8ccd-c3f98a15d73d.png)

**Relevant URL's:**
- UTD Download Guide: http://discomap.eea.europa.eu/map/fme/doc/UTDAirQualityDownloadGuide.pdf
- The service is available at: http://discomap.eea.europa.eu/map/fme/AirQualityUTDExport.htm

**Token Key:** Contact me to get it.

**Pollutants measured:**
![screen shot 2016-03-05 at 2 44 34 pm](https://cloud.githubusercontent.com/assets/13404290/13549993/e56394c2-e2e0-11e5-981d-cd3732bedc32.png)
_(Note: We don't use benzene)_

**Pollutant Nomenclature for the API:** PM10, O3, NO2, PM2.5, SO2, CO
More on nomenclature can be found here: http://dd.eionet.europa.eu/vocabulary/aq/pollutant/view

**Are units of measurement clearly indicated** (e.g. do you see 'AQI', 'ppm' or 'ug/m^3'?) 
_Note: We cannot directly input AQI, API, AQHI, etc. values directly into our system._
The awesome EEA folks have made an addition for us: The xml now includes the unit in the value_numeric tag:
{value_numeric unit="µg/m3"}16.25{/value_numeric}

**Other comments about units:**
No

**Are there date+timestamps for pollutant measurements?** 
Yes.

**Are time intervals otherwise indicated on the site (e.g. 'Measurements are 15 minute averages'):**
Hourly. 

**Are coordinates for the stations clearly indicated or discernible? Comment. (e.g. do you see a map or a list of coordinates):**
UPDATED: Coordinates are reported as: samplingpoint_x (for long), samplingpoint_y (for lat)

**Are you with the host agency and may we contact you?**: No.

**Any other comments about this source:**
- We have additional contacts at EEA who can help out if we encounter difficulties. If you'd like to be connected to them, please let me know.
- As noted above, we need to hear back from EEA regarding (a) units on measurements.
- We will need to figure out how to merge these with existing spots reported in EU to the system (i.e. GB, NL, PL). For GB, for instance, data are reported from DEFRA - where we are currently getting data - but 

(@olafveerman : @jflasher mentioned you might be interested in this.)

**Comment by olafveerman** [comment]
Yes, I am definitely interested in this, but still unsure when I can pick this up. Hopefully by the time you get an answer around the units of measurement

**Comment by dolugen** [comment]
@olafveerman Can you point me to the reference where you use locale in momentjs? I can't seem to find such example in the package docs.

**Comment by RocketD0g** [comment]
Awesome, @olafveerman! Got the update from the EEA folks - they actually altered the xml code to include units now, which was pretty awesome (and so fast!) of them. I will shoot you the token by email.

**Comment by olafveerman** [comment]
Started scaffolding a EEA adapter. Will be using the XML response.

### City
The city will be tricky. In some cases we can parse if from the `station_name`, like Belgium: 

``` xml
<station_code>42R841</station_code>
<station_name>42R841 - MECHELEN</station_name>
```

but it doesn't apply to other sources, like the Polish one:

``` xml
<station_code>PL0072A</station_code>
<station_name>Toruń, KASZOWNIK</station_name>
```

### Attribution
How should we deal with attribution? EEA first, and then the data source? Is there a particular attribution the EEA wants us to use?

### Updated date
They are very particular about the updated date, which leads me to believe they actually update the data. Should we be accounting for that?

cc @jflasher @RocketD0g

**Comment by RocketD0g** [comment]
## City
That is a bummer and don't have an immediate good thought. 

I personally think we should eventually get rid of the city location and just stick to coordinates. But I know this isn't ideal, as then how does someone search easily for location in our current set up? I don't know. But it strikes me that even within a single source, these things are not uniform, so we will struggle when trying to combine all of these sources. Dunno.

## Attribution
For attribution, I think doing the primary attribution to EEA and then to the data source listed in the API should work (e.g. the url under the 'station_namespace'). This is essentially what we did for the US EPA source.  

## Updated date
For the updated date, I would think we are only grabbing the original data when it is inserted in real-time and not going back and updating the data or filling in holes for data not grabbed. So, as of now, I would say we don't have to worry about this. I think in the future with an updated format, we may want to consider the 'date/time inserted' and then possibly, if we go down the road of worrying about QA/QC updates, we would need a 'date/time updated' as well.

cc @jflasher @olafveerman

**Comment by RocketD0g** [comment]
And as an aside to the comment above - and probably one that should eventually go elsewhere, but @jflasher, is it reasonable to envision at some point a way to search for a city name, that city is associated with a coordinate at the center of the city and certain radius, and all stations are returned within that radius? Maybe this is what you've already mentioned to me?

**Comment by jflasher** [comment]
This could be done, but it'd make any such request slower than just having the city name stored with the data and it'd require the use of a geolocation service which I believe generally cost money. I am slowly coming around to the more coordinates-centric model of doing things and dropping city name, but should we require coordinates for data to be included then?

**Comment by RocketD0g** [comment]
Got it. Hmm, agree; slower+costs money are both not positive attributes. :) Yeah, regardless, I think we should require coordinates going forward.

**Comment by olafveerman** [comment]
I've researched the API a bit more and have a couple of doubts / questions that we could relay to your contact at the EEA.

## Pollutant coverage
What pollutants are reported to UTD?

On UTD, for example, no CO data is being reported for Portugal.

![image](https://cloud.githubusercontent.com/assets/751330/14045339/c104366a-f26f-11e5-9b27-20d59750106f.png)

Going directly to the national source, there are stations with CO values: http://qualar.apambiente.pt/index.php?page=2&year=2016&month=03&day=24

## Time-outs and error handling
Yesterday, the system seemed to be down. A request would be spinning for a very long time (> 10 minutes) without any response being returned.
How does UTD handle errors? Can we expect normal HTTP status codes?

## Averaging period
UTD does not specify anything about the 'averaging periods' of the measurements, even though there is quite some variations between sources and pollutants. The Portuguese source, for example, reports the following on an hourly basis:

| pollutant | reports |
| --- | --- |
| O3 | hourly max value |
| NO2 | hourly max value |
| CO | 8-hour max value |
| SO2 | hourly max value |
| PM10 | daily average |
| PM2.5 | daily average |

##  Update frequency
How often do the national systems add data to UTD? Currently, a lot of countries are at least a day behind:

![image](https://cloud.githubusercontent.com/assets/751330/14045802/805771fa-f273-11e5-9fe8-d11a10e654bb.png)

**Comment by olafveerman** [comment]
cc @RocketD0g and @jflasher ^

**Comment by jflasher** [comment]
Awesome, I'll send something over.

**Comment by olafveerman** [comment]
Working on this adapter. Here are some sample responses from 4 countries:

| xml tag | Belgium | Netherlands | Poland | Portugal |
| --- | --- | --- | --- | --- |
| `<network_namespace>` | BE.CELINE-IRCEL.AQ | NL.RIVM.AQ | PL.CIEP.AQ | PT.APA.AQ |
| `<network_localid>` | NET-Flanders | NET-NL051A | NET_PL_PD_AQ | NET-PT00002 |
| `<network_name>` | Flanders | "Overige meetpunten RIVM" | Podlaska Sieć Monitoringu Jakości Powietrza | Rede de Qualidade do Ar de Lisboa e Vale do Tejo |
| `<network_countrycode>` | BE | NL | PL | PT |
| `<network_timezone>` | http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC | http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC+01 | http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC+01 | http://dd.eionet.europa.eu/vocabulary/aq/timezone/UTC |
| `<station_namespace>` | BE.CELINE-IRCEL.AQ | NL.RIVM.AQ | PL.CIEP.AQ | PT.APA.AQ |
| `<station_localid>` | STA-BETR892 | STA-NL00549 | STA_PL0148A | STA-PT03101 |
| `<station_code>` | BETR892 | NL00549 | PL0148A | PT03101 |
| `<station_name>` | 42R892 - KALLO | Laren-Jagerspad | Białystok-Miejska | Alverca |
| `<station_altitude uom="m">` | 9 | 1 | 145 | 22 |
| `<samplingpoint_namespace>` | BE.CELINE-IRCEL.AQ | NL.RIVM.AQ | PL.CIEP.AQ | PT.APA.AQ |
| `<samplingpoint_localid>` | SPO-BETR892_00001_100 | SPO-NL00549_00008_100 | SPO_PL0148A_9_001 | SPO-PT03101_00007_100 |
| `<samplingpoint_point>` |  |  |  | |
| `<pollutant>` | SO2 | NO2 | NOX as NO2 | O3 |
| `<value_datetime_begin>` | 2016-06-18 23:00:00 | 2016-06-18 23:00:00 | 2016-06-18 23:00:00 | 2016-06-19 01:00:00 |
| `<value_datetime_end>` | 2016-06-19 00:00:00 | 2016-06-19 00:00:00 | 2016-06-19 00:00:00 | 2016-06-19 02:00:00 |
| `<value_datetime_inserted>` | 2016-06-18 03:06:34 | 2016-06-19 01:57:14 | 2016-06-19 02:34:38 | 2016-06-20 01:05:45 |
| `<value_datetime_updated>` | 2016-06-20 02:09:41 | | | 2016-06-20 17:38:55 |
| `<value_numeric unit ="µg/m3">` | 1 | 2.49 | 14.2 | 66.4 |
| `<value_validity>` | 1 | 1 | 1 | 1 |
| `<value_verification>` | 3 | 3 | 3 | 3 |

**Comment by jflasher** [comment]
Awesome. Let me know if you need any help!

**Comment by RocketD0g** [comment]
Latest: We're now accessing the EEA API for a set of countries (e.g. Germany, France, Croatia, etc.), but not all possible yet. We're adding them in slowly to see how they behave in our system. One thing we notice is that the German data, for instance, has some gaps. This may have to do with perhaps German data being sent to the EEA system at a couple discrete times per day, rather than continuously - so not a real data gap, just one our system isn't picking up. We haven't really looked at the rhythm of that data source yet (or figured out how to account for different times different countries may dump data to EEA - we don't want to ping their system too much). Seeking help in figuring that out, as anyone is interested.

cc: @jflasher

**Comment by Stalfur** [comment]
Hello. As the person responsible for implementing technical solutions for Iceland to deliver UTD data into the EEA system what would be beneficial for you? We are currently doing lots of technical heavy lifting but expect to be ready for UTD data and other streaming later in the year.

Would you prefer the data via EEA UTD portal or would another method appeal more to you?

**Comment by Stalfur** [comment]
Also regarding co-ordinates vs city names then you could use Nominatim for reverse geocoding http://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding

**Comment by jflasher** [comment]
Hi @Stalfur thanks for the question and mention of Nominatim!

If the data is reporting to EEA, our preference would be to get it from there as we already have mechanisms in place to do that.

**Comment by lhufnagel** [comment]
In reply to @RocketD0g : 
Indeed the German Federal Environment Agency reports the hourly measurement data only every third hour. At night time (10:30pm-7:30am) not even once, but all hourly measurements in the following morning, explained here http://www.umweltbundesamt.de/daten/luftbelastung/aktuelle-luftdaten#strap-18358 

Could you send me the EEA Token Key? I would like to play around with it, and integrate more EU countries.

**Comment by jflasher** [comment]
Thanks for the info @lhufnagel! For the token, per http://discomap.eea.europa.eu/map/fme/doc/UTDAirQualityDownloadGuide.pdf, you can request one from Peter.Kjeld@eea.europa.eu.

We changed the EEA request mechanism from being synchronous to async in #213, however there was an issue with character encoding in the return that we were waiting to be fixed on their side, I haven't checked the status of that in a bit. I think this switch, which will also allow us to request data farther back in time, will help with this issue. We can also look at bringing in another batch of countries, we're just adding them slowly to see how the EEA system and our system work with more countries.

**Comment by sruti** [comment]
I think we've addressed this!
