### ISSUE TITLE
Canterbury, NZ data hasnt updated in 3 month

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1048]
https://explore.openaq.org/locations/884467

We'll want to check if this source is still active, if not discontinue it.

**Comment by majesticio** [comment]
I can see that the source is reporting data for Geraldine but its not being grabbed by the fetcher. This adapter will require an audit and refactoring

**Comment by russbiggs** [comment]
explorer is showing all canterbury locations as stale
![Uploading Screenshot 2023-07-17 at 4.31.05 PM.png…]()

**Comment by majesticio** [comment]
When I run the adapter locally I am getting up to date measurements, even if some are missing. So something is up

**Comment by majesticio** [comment]
resolved by #1053
