### ISSUE TITLE
Tasmania update frequency issues

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1054]
The locations in Tasmania seem to have some odd data frequencies with data showing for ~10 hours starting around 03:00 UTC then shutting off. 

<img width="1289" alt="Screenshot 2023-08-01 at 7 31 53 AM" src="https://github.com/openaq/openaq-fetch/assets/8487728/88629e64-dbe9-435e-9d1a-c4e726d77989">

**Comment by majesticio** [comment]
resolved by #1066
