### ISSUE TITLE
Japan missing data

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1056]
Seems like the Japan adapter is missing data every day at 15:00 and 16:00 UTC. 

e.g. 

<img width="1289" alt="Screenshot 2023-08-01 at 1 19 04 PM" src="https://github.com/openaq/openaq-fetch/assets/8487728/c71226f2-a71d-4a18-9ae7-1d0855c6cb06">

**Comment by majesticio** [comment]
I seem to remember their website not having data around midnite JST, which would align with what you are seeing here. I will investigate again to confirm, and add that information to the wiki if so

**Comment by russbiggs** [comment]
interesting. if we can use an offset to get it that might be another option if its available later

**Comment by majesticio** [comment]
Actually now that I am looking, it seems like they report their time as 1-24 hrs, instead of 0 as midnite through 23 hrs. I am going to see if the code logic accounts for this, but it would explain the missing data if it isn't. Midnite JST is 15:00 UST
