### ISSUE TITLE
EEA using deprecated battuta service

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1068]
The EEA adapter is still using the deprecated Battuta service. It would be best to remove these calls to the Battuta file to lessen the load on the bucket:

https://github.com/openaq/openaq-fetch/blob/93496c79adb4e5038508f4e387ed75e469c50b43/src/adapters/eea-direct.js#L43

**Comment by russbiggs** [comment]
@majesticio  Can this issue be closed

**Comment by majesticio** [comment]
Closing this issue, was resolved by PR #1071
