### ISSUE TITLE
Possible source for AQ data from Vietnam

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-fetch#1073]
This site reports AQI data, but might lead to raw AQ measurements. Needs further investigation.
https://moitruongthudo.vn/
<img width="1175" alt="Screenshot 2024-01-23 at 10 14 37 AM" src="https://github.com/openaq/openaq-fetch/assets/67290377/9ef36b97-58b8-4652-8597-07ad89c2f48c">

**Comment by russbiggs** [comment]
Nice find. The concentration (Nồng độ) tab looks like raw concentrations. When clicking a location it looks like it is calling an endpoint with the values e.g.

https://moitruongthudo.vn/public/dailystat/32 

The endpoint is pretty sparse in terms of detail about the data( no units, datetimes dont explicitly list tiemzone) , but in combination with other data on the page we could probably pull it together.

**Comment by russbiggs** [comment]
Here is the JSON payload that leaflet is using for the markers. Looks like it has all the location data we would need as well as ids to call the endpoint listed in my previous comment: 

https://moitruongthudo.vn/api/site

**Comment by majesticio** [comment]
This is great, it seems like those are also AQI values? A bit ambiguous

**Comment by russbiggs** [comment]
The "Concentration" charts seem pretty clearly not AQI given that the legend labels are in µg/m3. 

The AQI tables are populated by this separated endpoint:

https://moitruongthudo.vn/public/dailyaqi/14

note its the `dailyaqi` route
