### ISSUE TITLE
Provider name clean-up

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1083]
A number of providers are incorrectly named in the DB. Not exactly a fetch issue but this seemed the best place to log.

These could be renamed to better reflect their source:  

Spartan network reference grade monitors -> SPARTAN Network
Serbian data from NATIONAL NETWORK OF AUTOMATIC STATIONS FOR AIR QUALITY MONITORING -> remove capitalization
NZ data from Enviroment Canterybury->this is a description not a name 
AQ data from AQMIS site for Trinidad and Tobago -> this is a description not a name
Turkiye -> Türkiye

review the others to make them readable (remove underscore, uneccesary abbrevations etc) and correct any other with similaar mistakes to those above

**Comment by majesticio** [comment]
That makes sense, I will take an inventory and let you know what else I see as well

**Comment by russbiggs** [comment]
Can this get prioritzed to this week? These are the labels showing up Explorer and I'd like these to be tidier for the front end

**Comment by majesticio** [comment]
Requested changes have been made, labels have been updated appropriately.
