### ISSUE TITLE
Hanoi reporting very incosistently

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#1086]
Hanoi is still reporting very poor data coverage compared to their site, even with the offset deplyoment. This needs additional review to figure out why so many measurements are being missed. IF the offset deployment is performing this poorly, i recommend seeking a different solution because its clearly not doing much of a job.

<img width="1318" alt="Screenshot 2024-02-22 at 6 44 27 AM" src="https://github.com/openaq/openaq-fetch/assets/8487728/e375dc91-fbef-4140-904c-dedafd68abae">

**Comment by majesticio** [comment]
Thanks for pointing this out, I will look into it and fix the issue.

**Comment by majesticio** [comment]
So I have compared measurements from the source's website to our fetched measurements. For instance the site Kim Liên (pm25):

![Screenshot 2024-02-22 at 8 09 06 AM](https://github.com/openaq/openaq-fetch/assets/67290377/80553968-f096-4428-9f21-e87fe541e3b4)

if you look closely this appears to be consistent with our fetched data:
![Screenshot 2024-02-22 at 8 10 21 AM](https://github.com/openaq/openaq-fetch/assets/67290377/0a943211-8ca0-461a-ab42-e5167110003a)

I will continue to investigate this, if the data gaps are consistent the offset deployment might not be necessary.

**Comment by majesticio** [comment]
I have identified some of the data gaps, and they are consistent with the data we a receiving from the API. I am going to increase the hours fetched from 3 to 12 hours and observe this adapter over the next few days. If the coverage does not improve, the way we fetch data from this provider will need to be revisited.
