### ISSUE TITLE
Malaysia - Source (not yet useable, seeking help in contacting correct person for data)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#11]
Listed as a priority given recent AQ issues in region, but NOTE: There is an issue with these data as they are currently presented: They are shown as an index value of combined pollutants into a unitless value. The FAQ's indicate to contact an individual for historical concentrations in non-index units, though currently unsure how to do that.

After discussions with WRI/GFW, they are particularly interested in AQ data from countries affected by the fires in Indonesia.

AQ data for Malaysia:
http://apims.doe.gov.my/v2/
(click 'apims' when given choice at portal)

FAQ's (and 5th one down is the one on hourly concentration data): http://apims.doe.gov.my/v2/faq.html

Seeking help in identifying who to contact about access to hourly AQ data.

**Comment by magsyg** [comment]
It does look like that source previously mentioned, has been updated to http://apims.doe.gov.my/public_v2/home.html, this source has metadata for locations, and has parameters and units for their values

**Comment by RocketD0g** [comment]
Thanks, @magsyg! I'm missing where the  table has physical values reported, still just seeing API values. Can you point me to them?

**Comment by magsyg** [comment]
@RocketD0g, In the API-table screen, there is an information button, that shows what parameters and units the different signs are representing

**Comment by RocketD0g** [comment]
Ahh, I see that - but I don't think it's actually pointing to any information with those units. The scale at the bottom is in unitless Air Pollution Index (API), when looking at the map on that page or hovering over the data points on, I see no information reporting (though a blank spot for API), and when I click on the hourly table, it is in all API too. 

So I'm not really sure what the 'info' button is showing units for (took a screenshot below to make sure we're on the same page).


![Screen Shot 2020-05-20 at 3 31 22 PM](https://user-images.githubusercontent.com/13404290/82489056-ff833f80-9aae-11ea-8df5-307c01d5a749.png)

**Comment by magsyg** [comment]
The API map does not seem to work for this site at the moment, but the API Table [Hourly] does, on this page: http://apims.doe.gov.my/public_v2/api_table.html
![image](https://user-images.githubusercontent.com/56266980/82489706-63732b80-9ae2-11ea-8dc2-9850393e8b91.png)

**Comment by RocketD0g** [comment]
I just looked over[ the manual for the API calculation](http://apims.doe.gov.my/public_v2/pdf/API_Calculation.pdf) and it has the standard calc that takes a physical AQ measurement and put into a API/AQI type thing here: 

![Screen Shot 2020-05-20 at 3 52 21 PM](https://user-images.githubusercontent.com/13404290/82491084-2c852180-9ab2-11ea-9ce1-d25d574c7d64.png)

So either:
- the info box is correct, and  that API table isn't showing API but rather physical AQ measurements, but is still called an API table for some reason 
OR 
- the info box is wrong and those are API values not in the right units

It's not clear to me which, but I'd be willing to bet they are API values and the info box tells you the base units the stations measured data in.

If it _is_ showing physical AQ measurements, there'd need to be a check for the super-script symbol, to make sure the value is a single pollutant, if so, which one, and if it is multiple, then to ignore it.

(If you have more insight on this, let me know. I'd like it to be clearer so we could just ingest the data :)).

**Comment by RocketD0g** [comment]
Hey @magsyg - Just a heads up that I'm pinging a Malaysian scientist on our Slack channel to see if he can help us figure out what's shared on that table. Will comment here if I find out anything definitive! 

(And also, thanks again for your many contributions to the platform already!)

**Comment by RocketD0g** [comment]
Hi @magsyg - Just got a reply from a contact who is a professor/scientist in Malaysia. He believes they are sharing Air Pollution Index values and not straight physical measurements. He also doesn't believe the gov-measured data are shared in a physical place anywhere (to his knowledge) in Malaysia.

**Comment by magsyg** [comment]
Oh okay, so shall we then not add this source at all, or make a method transforming the data into an approximate using the manual of API calculation?

**Comment by RocketD0g** [comment]
Thanks, @magsyg. I think we'll be unable to add this source at this time. We've resisted adding in data sources where the data has to be back-calculated from AQI/API values. The breakpoints change over time, and it's often not obvious when they change.
