### ISSUE TITLE
US new cities

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq-fetch#111]
Nice there are so many new sources in the US!

I've just noticed that some are written in only capital letters while others aren't. Should there be a rule, e.g. MILWAUKEE -> Milwaukee?

**Comment by jflasher** [comment]
@masalmon Yep, we got a whole bunch of new places with the EPA data source. Unfortunately, the capitalization and some special characters are a bit all over the place. I was writing a function to do what you said, but it gets pretty complicated as there are edge cases and I can't just make every first letter caps and the rest lowercase. So it'd potentially still look weird even after I tried to fix it. So for now, we're just bringing in the data like it is from the original source.

**Comment by masalmon** [comment]
"So for now, we're just bringing in the data like it is from the original source" -> which is awesome! I need to re-do a map at some point!

**Comment by jflasher** [comment]
Yep, lots of new data. Just a note that due to #112, it's a couple of days old :(
