### ISSUE TITLE
Handle large data migrations better

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#117]
@dolugen so I merged in #110 which looked good locally and on staging since there wasn't a lot of data. When I deployed it to production, it looked like it was going to take hours and hours to complete because we have to update so much data. Since this blocks the fetch task from running, I just stopped it from running on production (by marking the migration complete and re-deploying). 

We should figure out a better way to handle these really big updates. I could run it locally I suppose and have it pointing at production, but that still doesn't seem great.

**Comment by dolugen** [comment]
I should've known this would be a problem. Now I don't know how to do this with Knex, but I could investigate how to solve this in PostgreSQL.

The criterion:
* Update a minor part of a large table (only Netherlands records)
* Update only a single field inside a JSON field (`data.date.local`)

**Comment by jflasher** [comment]
Yeah, that'd be great. I did some quick searches and didn't see anything. In this case, we do have the option of just updating it via a secondary client (like my local computer) since it's just updating some data. However, I could see this being a problem if we need to change some table structure that the code depends on.

**Comment by dolugen** [comment]
@jflasher Could you upload the resulting file from the following command?
```
COPY (SELECT * FROM measurements WHERE country='NL' LIMIT 100000)
TO '/tmp/measurements-nl.csv' CSV;
```

**Comment by dolugen** [comment]
So here's what I'm going for:
* Dump a CSV of NL data (the above command without `LIMIT`)
* Update said CSV file (with a script that updates timezone and writes a new file)
* Delete NL data from table
```
DELETE FROM measurements WHERE country='NL';
```
* Insert updated data
```
\COPY measurements FROM '/tmp/measurements-updated.csv' WITH CSV;
```
@jflasher Do you see any problem with this?

I think this would be way faster than the previous method (tested with dummy data with 100k rows), but I'll have to run it with real data. It's not as elegant as Knex migrations, but it shouldn't take a lifetime :grin:

**Comment by jflasher** [comment]
@dolugen interesting, I could see this working. My only worry is about everything serializing properly form native types to CSV, but I guess that should all be handled properly by psql. It scares me a bit to be deleting all that data. :) What happens when someone is accessing the database during this update time? I guess they just see no measurements for NL? Is there a way to just do a copy and overwrite from the csv? This would keep us from being without any measurements in there for that period of time.

**Comment by dolugen** [comment]
[COPY doesn't overwrite stuff](https://wiki.postgresql.org/wiki/COPY#Caveats_with_implementation), unlike MySQL's REPLACE. I could potentially reduce the downtime with one additional step: Import the data to a temporary table first. Then the original rows can be deleted before copying the updated ones.

**Comment by dolugen** [comment]
ping @jflasher

**Comment by dolugen** [comment]
Assigning this to myself as not forget this exists.

**Comment by jflasher** [comment]
This has fallen of my radar for awhile, but pinging @scisco in case he has any thoughts around this as well.

**Comment by dolugen** [comment]
Any new ideas on this?

**Comment by jflasher** [comment]
Yes and no. :) After the recent work to put real-time data into S3, we've got two sources of data. One is the database which currently holds all the data and powers the API. The other is the S3 bucket which also holds all the data and powers the aggregations. Going to open another ticket for this, but my long-term idea is to restrict the database to only holding the last 3 months of data. This will speed up the API and lower overall costs needed for the database. All data will be stored in S3. I'd recommend not updating the data in the database as it'll just timeout anyways. We'd want to update the data in the S3 bucket as it's a long-term record. So then we'd just need a script to read over the many JSON files in the bucket and edit them as we need to do these sorts of migrations.
