### ISSUE TITLE
Singapore - Sources (not useable yet)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#12]
Listed a priority given recent AQ issues in area but NOTE: There is an issue with these data as they are currently presented: They are not listed as individual stations, but rather as aggregated stations that represent different regions of the city. WRI/GFW is contacting NEA on our behalf to see if the station-level data are accessible. We will not proceed with these data until we received the station-level information.

After discussions with WRI/GFW, they are particularly interested in AQ data from countries affected by the fires in Indonesia.

AQ data for Singapore:
http://www.nea.gov.sg/anti-pollution-radiation-protection/air-pollution-control/psi/pollutant-concentrations/type/PM25-1Hr#pollutant

If anyone knows differently, please comment.

**Comment by gaomrx** [comment]
@RocketD0g  Still need help here? There are some stations listed at [aqicn.org](http://aqicn.org/city/singapore) as well as the [gov's haze website] (http://www.haze.gov.sg)

**Comment by RocketD0g** [comment]
Thanks, @gaomrx - The locations that are listed are actually not station-level - they are actually 20-something stations and they get averaged into the 'north', 'west', 'central' etc locations in a way that is not entirely clear. So until they report them at the true station level, we can't add them, unfortunately, for full transparency requirements of our system.

**Comment by saloca** [comment]
On the spreadsheet, I added some more specific information about the number of stations and their locations:

According to UNEP, Singapore has "Advanced telemetric air quality monitoring network with 22 air monitoring stations to continuously monitor the 6 key air pollutants (i.e. ozone, NOx, CO, PM10, PM2.5 and SOx)." https://wedocs.unep.org/bitstream/handle/20.500.11822/17103/Singapore.pdf?sequence=1&isAllowed=y

A California energy nonprofit has a map of some of these: http://mce2.org/wmogurme/images/workshops/ASEAN/day4/Singapore%20-%20PM2%205%20Monitoring_Singapore_Bala_APRU[1].pdf

I realize this doesn't help with finding station-level data. I did find a general description of where the data go for analysis, but it's circa 2006 so may be woefully outdated: http://cleanairasia.org/wp-content/uploads/portal/files/documents/singapore_0.pdf (see page 4).

**Comment by RocketD0g** [comment]
Thanks, @saloca!

After some additional investion, it's looking like station-level data are not available from Singapore at this time, so I'm marking this "on hold" until that changes.

**Comment by saloca** [comment]
Ah, too bad! Several of my in-laws just moved there so if there's anything that a person on the ground could do or find out for you, let me know and I'll see if I can hit them up.
