### ISSUE TITLE
location of the Sanathnagar - Hyderabad - TSPCB station

### ISSUE THREAD

**Issue by maelle** [openaq/openaq-fetch#127]
The station seems to be in a lake if using the lon/lat info. I'm sorry to find this funny. :smile:

![stations_hyderabad](https://cloud.githubusercontent.com/assets/8360597/13951677/ee482166-f032-11e5-8437-4bc0261b8934.png)

I googled the name of the station and Sanathnagar is a neighborhood further North-West. 

I'll send an email to colleagues there to ask if they know where the station is!

**Comment by masalmon** [comment]
Generally, how could we check the latitude and longitude of all stations? Openstreetmap has a monitoring station category, but I'm not sure we can expect each air quality source to be registered as a monitoring station in Openstreetmap data. That being said, this could be a collaboration between OpenAQ and Openstreetmap?

**Comment by jflasher** [comment]
@masalmon good catch! I think trying to engage local OSM communities could be really awesome, especially in areas where we don't have coordinates available to us like Australia and Sao Paulo. In this case, the lat/lon is coming from the site itself, so there wasn't any addition checking done.

And a related question, assuming we do get a corrected coordinate, the best way to handle it would be to notify the CPCB and have them change the value in their data source. Changing it only in ours isn't something I'd really like to do in most cases.

**Comment by masalmon** [comment]
Good catch is a good phrase for something you find in a lake! (technically my name impedes my fishing)

I agree with you regarding notifying the CPCB! I've contacted a colleague of ours in Hyderabad, I'll keep you updated.

Even for sources without geographical coordinates, the corresponding institution could be notified? It's not hard to add geographical info to an API, is it?

**Comment by jflasher** [comment]
It's not hard for us to add geo information normally, but I wouldn't want to speak for anyone else's systems.

**Comment by masalmon** [comment]
My colleague Sreekanth told me "17.4833° N, 78.4167° E these are sanath nagar coordinates"

@jflasher I'll let you figure out which one is the latitude :blush:

**Comment by jflasher** [comment]
Awesome, thanks @masalmon. I think the question still remains of how we handle this. Do we have any contact info for CPCB? I checked on the site and they do ask to inform them of any discrepancies, but provide no contact info.

**Comment by masalmon** [comment]
Well thanks to Sreekanth. I'll ask him about contact info!

**Comment by masalmon** [comment]
" I checked on the site and they do ask to inform them of any discrepancies, but provide no contact info." -> so there are two discrepancies to notify!

**Comment by abarciauskas-bgse** [comment]
Just looked at https://docs.openaq.org/v2/locations/5647?limit=100&page=1&offset=0&sort=desc&radius=1000&order_by=lastUpdated and the latitude/longitude looks ok to me

```
      "coordinates": {
        "latitude": 17.4559458,
        "longitude": 78.4332152
      },
```

https://goo.gl/maps/CbG8CHPn1GCNod2e6
