### ISSUE TITLE
How to find sources for Pakistan?

### ISSUE THREAD

**Issue by maelle** [openaq/openaq-fetch#129]
I've just seen that cities in Pakistan are said to be extremely polluted. This made me curious!

The aqicn.org website mentions using data from UNEP and Quaid-e-azam University.

The Pakistan Environment Protection Agency either does not have an easy website in English or does not provide the real time measurements: I could not find anything here http://environment.gov.pk/

Here there seems to be real-time values from the university in Islamabad I mentioned previously http://www.yangshitianqi.com/Quaid-e-azam%20University/kongqizhiliang.html 

I have no idea what the website (base URL http://www.yangshitianqi.com/ ) is. It looks like Chinese? Could anyone look at it? And most importantly does anyone know someone in Pakistan?

**Comment by abid-omar** [comment]
Check the AirVisual API for sources on Pakistan. Perhaps those can be included at Openap

**Comment by masalmon** [comment]
Thanks. These are the locations for Pakistan on the website but I cannot find a link to the source:

* https://airvisual.com/pakistan/sindh/karachi/karachi-industrial

* https://airvisual.com/pakistan/punjab/lahore/lahore-cantt

I have not spent a lot of time searching, though.

**Comment by abid-omar** [comment]
The source is the consumer level AirVisual Nodes. More Nodes will be
available soon in further cities. Unfortunately, government level or
research-grade sources do not exist in Pakistan.

**Comment by masalmon** [comment]
Ok so I don't think it can be included if it's not free? cc @RocketD0g  @jflasher

**Comment by jflasher** [comment]
Even if it was freely available, I think we'd need to figure out how to handle measurements coming from low-cost sensors, which is a big issue.

**Comment by masalmon** [comment]
I hadn't even realized it was low cost sensors :grimacing: Stupid me

**Comment by jflasher** [comment]
Well it's interesting because I imagine what's happening is aggregating low-cost sensors over an area and then presenting them as one final thing, but I guess that final thing still needs to be treated as 'low-cost sensor' data?

**Comment by masalmon** [comment]
at least not as physical concentration if it's an aggregated thing?

**Comment by abid-omar** [comment]
The data quality and reliability of low-cost sensors is certainly an issue.
The way I see it, some data is better than none. Since I've set-up these
sensors in Pakistan, I see issues of reliable online connections as well.
I'm working on publicizing this data through an hourly Twitter account, and
this will hopefully create the awareness and get the Government or
Universities to set up BAM-based monitors. If there is some way to use this
data on OpenAQ till then, would be of great help.

Perhaps OpenAQ could have some alternate channel for this kind of data.

**Comment by RocketD0g** [comment]
@abid-omar - Thanks for starting this thread. We are definitely interested in aggregating low-cost sensor data one day, but we currently don't have the capacity to do it, in terms of how it would be visualized or accessed alongside government or research-grade data. We think this would have to be done very carefully, given the data quality issues mentioned above. We're applying for funding from various sources to do this, but until something comes through, we need to put  sharing large-scale amounts of low-cost sensors on hold. If you're interested at some point, it would be great to chat with you about needs you perceive on communicating low-cost sensor data. I'll reach out to you on the slack channel!

**Comment by jflasher** [comment]
PK data will be coming in with https://github.com/openaq/openaq-fetch/pull/607
