### ISSUE TITLE
Indonesia - Sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#13]
Of course listed as a priority due to recent AQ issues in the region, but there are issues accessing data at an appropriate time resolution (@olafveerman, correct/edit if I'm mistaken).

After discussions with WRI/GFW, they are particularly interested in AQ data from countries affected by the fires in Indonesia.

Here is the general AQ data page for Indonesia: 
http://www.bmkg.go.id/BMKG_Pusat/Kualitas_Udara/

Here is an example of one of the page (PM10). I am unsure if we can programmatically get data from this page either from the graph (hover over point) or hit 'view data':
http://www.bmkg.go.id/BMKG_Pusat/Kualitas_Udara/Informasi_Partikulat.bmkg

**Comment by RocketD0g** [comment]
Also, transporting @olafveerman 's previous comment over: 
***
This seems pretty do-able with a basic scraper. The HTML contains the raw measurements for the locations, wrapped in the following div:

<div class="modal fade modal-medan" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
The actual measurements for PM10 look like this:

<div class="modal-body">
  MEDAN, Jam 0 : 106.36<br>
  MEDAN, Jam 1 : 79.84<br>
  MEDAN, Jam 2 : 75.38<br>
  MEDAN, Jam 3 : 68.41<br>
  MEDAN, Jam 4 : 74.49<br>
  MEDAN, Jam 5 : 84.06<br>
  MEDAN, Jam 6 : 89.71<br>
  MEDAN, Jam 7 : 109.60<br>
  MEDAN, Jam 8 : 133.09<br>
  MEDAN, Jam 9 : 140.42<br>
  MEDAN, Jam 10 : 143.89<br>
  MEDAN, Jam 11 : 162.02<br>
  MEDAN, Jam 12 : 163.93<br>
  MEDAN, Jam 13 : 142.81<br>
  MEDAN, Jam 14 : 140.22<br>
  MEDAN, Jam 15 : 144.56<br>
  MEDAN, Jam 16 : 159.95<br>
  MEDAN, Jam 17 : 178.96<br>
  MEDAN, Jam 18 : 205.30<br>
</div>
Medan is the location, Jam is the hour.

**Comment by sminnemeyer** [comment]
The Indonesia Meteorological Agency (BKMG) recently updated their website and the URL has changed. 
The BKMG website can be accessed here: http://www.bmkg.go.id/?lang=EN 
The individual pollutants can be accessed under the heading "Air Quality/Kualitas Udara"; here's the link for the PM10 page http://www.bmkg.go.id/kualitas-udara/informasi-partikulat-pm10.bmkg 

I plan to work with the WRI Indonesia office to determine the best contact for BKMG to request official permission to use the data.

**Comment by sruti** [comment]
It would be good to look into this source and see if it still exists/meets the following requirements:

- [ ]  Data is ‘raw’ and reported in physical concentrations not in an 'Air Quality Index' or equivalent (e.g. AQI, PSI, API) format

- [ ] Data is at the ‘station-level' with geographic coordinates, not aggregated into a higher (e.g. city) level

- [ ] Data is from measurements averaged between 10 minutes and 24 hours

- [ ] (Nice to have) Programmatic access
