### ISSUE TITLE
Portugal

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-fetch#130]
This will not be be necessary if the EEA (#103) source gets pulled in, but it does look like there is more data on the local side than there is in the EEA API. Ticketing a summary of the source in case we do decide to go local.

Data is reported here: http://qualar.apambiente.pt/index.php?page=2
It shows data of that current day. Right after mid-night, until the first measurements of the day are in, all the cells will show `N.D.` (not available).
### Max vs Avg values

Data is reported on an hourly basis, but instead of average values, most of the pollutants show max values:

| pollutant | reports |
| --- | --- |
| O3 | hourly max value |
| NO2 | hourly max value |
| CO | 8-hour max value |
| SO2 | hourly max value |
| PM10 | daily average |
| PM2.5 | daily average |
### Coordinates

Are available in the station details that pop up in the link
### Time

Note that the time is reported in UTC, which is not always equal to the local time. Also, Madeira and the Açores are in a different time-zone than continental Portugal. This is not reflected in the data, meaning that we'll probably have to do a dirty switch based on station name to derive the local time.

**Comment by RocketD0g** [comment]
See: https://github.com/openaq/openaq-fetch/issues/309
