### ISSUE TITLE
Location of Saskawetchan, CA

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#131]
![screenshot from 2016-03-28 09 32 31](https://cloud.githubusercontent.com/assets/194381/14068749/e864e626-f4bf-11e5-8fb0-37e8524904ef.png)

It appears to sit at the equator, but I suspect it should not.

https://api.openaq.org/v1/locations?country=CA&city=SASKATCHEWAN

**Comment by jflasher** [comment]
[Null Island](https://en.wikipedia.org/wiki/Null_Island)! Wonder if it's coming from us or them?

**Comment by jflasher** [comment]
Confirmed that this is coming from the source. 

```
000080402|O3|0402|PA|Active|SK1|Saskatchewan Environment|CA|0.000000|0.000000|0.000|-6.00|CA|||||00|CC|00008|SASKATCHEWAN||
```

Will let them know and close this here.
