### ISSUE TITLE
German data

### ISSUE THREAD

**Issue by dirkschumacher** [openaq/openaq-fetch#137]
Germany has a nice, but undocumented API of nearly all stations across the country. It has no license (I have asked them, but no response so far) and it is probably part of the EEA API #103. 

It currently supports the following pollutants:

pollutant | aggregation | example GET URL 
--- | --- | :--- 
PM10 | daily mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=PM1&data_type=1TMW&date=20160403
SO2 | daily mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=SO2&data_type=1TMW&date=20160402
SO2 | 1 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=SO2&data_type=1SMW&date=20160402&hour=14 
SO2 | 1 hour max | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=SO2&data_type=1TMAX&date=20160402&hour=14
NO2 | 1 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=NO2&data_type=1SMW&date=20160402&hour=14 
NO2 | 1 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=NO2&data_type=1SMW&date=20160402&hour=14 
NO2 | 1 hour max | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=NO2&data_type=1TMAX&date=20160402&hour=14 
O3 | 1 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=O3&data_type=1SMW&date=20160402&hour=14 
O3 | 1 hour max | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=O3&data_type=1TMAX&date=20160402&hour=14 
O3 | 8 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=O3&data_type=8SMW&date=20160402&hour=14 
O3 | 8 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=O3&data_type=8MAX&date=20160402&hour=14 
CO | 8 hour mean | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=CO&data_type=8SMW&date=20160402&hour=14 
CO | 8 hour max | https://www.umweltbundesamt.de/luftdaten/stations/locations?pollutant=CO&data_type=8MAX&date=20160402&hour=14 

Station meta data can be found here:
https://www.umweltbundesamt.de/luftdaten/stations?pollutant=CO&data_type=8SMW&date=20160402&hour=14

Data is used here: 
https://www.umweltbundesamt.de/daten/luftbelastung/aktuelle-luftdaten

**Comment by RocketD0g** [comment]
This is awesome, @dirkschumacher! :+1: 
Thank-you! I'll check to see if this is covered in the EEA API or not.

**Comment by RocketD0g** [comment]
Looking through #103, it's looking like there is significant (and perhaps complete) overlap with the data here. So, closing this for now but once that source is up, if there are any identified gaps with these data, we can pull these in, individually. Thanks!

**Comment by ElFrogster** [comment]
Hello, I am new to all of this, but at least when looking at the openaq explorer it seems like it does not have a lot of the data the Umweltbundesamt has.

![Screenshot2](https://github.com/openaq/openaq-fetch/assets/123737003/691ea5c8-19db-473f-af6d-6346bb618e4c)
![Screenshot1](https://github.com/openaq/openaq-fetch/assets/123737003/06d35bb1-5102-42e8-8516-11ee7404f37a)

Also it seems like there is an offical documented api now

https://luftqualitaet.api.bund.dev/

**Comment by russbiggs** [comment]
Hi @ElFrogster the map view your seeing in Explorer filters the data by parameter, so the "missing" stations youre seeing likely just dont measure the pollutant you are currently filtering to. You can see on this map the coverage looks much closer to the luftqualitaet.
<img width="717" alt="Screenshot 2024-02-02 at 9 46 17 AM" src="https://github.com/openaq/openaq-fetch/assets/8487728/6a1eb50d-d062-437d-be13-599adb005d84">

Your comment is great validation for an update I am working on as we speak to show all locations, regardless of parameter, to help resolve this confusion.

**Comment by ElFrogster** [comment]
Ok, got it! Yeah, now it seems to line up pretty well.
