### ISSUE TITLE
Question about locations

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq-fetch#138]
In the location endpoint firstUpdated is the date at which the location is added to the platform. What would happen if a parameter was added to the location? Could it get its own firstUpdated value?

**Comment by jflasher** [comment]
So the lastUpdated/firstUpdated is actually dependent on the parameter set you're looking at. If you don't specify anything in particular, you get the first and last updated across all parameters. However, if you add `parameter=pm25`, you'd get first/last updated for *only* the pm25 values.

**Comment by masalmon** [comment]
Oh this is nice!!
