### ISSUE TITLE
New Data: Queensland, AU

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#145]
From an email: 

https://openaq.org/#/sources doesn’t appear to have our online data for the Australian state of Queensland. [ https://data.qld.gov.au/dataset/air-quality-monitoring-live-data-feed   ]

Also released at https://www.google.com.au/?gfe_rd=cr&ei=OcYFV8D5EKHM8ge9m7DYCQ&gws_rd=ssl#q=air+quality+monitoring+datasets+queensland+open+data such as https://data.qld.gov.au/dataset/air-quality-monitoring-2012

**Comment by dolugen** [comment]
url: http://www.ehp.qld.gov.au/cgi-bin/air/xml.php?category=1&region=ALL
sourceURL: https://data.qld.gov.au/dataset/air-quality-monitoring-live-data-feed/resource/50410fbe-8766-45cd-a259-c4c1f3c89dd1

Looks like the resource is updated once a day and only keeps the current day's data up there.

**Comment by jflasher** [comment]
Thanks @dolugen. Just a note to anyone else looking at this, urls in the XML seem to be like `http://www.ehp.qld.gov.au/air/data/http://www.qld.gov.au/environment/pollution/monitoring/air-monitoring/seq/` (note the dual `http` which breaks things).

Also, any way we can get the coordinates? Didn't see them available anywhere. @RocketD0g could we reach back out to the original mailer? Other than that, seems pretty straightforward to add.

**Comment by RocketD0g** [comment]
Great and thanks, @dolugen and @jflasher ! I will reach out the original person to ask about coordinates and update when we get more info.

**Comment by RocketD0g** [comment]
I heard back about the coordinates. I haven't gone through the page in detail yet, but it looks like the Queensland coordinates (as well as others ) are linked off of this page by station location: https://data.qld.gov.au/dataset/air-quality-monitoring-2015

**Comment by jflasher** [comment]
An update here, looked at how to get coordinates and there doesn't seem to be a way to get from the XML to the coordinates for each location. This means we'll most likely need to hardcode the values.

**Comment by dolugen** [comment]
@jflasher How do you go about getting coordinates of stations? Also, I want to confirm that the provided values are in the system's preferred unit.

**Comment by dolugen** [comment]
And I don't know what their averagingPeriod is.

**Comment by jflasher** [comment]
@dolugen I think we'd need to grab the coordinates from the page referenced above and hardcode them. Not the best, but not sure what else we can do. averagingPeriod can probably be inferred from data update times.

**Comment by dolugen** [comment]
Thanks, I didn't notice that page before. I followed up and poked around a bit, and found that the website is actually a frontend for a system called [CKAN](ckan.org). First time I've heard of it. The great thing is we can access the yearly datasets (from 2010 to 2015) through the API and possibly import them to OpenAQ.

A question here: What's the recommended way to import an existing dataset? It wouldn't be an adapter, but a processor. I'm not sure where it fits in the pipeline.

I've also wrote to Queensland Government in hopes that they'd attach station coordinates to their live feed. Worth a try.

PS: Should there be a distinction made that the data comes from a dataset or a live feed?

**Comment by dolugen** [comment]
We might have the coordinates in the feed in the future, but in the meantime I can use [this list of coordinates](https://data.qld.gov.au/dataset/environmental-monitoring-site-locations/resource/37eab16f-d391-44e3-93aa-b0dac0a6a2d8) (kindly pointed to by the government officer).

**Comment by jflasher** [comment]
Oh, nice on the coordinates. We've got https://upload.openaq.org/ that's mostly ready to go I believe, just not officially launched yet. It's intended as an upload mechanism for one-time uploads. It still needs an adapter written to run and do the import.

**Comment by dolugen** [comment]
Could we have the parameter->preferredUnit mapping as a utility for adapters? Or the base database handler could just set the preferredUnits when possible.

Also, I wish there were a coordinates-to-city-name service :pray:

**Comment by dolugen** [comment]
> Also, I wish there were a coordinates-to-city-name service :pray: 

There is one: [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/start)

**Comment by jflasher** [comment]
> Could we have the parameter->preferredUnit mapping as a utility for adapters? Or the base database handler could just set the preferredUnits when possible.

@dolugen can you open this up as a separate issue?


> Also, I wish there were a coordinates-to-city-name service

Also, if you have more of an idea on how this might work with the API or fetch, please open a separate issue to discuss. Don't want things to get buried in this issue.

**Comment by dolugen** [comment]
> can you open this up as a separate issue?

Okay!

> Also, if you have more of an idea on how this might work with the API or fetch, please open a separate issue to discuss. Don't want things to get buried in this issue.

I'll open a discussion issue on this.

**Comment by jflasher** [comment]
Just fyi, looking at the data now it looks like coordinates were added, very cool!

```xml
<station name="Mountain Creek" information="http://www.qld.gov.au/environment/pollution/monitoring/air-monitoring/seq/#mountaincreek" longitude="153.1038" latitude="-26.6917">
<measurement name="Nitrogen Dioxide" index="3" rating="1" rating_name="Very Good">0.003</measurement>
<measurement name="Ozone" index="20" rating="1" rating_name="Very Good">0.02</measurement>
<measurement name="Particle PM10" index="29" rating="1" rating_name="Very Good">14.3</measurement>
<measurement name="Visibility" index="5" rating="1" rating_name="Very Good">11</measurement>
</station>
```

**Comment by dolugen** [comment]
> Just fyi, looking at the data now it looks like coordinates were added, very cool!

That's good news! 👍 

Just a reminder, that SW Queensland stations are missing coordinates.

**Comment by jflasher** [comment]
> Just a reminder, that SW Queensland stations are missing coordinates.

Yep, we've reached out to initial source to get them added and the adapter will start adding these measurements when they are.
