### ISSUE TITLE
Data from Israel

### ISSUE THREAD

**Issue by maelle** [openaq/openaq-fetch#146]
The website is http://www.svivaaqm.net/Default.rtl.aspx

When playing with grey buttons on the right I e.g. got the two tables I'm attaching.

![israel](https://cloud.githubusercontent.com/assets/8360597/14472311/e0fc7aa4-00f2-11e6-9086-e41ce56f37c6.png)
![israel2](https://cloud.githubusercontent.com/assets/8360597/14472312/e118fbe8-00f2-11e6-8ffb-e15c0ab892f0.png)

**Comment by masalmon** [comment]
"נתוני ניטור בזמן אמת" means "real time monitoring data"

**Comment by masalmon** [comment]
and for instance "חיפה וקריות" is "Haifa and its suburbs"

**Comment by masalmon** [comment]
Last thing for today, the column name on the right in the table is "station name".

**Comment by dolugen** [comment]
Anyone know Hebrew?

**Comment by masalmon** [comment]
Should we make a Twitter call for help?

**Comment by jflasher** [comment]
If we leave the place names in Hebrew, I think we don't need to know any to grab the data? Only thing I don't see is lat/lon.

Does leaving the names in Hebrew sound good? Otherwise I guess we'd be hardcoding translations.

**Comment by RocketD0g** [comment]
Sounds good to me!

**Comment by masalmon** [comment]
A.k.a. "If you have encoding issues in your code, you won't miss them now" :grinning:

**Comment by jflasher** [comment]
😁

**Comment by masalmon** [comment]
I think that for each station this page http://www.svivaaqm.net/StationInfo5.aspx?ST_ID=11 gives lon and lat?

**Comment by jflasher** [comment]
Nice! Any way to get from that main page to the station pages? Is there an ID or similar?

**Comment by masalmon** [comment]
קו אורך is longitude.

you get the station ID when your mouse is on the station name

![israel](https://cloud.githubusercontent.com/assets/8360597/21145400/64dcb1a6-c14e-11e6-8e1c-1f2690b1435a.png)

**Comment by masalmon** [comment]
(station name being the column in Hebrew)

**Comment by masalmon** [comment]
On each station page clicking on the button in the red circle on this pic, you get to a data query page. I guess one could get historical data from there?

![station](https://cloud.githubusercontent.com/assets/8360597/21145459/b3e48292-c14e-11e6-96a6-3bf311b6a344.png)

**Comment by masalmon** [comment]
I'll stop looking at this now, but there seems to be much data. :-)

**Comment by RocketD0g** [comment]
**To recap in a condensed comment, as well as to address a time stamp issue:**

1. Go here: http://www.svivaaqm.net/Default.rtl.aspx

2. Click here for "Real-time monitoring data"
![screen shot 2017-06-26 at 11 51 52 am](https://user-images.githubusercontent.com/13404290/27548100-e1f0d572-5a65-11e7-9aed-b5146da15de6.png)

3. This will bring a drop down menu of regions. Click on any one of them, and you will see a table listing various pollutants (measured in physical units)

The red circled boxes from left to right: Time Stamp (military time, thenn day-month-year) and Station Name.
![screen shot 2017-06-26 at 11 57 27 am](https://user-images.githubusercontent.com/13404290/27548338-b4ac94f6-5a66-11e7-8c0a-53907a28b9d6.png)

Note: On this page, you will also find 

4. Click on Station Name to get this view, which lists station name (top box) and longitude (top number in bottom box) and latitude (bottom number in bottom box):
![screen shot 2017-06-26 at 12 08 03 pm](https://user-images.githubusercontent.com/13404290/27548857-39e79200-5a68-11e7-95fe-5aa3bd1f93cf.png)

5. **Important note:** The data _appear_ to report every 5 minutes, as 5 minute averages, though it is not entirely clear. This is faster than OpenAQ currently has the ability to report back. You can also query the system for each station to report back 15 minute (or otherwise specified averages). To do that, do the following:

A. On a given station-level page, click on the "Station Report", highlighted with the red box: 
![screen shot 2017-06-26 at 12 18 59 pm](https://user-images.githubusercontent.com/13404290/27549346-a888827c-5a69-11e7-9305-1a75c951791e.png)

B. You'll get a page like this, and the red box value is the "table" option (The "Excel" option may also work?).  Any averaging time 15 minutes or great would be great to add in (Be sure to select "Avg", press single button on page to continue.

![screen shot 2017-06-26 at 12 21 03 pm](https://user-images.githubusercontent.com/13404290/27549432-f3c13fb8-5a69-11e7-8496-37611f28a5be.png)

C. This produces a table with the real-time data for a given specified time period that looks like this: (note: it may be displayed on several pages):
![screen shot 2017-06-26 at 12 26 28 pm](https://user-images.githubusercontent.com/13404290/27549702-e6a5120e-5a6a-11e7-8663-8c129a837b82.png)

**Comment by maxgrossman** [comment]
@dolugen, @RocketD0g, @maelle, and @jflasher.

Morning from DC!

I've spent a good amount of time working through the above steps for the Israel adapter.
Doing so has proved...challenging.

The form is an asp.net form, providing a number of complications I'd be happy to detail in the discussion. The short of it is sending a request.post() with the form object exposed when one submits the form manually does not return the table we want. A potential option to get around this is using something like [phantomjs-node](https://github.com/amir20/phantomjs-node) or [horseman](https://github.com/johntitus/node-horseman) to render pages. However, rendering is not very resource 'light'.

Having said that, we can easily fetch the [page](http://www.svivaaqm.net/StationInfo5.aspx?ST_ID=11) that includes coordinates + the most up to date recordings quite easily. All the links we need are exposed, so it's a matter of using cheerio to get links, then request to get tables + coordinates.

I started working on that last night and pushed it to my [adapters/israel branch](https://github.com/openaq/openaq-fetch/blob/adapters/israel/adapters/israel.js) just now.

So, given the complications with using the form, do we all think it is ok to use the pages with coordinates + up to date recordings?

I recognize this might create vulnerability that we gather data with slightly inconsistent deltas between recordings. I don't know if their update is exactly every 5 minutes, or 5 minutes + some change. However, for keeping processes 'lightweight', it may make sense to use those pages.

Looking forward to your feedback!

**Comment by maxgrossman** [comment]
...in fact for those who are interested in the attempts to scrape the form w/request, here's the [diff](https://github.com/openaq/openaq-fetch/commit/ffc1bf00028bdd5def6f2f9c9392c3581ddc9558) between 2 commits I made.

**Comment by jflasher** [comment]
Do we think the update time for this source is every 5 minutes? That'd be 10 minutes faster than the current quickest.

**Comment by RocketD0g** [comment]
I believe you can also query the system for 15 minute updates (outlined in step 5 above). Could that work?

**Comment by maxgrossman** [comment]
@jflasher 
The update times seem to have a 5 min delta, but the actual report times are inconsistent actually on second look. Some stations update every 30 mins, others 10 mins... That means the page re-renders ever few minutes, but the actual values only update on the station update interval.

See [here](http://www.svivaaqm.net/) for reference. 

@RocketD0g 
I also just checked in the form and the interval you can specify in the query is germane to the update interval. So, if the station only updates ever 30 mins, then the shortest interval option you have is every 30 minutes.

Also, the issue with trying to scrape the form is not so much providing the parameters for the interval and desired pollutants etc, but rather these special params that asp.net forms use + actually grabbing the returned table.

**Comment by jflasher** [comment]
@maxgrossman I think any way we can get the data is fine, no need to go the form route if there is a better way to do it.

My bigger concern is about the update time. Every 10 minutes, fetch will load the page, so if the underlying measurements are happening at a 10 minute or less interval, we could be missing some occasionally. It's not a problem if they locations update on different intervals, only a problem if a given location updates at <= 10 minutes.

**Comment by maxgrossman** [comment]
@jflasher - totally agree w/the under 10 min problem, we might be reporting data at inconsistent deltas. 

That said, @dolugen and I have chatted and I'm going to work through not using the form for Israel for now and he is going to try the form w/South Africa. He and I will circle back up after he does some work to see if the form is feasible.

**Comment by maxgrossman** [comment]
...thankfully for the sake of the project and not so much my coding chops @dolugen was able to figure out gathering data from the form. He's going to try to make his solution dynamic tomorrow. If he is successful I'll refactor the code I just pushed for Israel to match his work as there then is no delta issue at all.

@jflasher @RocketD0g @dolugen

**Comment by dolugen** [comment]
I tried modifying the Richards Bay - Envista adapter (#9) for the Israel source. I made some little changes that got it working on a single station. But when I try to work it on multiple stations, I'm hitting an error page. Probably intended as a 500 page, but it returns with 200. It could be a cookie problem similar to Richards Bay, not sure.

**Comment by dolugen** [comment]
Took another shot at adapting the `envista_za.js` adapter for Israel. It's hit and miss. Sometimes, the export page errors out, and it's random. One time I get 13k results, another time 16k, etc. Error pages are around 10-20. I'm debating whether I need to keep going and figure out what's bugging, or ditch this and go with Max's route and finish that.

**Comment by jflasher** [comment]
Go with your heart. :) Any idea if the problem lies with the source or with the adapter? That is, if you went the other route, think you'd still be seeing the same issues?

**Comment by dolugen** [comment]
Either way, I have no idea what's going wrong. But I'll say that it's the source :) I talked with Max about it, and he's going to incorporate his fetching method onto this one as fallback. So you're getting best of both worlds.

**Comment by Ron-Burg** [comment]
Hello,
I know Hebrew and so I searched the website for a better way to scrape it, and there is actually a dedicated API for it :)
It's very basic but can give you a lot of data (Not historical data but the latest results).
The API has the following endpoints:
1.	list of all stations (without the actual values):
http://www.svivaaqm.net/api/stations
2.	Info about specific station (id=2 in this example):
http://www.svivaaqm.net/api/stations/2?getLatestValue=true

By default, the data is sent back as XML, if you want you can add type=json to get the data as a JSON (http://www.svivaaqm.net/api/stations?type=json).
The API doesn't provide a way to get historical data, but I did manage to find a way to get historical data for multiple stations via the form (but it is painfully slow.. ).

**This is how you can get the historical data with the form:**
1.	Enter http://www.svivaaqm.net/
2.	Select "Generate detailed reports"
![image](https://user-images.githubusercontent.com/26197727/29745148-58b4a04a-8abc-11e7-9069-f542b4c3514f.png)

3.	Select "Multi station report"
![image](https://user-images.githubusercontent.com/26197727/29745152-63ee4f2e-8abc-11e7-93ce-29762c9deabd.png)
 
Then you will get this form:
 
![image](https://user-images.githubusercontent.com/26197727/29745155-6b6ee254-8abc-11e7-9a5a-e5ca8a4932af.png)

-	The checkbox text above the red lines means "All Stations"
-	The blue area is where you can select each station (and even individual types of measurements by expending the station and selecting the specific test)
-	The Black circle shows how many different tests (Not stations) is selected. I couldn't get it to work with all of them, at least not in an acceptable time..
After you fill the form and send it you will get the results as follow:
![image](https://user-images.githubusercontent.com/26197727/29745161-7ee7fbea-8abc-11e7-99e5-2efcb6ed1a00.png)
 
Where "אורט" and "אחד העם" in the first line is the name of the station.

About the samples delta- It says that the data is collected every 5 minutes on all stations. The timestamp is Israel time (+2) and not the Israel daylight saving time (+3).

I hope this helps and if you need any help with the translation I'll be happy to help.

**Comment by dolugen** [comment]
Wow this is great! Thanks a bunch @Ron-Burg! I will have to update the adapter using this.

**Comment by RocketD0g** [comment]
Thanks a million to you both, @Ron-Burg + @dolugen! That is great!
