### ISSUE TITLE
Belgian sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#15]
@olafveerman 's issue transported to this repository:

Measurements for a lot of Belgian measuring stations: http://www.ircel.be/nl/luchtkwaliteit/metingen
This page shows rolling averages for most parameters.

When you drill down, it's possible to get the actual hourly measurements and not the rolling averages. For example:

go to this page: http://www.ircel.be/en/air-quality/measurements/particulate-matter/pm10?set_language=en
click on table with detailed info per monitoring site
Have not found a programmatic way to access this data, it might need to be scraped.

**Comment by RocketD0g** [comment]
Halt on this issue for now: investigating possible lead on open EU AQ API.

**Comment by jflasher** [comment]
Should now be pulled in through EEA source.
