### ISSUE TITLE
Sarajevo - New Data

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#155]
Hourly data here: http://www.fhmzbih.gov.ba/latinica/AKTUELNI/A-zrak.php

No coordinates listed, and sending an email.

**Comment by jflasher** [comment]
What do you think the difference is between the two tables? The one on the left looks to be a day behind? The one on the right is updated on the :30 (at least that I just saw)?

**Comment by RocketD0g** [comment]
The one on the right is hourly average, the one on the left is daily (and goes with total 24 hours from day before, it seems). So think we'd want the one on the right. All units are in ug/m^3.

**Comment by RocketD0g** [comment]
Found the station coordinates, too: (Can convert into decimal form later)

**For Sarajevo stations:**
- Bjelave: 18° 25' 23'' E, 43° 52' 03'' N for  SO2, NOx, CO, O3:
                18° 25' 22'' E, 43° 52' 04'' N for PM10
- Vijećnica: 18° 21' 49'' E, 43° 50' 54'' N
- Otoka:  18° 21' 59'' E, 43° 50' 58'' N
- mobilna (Ilidža): = 18° 18' 49'' E, 43° 49' 40'' N 
                               [While station can be mobile, it is set up at these coordinates]
- Ivan Sedlo: 18° 02' 10'' E, 43° 45' 04'' N

**For Jajce stations:**
- Harmani: 17° 16' 05'' E, 44° 20' 35'' N

**For Zenica stations:**
- Centar:17° 54' 46'' E, 44° 11' 57'' N
- Radakovo: 17° 55' 55'' E, 44° 11' 43'' N
- Tetovo:  17° 53' 28'' E, 44° 13' 32'' N
- Brist: 17° 54' 02'' E, 44° 12' 08'' N

**For Goražde stations:**
- Radadinik: Can't find.


_Source:_ http://www.fhmzbih.gov.ba/PUBLIKACIJE/zrak/2015/zrak-2015.pdf
