### ISSUE TITLE
Index coordinates

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#158]
I should've just posted here at the first time, but from dolugen/openaq-browser#2:

I said:
> Location and measurement queries by coordinates seem a bit slow. It's taking several seconds for a fresh query for me.

@jflasher said:
> Yep, looks like we just need to make an index on the `coordinates` field explicitly. The aggregation endpoints are handled using `turf` server side, so it makes sense they're still quick.

> http://postgis.net/docs/manual-1.3/ch03.html#id434676

**Comment by jflasher** [comment]
@dolugen can you take a look at some `measurements` queries with coordinates again? I just tried creating an index like in the index above, and even though it was being used, didn't see a huge speed boost. You can see in the logs below, the queries just seem to take a bit of time (roughly same with index created on `coordinates`).

```
openaq-production=> select * from measurements where ST_DWithin(coordinates, ST_MakePoint(-70.188, -22.0855), 2000) limit 100;
Time: 209.984 ms
openaq-production=> select * from measurements where ST_DWithin(coordinates, ST_MakePoint(-70.188, -22.0855), 2000) limit 1000;
Time: 1818.391 ms
openaq-production=> select * from measurements where ST_DWithin(coordinates, ST_MakePoint(-70.188, -22.0855), 20000) limit 1000;
Time: 1776.409 ms
openaq-production=> select * from measurements where ST_DWithin(coordinates, ST_MakePoint(-70.188, -22.0855), 200) limit 1000;
Time: 2493.869 ms
```

However, none of these should be timing out like you saw. If you see that again, can you point me to the exact queries (could be location specific for some reason?).

**Comment by dolugen** [comment]
The response times were under a second in queries I checked :+1: 

> However, none of these should be timing out like you saw. If you see that again, can you point me to the exact queries (could be location specific for some reason?).

I'm not seeing any more time outs, I'll let you know if I see one.
