### ISSUE TITLE
Skopje, Macedonia - Data Sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#16]
Hourly data for each pollutant, using the following configuration shown in this attached image:
![screen shot 2015-08-30 at 9 31 52 pm](https://cloud.githubusercontent.com/assets/13404290/9570641/cbb08fbe-4f5e-11e5-8677-86a13ec6b358.png)

**Comment by dolugen** [comment]
The source URL is http://airquality.moepp.gov.mk/?page_id=4&lang=en

The "Table" option is disabled right now. I don't know if that's temporary or not. You can enable the option with a DOM inspector.

**Comment by RocketD0g** [comment]
Thanks for adding the source url @dolugen, my bad! The table will also activate if you hit the 'day' option; it just doesn't like the 'week' option. The units for this can be gotten off of the graph. The locations can be found at measurements--->descriptions of monitoring sites.

**Comment by jflasher** [comment]
MK is now included via EEA source.
