### ISSUE TITLE
coordinates Test Prueba Santiago CL Chile - SINCA

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq-fetch#170]
They are 3.155026, 3.881017 which seems weird but "Test Prueba" probably means it's a test thing, maybe a field blank?

**Comment by jflasher** [comment]
Oh weird. This definitely doesn't seem like good data, but don't think there is any way to really catch this. Something maybe we can make the AirNow operators aware of.

Thanks for catching this @masalmon !

**Comment by masalmon** [comment]
Is SINCA AirNow?

**Comment by jflasher** [comment]
Oh woops. It's not, had just answered the other AirNow thing.

**Comment by masalmon** [comment]
If you write to them the webpage for the station http://sinca.mma.gob.cl/index.php/estacion/index/id/269 gives credible coordinates on the right but the map on the left shows the wrong coordinates.

**Comment by masalmon** [comment]
(I say credible because they look like the other coordinates for the same city)
