### ISSUE TITLE
Historical Data from Spartan 

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#171]
Hourly PM2.5 and BC data for several locations around world are here: 
http://www.spartan-network.org/instrumentprotocol.html

(see zipped folder for hourly data)

Attached are coordinates: 
[Site lat long info..docx](https://github.com/openaq/openaq-fetch/files/288130/Site.lat.long.info.docx)

For attribution:List SPARTAN data as follows: SPARTAN Network  and url: spartan-network.org 

@jflasher, tagging you since we discussed this particular format/source.

**Comment by jflasher** [comment]
Closed with https://github.com/openaq/openaq-fetch/pull/173
