### ISSUE TITLE
Add in two properites to the data format

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#175]
Per our discussion here: https://github.com/openaq/openaq-data-format/issues/8

Let's add: 

Additional Tag # 1: `sourceType` 
This delineates which of three data sources type from which the data originates:

1. `government` - Sensors that are deployed by or on behalf of governmental bodies. 
2. `research` - Sensors that are deployed by researchers affiliated with universities and/or research organizations.
3. `other` - Sensors that are deployed by citizen scientists, often low-cost sensors.

Additional Tag # 2: 
`mobile` - This is either T/F, and indicates whether the source is stationary or mobile.

**Comment by jflasher** [comment]
Closed with https://github.com/openaq/openaq-fetch/pull/173. Will still need to add access to properties via API.
