### ISSUE TITLE
Increasing query time for count() for every request

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#180]
As we've been adding more data, we're seeing an increased query time on the `count()` query. This runs before every API request to `/measurements` so we can do the paging. With parameters included, it's not so bad ~50ms, but when going over the full dataset, it can take 1 - 2s, which is slowing down all the requests.

Did a quick search and didn't see a great way to solve this. We're already counting over an indexed field and we need the exact number and to be able to pass parameters to the query.

**Comment by jflasher** [comment]
Pinging @scisco since he asked to be brought into the conversation. We could potentially look at caching the total number of measurements instead of doing the count each time or caching it for some of the more popular queries based on analytics.

**Comment by scisco** [comment]
@jflasher do we use Redis or other caching mechanisms? In other words, is redis available for use or it has to be added?

**Comment by jflasher** [comment]
@scisco yep, we do have access to Redis. Every 10 minutes when new data is inserted into db, the API receives a notice that new data has been added and runs some queries and caches the results https://github.com/openaq/openaq-api/blob/develop/api/controllers/webhooks.js#L45.

**Comment by scisco** [comment]
cool. thanks

**Comment by jflasher** [comment]
@reinh of potential interest to you.
