### ISSUE TITLE
Missing SPARTAN data for three locations.

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#181]
Looks like Canadian, South African, and Argentinian sources aren't making it to the platform. Probably a formatting issue. Note to self to look at csv files on SPARTAN site to see.

**Comment by abarciauskas-bgse** [comment]
Looks like this is still an issue for Canada and South Africa locations.

I see data for Argentina listed under id `14` and see `2448` measurements going back to 2015.

https://docs.openaq.org/v2/measurements?date_from=2000-01-01T00%3A00%3A00%2B00%3A00&date_to=2021-03-07T19%3A10%3A00%2B00%3A00&limit=100&page=1&offset=0&sort=desc&radius=1000&location=14&order_by=datetime

Here are the sources locations that seem to be missing:

https://www.spartan-network.org/halifax-ca
https://www.spartan-network.org/kelowna-ca
https://www.spartan-network.org/lethbridge-ca
https://www.spartan-network.org/sherbrooke-ca
https://www.spartan-network.org/toronto-ca
https://www.spartan-network.org/pretoria-south-africa
