### ISSUE TITLE
Move from PostgreSQL to Elasticsearch?

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#182]
There has been some talk of potentially moving from PostgreSQL to Elasticsearch. We're seeing a bit of a slowdown with Postgres, but I think that's more down to me not properly optimizing the database rather than anything inherent in the db. But as we accelerate number of datapoints we're collecting, is Postgres the final best answer? Should we use something like Elasticsearch? Or something else?

A couple of things to keep in mind as we think over other potential options
- We're collecting around 100K datapoints a day and that'll increase we we add a source like EU.
- We want to provide access to all historical datapoints
- There is also value in aggregation results (around all locations or cities or countries) so we'd need to be able to accommodate that
- We're going to be looking to bring on low-cost sensor data in the near future which could be a lot of data (open questions about how much we store, etc), but do we try to use the same system for those measurements or something different?

cc/ @dolugen @scisco @reinh

**Comment by fpedrera** [comment]
In our team we have a couple of experiences dealing with tens of millions of rows in PostgreSQL/PostGIS under Carto (http://www.carto.com) and making spatial and aggregation queries. 

From our experience, we were able to optimize the performance by using these mechanisms: 

- Using composite indexes: https://www.postgresql.org/docs/9.5/static/indexes-multicolumn.html
- Using partial indexes: https://www.postgresql.org/docs/9.5/static/indexes-partial.html
- Working on the query itself, by using EXPLAIN ANALYZE on the query. 

Anyway, we are far for being experts, and we mainly followed the advice given by the Carto team and its CTO @javisantana. 

Anyway, some question arise: 
- What version of PostgreSQL are you using? Version 9.5 introduces some big data features: https://www.postgresql.org/about/news/1636/
- What kind of queries are you doing? We could take a look on them if you indicate the files on the GitHub repo with the queries. 

About moving to Elastic Search, I would first try to fine tune the PostgreSQL database before moving to manage an Elastic Search cluster.

**Comment by jflasher** [comment]
Summarizing some other items that came up in Slack.

> So as far as the config goes, the only values I might change are "work_mem" - currently set to 4MB... you can push that up... it is the max memory allowed to be used for a query workspace and might contribute to some of your slowdowns. I'd push it up to 100mb - and default_statistics_target  --- this is set to 100 now which is the default. This basically impacts the query planner. Pushing it higher allows for better query plans, but also means that when you manually run ANALYZE on the table, it will take longer. You can go up to 1000 with it, but I'd start with just "work_mem".

And other thoughts around using indexes well came up.

**Comment by jflasher** [comment]
Thanks for the ideas @fpedrera. Going to drop table structure below.

<img width="957" alt="screen shot 2016-09-13 at 2 24 10 pm" src="https://cloud.githubusercontent.com/assets/848934/18473537/d1b40a96-79bd-11e6-9b84-2cde382ce04e.png">

I'll paste the queries below as well. Full disclosure, they could be done horribly, but generally seem to work. It looks like on rare occasions, the index doesn't get used and a sequential scan is done which just brings the whole system to a crawl. For the time being, I've moved to a bigger database, but changing some of the above parameters might help as well.

Latest query (trying to get the latest record for each parameter for each location) - `select * from measurements join (select max(date_utc) max_date, location, city, parameter from measurements group by location, city, parameter) temp on measurements.location = temp.location and measurements.city = temp.city and measurements.parameter = temp.parameter and measurements.date_utc = max_date;`

Locations query (trying to get unique location info and associated metadata like last/first time and counts of measurements) - `select * from measurements join (select max(date_utc) last_updated, min(date_utc) first_updated, count(date_utc), location, city, parameter from measurements group by location, city, parameter) temp on measurements.location = temp.location and measurements.city = temp.city and measurements.parameter = temp.parameter and measurements.date_utc = last_updated;`

Cities/Countries query (getting unique cities) - `select country, city, location, count(location) group by country, city, location order by country;`

**Comment by jflasher** [comment]
Found http://www.davidmkerr.com/2013/11/tune-your-postgres-rds-instance-via.html which has been helpful along with recommendations above, making some of these changes as time permits.
