### ISSUE TITLE
Source AirNow doesn't have a country

### ISSUE THREAD

**Issue by danielfdsilva** [openaq/openaq-fetch#184]
The source `AirNow` appears as source for US based locations but in the `/sources` endpoint it has no country.
![pasted image at 2016_08_02 20_25](https://cloud.githubusercontent.com/assets/1090606/17342413/0a01daec-58f1-11e6-8163-0e17bf1baa3d.png)

**Comment by olafveerman** [comment]
@jflasher 
https://github.com/openaq/openaq-fetch/pull/183 will also be relevant for this discussion.

**Comment by RocketD0g** [comment]
@jflasher will have to answer for sure, but this is prob because AirNow is a source for multiple countries (US, Mexico, Canada). I know that info doesn't help solve the core of the issue for this or #183 though...

**Comment by jflasher** [comment]
Yep, this is on purpose. Everything in the sources files is used unless overwritten by the adapter. In this case, the data is coming from different countries, so I didn't set it in the file. Open to alternate methods of handling this if any come to mind.

**Comment by olafveerman** [comment]
I like the current setup: it reduces the amount of adapters/sources and if another country is added to AirNow, it's automatically picked.

This should probably be solved on the `/sources` endpoint?

**Comment by jflasher** [comment]
Right now the `/sources` endpoint is just pulling form the JSON files I believe. In that case, I'd rather leave as is. What might make more sense to do is to actually populate the data from some kind of query on the db and save as an aggregated dataset like we do for the others.

Are we using the `/sources` endpoint anywhere?

**Comment by danielfdsilva** [comment]
@jflasher actually we are using it in the frontend to get the source url, and other values. Including the count per country.
Maybe the `country` prop could be an array?

**Comment by jflasher** [comment]
Wanted to bring this back up, is this still an issue we need to address?
