### ISSUE TITLE
Turkey - Sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#19]
Map of stations with coordinates and current readings and stations' current data are here (though not on unique urls):

http://www.havaizleme.gov.tr/Default.ltr.aspx

'TÜM İSTASYONLAR' = all stations

Clicking on the stations reveals site coordinates (click 'station description) and pollutant types measured.

(Sidenote: They use an AQI system with breakpoints same as the US EPA)

**Comment by dolugen** [comment]
The site gets the data from a "National Air Quality Monitoring Network" made by [Argate](http://www.argate.com.tr/Hizmetler/HavaKalitesi). Here's a couple of pages:

* http://index.havaizleme.gov.tr/Report/Station
* http://index.havaizleme.gov.tr/Station/StationInfo/5#
* All Stations table http://index.havaizleme.gov.tr/Dynamic/0 

But you'll be redirected to the www page if you try to go to the homepage.

All station coordinates can be returned at http://index.havaizleme.gov.tr/Map/GetStationLastReceived/0?useLowest=False, but you probably need the cookies from the www page.

**Comment by RocketD0g** [comment]
Physical values with identified units are shown,too, which is good. Note,
if you translate the page from Turkish into English in chrome, 'µg/m³'
looks like 'mg/m^3.' Looks like gaseous (non-PM) compounds are in mass
concentrations instead of preferred volume concentrations, but the system
accepts this, yeah @jflasher?

On Thu, Feb 25, 2016 at 9:20 PM, Dolugen Buuralda <notifications@github.com>
wrote:

> The site gets the data from a "National Air Quality Monitoring Network"
> made by Argate <http://www.argate.com.tr/Hizmetler/HavaKalitesi>. Here's
> a couple of pages:
>
>    - http://index.havaizleme.gov.tr/Report/Station
>    - http://index.havaizleme.gov.tr/Station/StationInfo/5#
>    - All Stations table http://index.havaizleme.gov.tr/Dynamic/0
>
> But you'll be redirected to the www page if you try to go to the homepage.
>
> All station coordinates can be returned at
> http://index.havaizleme.gov.tr/Map/GetStationLastReceived/0?useLowest=False,
> but you probably need the cookies from the www page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaq/openaq-fetch/issues/19#issuecomment-189081938>.
>



-- 

507.246.2097

**Comment by jflasher** [comment]
Yep, the system will accept anything in ppm or µg/m³.

**Comment by RocketD0g** [comment]
This data source has broken. 

I haven't explored what exactly is going on precisely, but this website is still where the data are at: http://www.havaizleme.gov.tr/

**Comment by RocketD0g** [comment]
Update: 

- [This page](http://index.havaizleme.gov.tr/Dynamic/0) lists the data in a table format. 

- 100+ stations (most common pollutant measured is PM10).

- Location information seems available when you click on a location for more station information via a map, though don't see coordinates directly. I wonder if there is something we can do with the broken adapter and connecting it to those matching station names/coordinates.

**Comment by sruti** [comment]
I think we have everything we need for this source! 

Note: 

- the website seems to be about 12hrs behind the table, which is up to date. 

- the averaging period can be found on the site (Saatlik Ortalama)
- seems like the timestamp for the table is the beginning of the measurement period since currently it says 22:00 and the time in Turkey is 10:22 PM
