### ISSUE TITLE
Japanese Sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#20]
Japanese data was listed as a priority as we got a request to have this in our database longterm:

Sources for Yokohama:

http://cgi.city.yokohama.lg.jp/kankyou/saigai/data/taiki/all/all_0000_00_001.html
http://www.ihe.pref.miyagi.jp/telem/dayreportitem/?itemSelect=10&day=2015%E5%B9%B410%E6%9C%8804%E6%97%A5

Appears to be hourly but unsure. Joe is contacting Miyagi Prefecture regarding details, potentially existing API, station coordinates.

Tokyo: 
Just oxides? Need help with translation:
http://www.ox.kankyo.metro.tokyo.jp/index.php?chiku=1
http://www.ox.kankyo.metro.tokyo.jp/

Main page: http://www.kankyo.metro.tokyo.jp/nature/index.html

**Comment by dolugen** [comment]
Any updates on this since 2015?

**Comment by jflasher** [comment]
I think we're probably on hold here until we get someone to help us understand page contents.

**Comment by dolugen** [comment]
Links for more japanese cities http://japan.census.okfn.org/dataset/air-quality

**Comment by RocketD0g** [comment]
Thanks, @dolugen! These will be added in as someone in the community has the bandwidth to pick it up, check it meets our [data format requirements](https://github.com/openaq/openaq-data-format), and writes the scraper tool (or otherwise figures out how to access the data).

**Comment by dolugen** [comment]
More on the Tokyo source:

- Data URL: http://www.taiki.kankyo.metro.tokyo.jp/cgi-bin/bunpu1/p160.cgi?no2=1501307014=1501307014=1=800=2====2=#chap1
  It shows the latest AQ.
- About measurements and units: http://www.taiki.kankyo.metro.tokyo.jp/bunpu1/air1/tanni.html
  Describes the measurements, their units, and averaging periods.

**Comment by RocketD0g** [comment]
One note on Japanese data: I learned this week that Japanese data will soon be shared through the US EPA AirNow system (identically to how we pull in Mexico and Canadian data). I'm not precisely sure on the timeline, but it sounded on the order of months. Thoughts on putting this issue on hold? 

(If we do, I'm putting a marker on my calendar so that, if, in 6 months, there is no change, we revisit 'unholding')

**Comment by RocketD0g** [comment]
Meanwhile, the folks from Yokohama did get back to us and here is a link to the coordinates for Yokohama stations (lower down on the page): http://www.city.yokohama.lg.jp/kankyo/mamoru/kanshi/map16/airplc.html

**Comment by AreteY** [comment]
Tokyo as of 2018 has AQ monitoring conducted by the Tokyo Metropolitan Government, Bureau of Environment ([https://www.kankyo.metro.tokyo.lg.jp/en/automobile/monitoring.html](url)). AQ data is updated hourly at this site, [https://www.taiki.kankyo.metro.tokyo.lg.jp/taikikankyo/realtime/index_en.html](url); stations can also be read in Japanese by changing the language at the top. More information may be here about the monitoring stations (and hopefully the station coordinates): [http://soramame.taiki.go.jp/](url)

**Comment by sruti** [comment]
Update on this: we got in touch with someone at the Japanese Ministry of Environment and they were able to point us to the right place to get the data and sent us a file with the station coordinates, so we have all the information needed to write this adapter!
- Direct download of all data: http://soramame.taiki.go.jp/DownLoad.php
- File with station ids and coordinates:
[Air quality measurement station  Coordinates rev2020.3-1.xlsx](https://github.com/openaq/openaq-fetch/files/4470557/Air.quality.measurement.station.Coordinates.rev2020.3-1.xlsx)
