### ISSUE TITLE
Fetch Dutch locations dynamically

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#22]
Originally created by @olafveerman :
Coordinates for the Dutch stations are hard-coded in the adapter: https://github.com/openaq/openaq-api/blob/master/adapters/netherlands.js#L98

Instead, they should/could be parsed from: http://www.lml.rivm.nl/meetnet/index.php

**Comment by RocketD0g** [comment]
Halt on this issue for now: investigating possible lead on open EU AQ API.

**Comment by dolugen** [comment]
> Instead, they should/could be parsed from: http://www.lml.rivm.nl/meetnet/index.php

Any idea how to parse the map? I don't know how to access the marker data.

**Comment by jflasher** [comment]
If you view source on the page, you see a bunch of `addMarker()` functions that look like below, I think that'd do it?

```
addMarker(51.5475, 5.8382, 'Zuid', '<div id=lml_info><div id=lml_naam>NL10243<br>De Rips-Blaarpeelweg</div><table><tr><td width=25% class=lml_omschrijving>eigenaar<td class=lml_omschrijving>RIVM<tr><td width=25% class=lml_omschrijving>zone<td class=lml_omschrijving>Zuid<tr><td width=25% class=lml_omschrijving>co&ouml;rdinaten<td class=lml_omschrijving>51.5475, 5.8382<tr><td width=25% class=lml_omschrijving>componenten<td class=lml_omschrijving>NH3&nbsp;&nbsp;PM10&nbsp;&nbsp;</table><a href=../histo/index.php?stat=NL10243>naar de metingen van dit meetpunt</a></div>', '<div class=tooltip>De Rips-Blaarpeelweg</div>');
```
