### ISSUE TITLE
New Data Source - Poland

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#226]
This was contributed by someone via email. I have not yet verified if it is also picked up in the EEA dataset:

it would be great if you could add a new source - station at Mewy Street, Gliwice, Poland.

http://powietrze.katowice.wios.gov.pl/stacje/stacja/4

**Comment by dolugen** [comment]
Marking it as "on hold" until verified not duplicate.

**Comment by jflasher** [comment]
Closing as I believe we're good with https://github.com/openaq/openaq-fetch/pull/550. Feel free to reopen if needed.
