### ISSUE TITLE
Buenos Aires tagged as Brazil

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-fetch#227]
A Spartan station has Buenos Aires tagged as Brazilian: https://api.openaq.org/v1/locations?location=SPARTAN%20-%20CITEDEF
Should probably be `AR`.

**Comment by jflasher** [comment]
Good catch, probably totally my fault, I might've put in as wrong country. Updated in database and will be fixed in adapter in a moment.

For future reference, code to update fields inside JSON is like below

```update measurements set country='AR', data=to_json(jsonb_set(to_jsonb(data), '{country}', '"AR"')) where location = 'SPARTAN - CITEDEF'```
