### ISSUE TITLE
Louisville KY Monitor Data

### ISSUE THREAD

**Issue by schnuerle** [openaq/openaq-fetch#231]
Louisville KY city government (where I work) has an air quality monitoring API, with current stats and geolocation of points.  Here is the official link: https://aaws.louisvilleky.gov/api/v1/Monitor/CityAQI

Can you add it as a resource to your map?  Thanks for your work!

**Comment by dolugen** [comment]
Thanks @schnuerle!

OpenAQ has access to AirNow data, so let's see if there's any station that's not already in the system. Here are the corresponding station descriptors in the two sources:

Louisville KY | AirNow
-----------------|----------
Louisville Police Firearms Training Center | Firearms Training
Cannons Lane Air Monitoring Station | Cannons Lane
KyDAQ Monitoring Station in Buckner - Seasonal Monitor | BUCKNER
Bates Elementary School | BATES
Southwick Community Center | Southwick Community
KyDAQ Monitoring Station in Shepherdsville - Seasonal Monitor | SHEPVILL
Durrett Lane Near Road Site (30m from I-264) | Near Road
Watson Lane Elementary School, Valley Station | WATSON

The AirNow names are truncated, but the coordinates match. They're all in OpenAQ API! :smiley:
