### ISSUE TITLE
Missing PM2.5 source in Bangalore?

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#233]
Noted by Gangadhar:

It looks like the AQICN website has PM2.5 data for Bangalore which they claim to get from CPCB. But OpenAQ does not have PM2.5 data for Bangalore. Any idea why this difference?

Comment by Amrit:

I can’t speak for AQICN. But take a look at the KSPCP website. They seem to have PM2.5 data in their PDF files. Don’t know about CPCP though. 
http://kspcb.kar.nic.in/ambient_air_quality.html

You can go to the OpenAQ India page and scroll down to Bangalore and see which pollutant values are being aggregated from which stations. Then, even go to the CPCP website and see if somehow any of them do record PM2.5 or other pollutants that OpenAQ maybe not aggregating.

P.S. I have no way of knowing this, but it is possible that AQICN is using some ratio to guesstimate the amount of PM2.5 in the city based on the real-time PM10 values. And the screenshot you attached is from the BTM station in Bangalore. Try to find that station’s website on CPCP website and see their real measurements.

**Comment by dolugen** [comment]
CPCB reports on 2 stations (Peenya and BWSSB) with PM2.5 data in Bangalore. 

After looking at a few station pages, I can tell that the adapter wasn't picking up fields with "PM 2.5", while taking "PM2.5". 

I don't know if any other stations are having this problem, but a change in the adapter should fix them all.

**Comment by dolugen** [comment]
A similar issue was raised: #237.

**Comment by jflasher** [comment]
Closed in https://github.com/openaq/openaq-fetch/pull/238
