### ISSUE TITLE
Handle EEA city names better, aka do we get rid of cities?

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#234]
Was looking at EEA data just now and noticed for [DE](https://openaq.org/#/countries/DE), they're actually just people's names! We're using the `network_name` property from EEA results which is inconsistent across sources and in this case, doesn't make sense for our purposes at all.

But I guess my real question is, do we scrap cities altogether (they've been confusing from the beginning), make sure everything has a lat/lon and use some sort of geocoder to match city to location? 

This would require some changes to website as we do break locations out by cities (which is obviously useful), but not sure we should be basing decision on required changes to display.

**Comment by olafveerman** [comment]
Yes, I support this idea. Practically speaking, `city` is a challenging concept and it will make writing adapters easier.

Beyond changes to the frontend, how does this impact the check for uniqueness? Are there locations within a country and source combination with the same name?

**Comment by olafveerman** [comment]
This is sort of handled by the new EEA Direct adapter. I think we can close this.
