### ISSUE TITLE
Change location for AirNow FTP

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#239]
Looks like AirNow FTP location is changing and we'll need to move to use new source. Not sure of timing but probably better to do sooner rather than later.

![image](https://cloud.githubusercontent.com/assets/848934/22559896/9bcd6650-e940-11e6-8c22-caffa4998f81.png)

**Comment by sourabhtk37** [comment]
https://github.com/openaq/openaq-fetch/blob/b44ab4ce9f58e944b39ed322a67fbee07f14b6b1/sources/us.json#L3

This need to be changed right?

**Comment by jflasher** [comment]
Yep, still needs to be done.

**Comment by jflasher** [comment]
Just a note here, I just noticed the protocol changes from ftp to http, which would be a problem. However, looking at what's on `https://files.airnowtech.org`, it's not the same data as we're currently using. Going to reach out to the email address to get more info.

**Comment by jflasher** [comment]
The files we're looking for should now be at http://files.airnowtech.org/

**Comment by jflasher** [comment]
Done with https://github.com/openaq/openaq-fetch/pull/526
