### ISSUE TITLE
Andalucia data

### ISSUE THREAD

**Issue by maelle** [openaq/openaq-fetch#246]
@Pakillo just told me about https://github.com/SevillaR/aire but it's written in R.

**Comment by jflasher** [comment]
It does point to http://www.juntadeandalucia.es/medioambiente/site/portalweb/menuitem.7e1cf46ddf59bb227a9ebe205510e1ca/?vgnextoid=7e612e07c3dc4010VgnVCM1000000624e50aRCRD&vgnextchannel=3b43de552afae310VgnVCM2000000624e50aRCRD, but I can't seem to find the underlying data.

**Comment by Pakillo** [comment]
Hi, 

All data are structured as daily reports. To see the data you need to (manually) select the province, date, and type of report (quantitative) and then you get HTML with data tables, like for example http://www.juntadeandalucia.es/medioambiente/atmosfera/informes_siva/feb17/nal170209.htm

**Comment by jflasher** [comment]
Thanks @Pakillo! The URL format seems easy to break down. It's got the month + year and then a unique station code and date. So we should programmatically be able to build that URL for all the stations and skip the click the menu items part.

And a couple of quick questions.

1. Do you know if there are coordinates for the stations provided anywhere?
2. Do you know what the **PART** measurements are? I'm guess they're pm25 or pm10, but not sure which one.
3. Just to confirm this isn't in the EEA data? cc/ @masalmon

**Comment by masalmon** [comment]
@jflasher I had wondered this and when looking at the grey points on OpenAQ map the South of Spain doesn't have any point at all so I don't think it was included in the EEA data?

**Comment by jflasher** [comment]
Thanks @masalmon. And hopefully those points won't be grey for much longer!

**Comment by masalmon** [comment]
Good thing Andalucia is one of the rare Spain regions I know where to place on a map :grin:

**Comment by Pakillo** [comment]
Hi,

Glad you'll be able to integrate these into OpenAQ :) Note they are **raw** data, not validated, as captured by measuring stations. The Andalusian government supposedly passes some checks/quality control on them later. But I haven't been able to find the validated anywhere (which doesn't mean they wouldn't give them if we asked! But that's not automatic of course).

Note also that daily reports, and hence URLs, are by **province**, not station (e.g. al for Almeria, se for Sevilla, etc). Hence the same URL contains data for all the stations in that province (as separate HTML tables).

To your questions:

1. Station coordinates: there is a KML [here](http://www.juntadeandalucia.es/medioambiente/site/portalweb/menuitem.7e1cf46ddf59bb227a9ebe205510e1ca/?vgnextoid=de4b20ac2a01d310VgnVCM2000000624e50aRCRD&vgnextchannel=9638282747fcc310VgnVCM2000000624e50aRCRD&lr=lang_es). And also a pdf table with UTM coordinates [here](http://www.juntadeandalucia.es/medioambiente/portal_web/web/temas_ambientales/atmosfera/calidad_aire/RVCCAA_2015.pdf).

2. PART: I don't know really. Most stations measure only PM10, but others also PM2.5, and I haven't seen those distinguished in the data tables. [Here](http://www.juntadeandalucia.es/medioambiente/portal_web/web/temas_ambientales/atmosfera/calidad_aire/RVCCAA_2015.pdf) you have a table with the measurements taken at each station, in case it helps.

Hope this helps!

Thanks

**Comment by masalmon** [comment]
@jflasher if it helps this week-end I can try extracting the table from the pdf with https://github.com/ropensci/tabulizer

**Comment by Pakillo** [comment]
Thanks. We already extracted the station coordinates, see CSV here: https://github.com/SevillaR/aire/blob/master/inst/station-info/station_info.csv.
And there's also an RData object with station coordinates in geographical (rather than UTM) coordinates [here](https://github.com/SevillaR/aire/tree/master/data). Prepared with [this script](https://github.com/SevillaR/aire/blob/master/inst/station-info/preparing_station_info.R). Hope it helps

**Comment by RocketD0g** [comment]
Recap for dev folks: 

1. This is the main site: http://www.juntadeandalucia.es/medioambiente

2. To go to a real-time data source, go to: http://www.juntadeandalucia.es/medioambiente/site/portalweb/menuitem.7e1cf46ddf59bb227a9ebe205510e1ca/?vgnextoid=7e612e07c3dc4010VgnVCM1000000624e50aRCRD&vgnextchannel=3b43de552afae310VgnVCM2000000624e50aRCRD

3. Select one of the 8 locations and the current date. Be sure to pick "Cuantitativo" 
For example: http://www.juntadeandalucia.es/medioambiente/atmosfera/informes_siva/jun17/nal170625.htm

* Data (except 'PART') w/ timestamps and units (ALL in ug/m^3):http://www.juntadeandalucia.es/medioambiente/atmosfera/informes_siva/feb17/nal170209.htm 

Note: I'm assuming "Part" is total suspended particulates, based on the page's language. We can ingest the SO2, NO2, CO, and O3. If anyone finds out differently, say so.

* Coordinates: https://github.com/SevillaR/aire/blob/master/inst/station-info/station_info.csv

* Source: Network of Monitoring and Control of Air Pollution in Andalusia

Question for @jflasher - Data appears to report every 10 minutes. Is this a problem?

**Comment by maxgrossman** [comment]
Hi @RocketD0g, @Pakillio, @maelle,  and @jflasher.

Thanks for the above discussion. All very helpful.

Anyhow I noticed that the daily tables are updated once a day. That generates a scenario where this morning I was only able to access yesterdays table and just now when I tried again today's records were available. 

That said, as I build this adapter I wanted to know how we wanted to report the data. We could either:

1) report data at the time closest to the adapter fetch time, but 24 hours previous. So if we are fetching data at noon today, grab the data for the same time, but 24 hours ago.

2) Report the currently available data table in total, not worrying that we are recording the same data over and over.

Regardless of the desired method, I'll have to add a bit of logic to try endpoints for both today and yesterday. Or, I'll have to know when they update the page and use that knowledge to build the correct request.

I also wanted to point out that it appears that on the [real-time data source](http://www.juntadeandalucia.es/medioambiente/site/portalweb/menuitem.7e1cf46ddf59bb227a9ebe205510e1ca/?vgnextoid=7e612e07c3dc4010VgnVCM1000000624e50aRCRD&vgnextchannel=3b43de552afae310VgnVCM2000000624e50aRCRD) page there is mention of CO and Ozone being 'movil', or mobile sources. 

Further discussion in footnote (4) under the table in section `Rango cuantitativo` declares that the calculation for Ozone uses, roughly translated, "eight-hour moving averages".

I should note that these are in discussion about the calculation of an air quality index and not the raw data itself. Though, I would presume that this 'movil' business also applies to the raw data we are interested in. 

Thanks - Max

**Comment by jflasher** [comment]
Hey @maxgrossman, yeah, I think we're trying to avoid the mobile stations for now. Two other points I wanted to bring up as I read over this.

1. The datetime stored with each individual measurement is the datetime at which it was made, which should be provided by the source somehow. It's not the time that the fetch process ran to check the data, those are independent things. We don't store the time that a measurement was recorded by our system anywhere. If a timestamp isn't available on the source page, we can't use the source. I don't believe we should be inferring it from when fetch is running.

2. There is a unique constraint on the database on `location-city-parameter-date` which means that no two measurements with that combination can be saved. So if the adapter provides data for the last two days, only the "new" data will be saved. There is some overhead on the system to try and write data that is not ultimately saved, but it's not a huge deal. If you can get data for the 6 hours or so, that'd be best, but if it needs to be the last two days, that's probably not a problem either since there isn't a ton of data here (I don't think).

**Comment by maxgrossman** [comment]
Hi @jflasher - thanks for the feedback. 

Reading your comments, I would think I should move forward parsing and returning the most up to date data provided by the site in its _entirety_, excluding the mobile aq sources.

And to make it known now as I'm developing, I'm using [tryEach](https://caolan.github.io/async/docs.html#tryEach) to deal with the complication of yesterday's v. today's data being available. So, the adapter tries for today's data, and if unsuccessful falls back to get yesterday's. Then of course outside the scope of those requests, if nothing is returned, that's handled.

Thanks again.

**Comment by dolugen** [comment]
The page with the query form contains a list of pollutants, including PM10. PART = PM10?
