### ISSUE TITLE
Missing coordinates and duplicated locations in India 

### ISSUE THREAD

**Issue by nishadhka** [openaq/openaq-fetch#248]
The table below shows the locations missing with coordinates and possibly duplicated with location name typos. This is from https://api.openaq.org/v1/locations?country=IN

| S.NO | Location Name                                      | City          |
|------|------------------------------------------------|---------------|
| 1    | AP Tirumala                                    | Chittoor      |
| 2    | Civil Lines, Nagpur - MPCB                     | Nagpur        |
| 3    | Durgapur City Center, Barddhaman - WBSPCB      | Barddhaman    |
| 4    | East Arjun Nagar                               | Delhi         |
| 5    | East Arjun Nagar-Delhi CPCB                    | Delhi         |
| 6    | Gangapur Road Nashik-MPCB                      | Nashik        |
| 7    | GVM Corporation                                | Visakhapatnam |
| 8    | GVMC Ram Nagar                                 | Visakhapatnam |
| 9    | GVMC Ram Nagar-APPCB                           | Visakhapatnam |
| 10   | Howrah - WBSPCB                                | Howrah        |
| 11   | IDA Pashamylaram,Hyderabad                     | Hyderabad     |
| 12   | IDA Pashamylaram, Hyderabad                    | Hyderabad     |
| 13   | KTHM College, Gangapur Road, Nashik-MPCB       | Nashik        |
| 14   | KTHM College Nashik-MPCB                       | Nashik        |
| 15   | KTHM College, Nashik - MPCB                    | Nashik        |
| 16   | Maninagar                                      | Ahmedabad     |
| 17   | MIDC Khutala,Chandrapur - MPCB                 | Chandrapur    |
| 18   | More Chowk-Waluj, Aurangabad - MPCB            | Aurangabad    |
| 19   | Opp. GPO Civil Lines-Nagpur MPCB               | Nagpur        |
| 20   | Opposite GPO Civil Lines - Nagpur MPCB         | Nagpur        |
| 21   | Opposite GPO Civil Lines Nagpur -MPCB          | Nagpur        |
| 22   | Opposite GPO Civil Lines-Nagpur MPCB           | Nagpur        |
| 23   | Pimleshwar Mandir - Dombivali - MPCB           | Thane         |
| 24   | Pimleshwar Mandir, Dombivali - MPCB            | Thane         |
| 25   | Pimpleshwar Mandir, Dombivali - MPCB           | Thane         |
| 26   | Sidhu Kanhu Indoor Stadium,Barddhaman - WBSPCB | Barddhaman    |
| 27   | Sidhu Kanhu Indoor Stadium, Durgapur - WBSPCB  | Barddhaman    |
| 28   | Siri Fort                                      | Delhi         |
| 29   | Tirumala                                       | Tirupati      |
| 30   | Tirumala-APPCB                                 | Tirupati      |
| 31   | TSPCBPashamylaram                              | Hyderabad     |
| 32   | Visakhapatnam                                  | Visakhapatnam |

**Comment by jflasher** [comment]
Thanks for collecting these @nishadhka. I wonder if the coordinates are available in the system and we're not catching them somehow? I think the name errors we can try and fix up occasionally by renaming in the database. We could try and catch them in the adapter, but I'm afraid the adapters will just become a mess of trying to catch other people's typos retroactively. Anyone else have any thoughts around that?

**Comment by dolugen** [comment]
My guess is that the source maintainer keeps changing the names! I can't think of a better way than occasional fixes in DB at the moment.

**Comment by dolugen** [comment]
Almost wanna propose a label called "data-discrepancy" or "data-diversion", as this kind of issue is becoming an regular occurrence.

**Comment by nishadhka** [comment]
Will dictionary replacement works? but that dictionary has to be so dynamic! 
There can be unique coding for stations (integer+string) that goes from countries, cities to station level. Currently merging and filtering have to be carried out on location name strings, that can get tampered easily.

**Comment by jflasher** [comment]
Given each device a unique ID would be an amazing thing. There are probably some IoT focused projects that are already thinking over some of those things. It would be such a help for what we're doing, but don't know that this project would be the right place to do that. Seems like a very hard thing to tackle given shifting input data.

**Comment by nishadhka** [comment]
In that case, I would lobby! for applying Sensor Observation Service ([SOS](https://en.wikipedia.org/wiki/Sensor_Observation_Service)) based standardization of openAQ data. It has Uniform Resource Name (URN) based identification of monitoring station and other thinks for enhancing interoperability. Sensor Observation Service(SOS), part of Sensor Web Enablement standard [SWE](http://www.opengeospatial.org/ogc/markets-technologies/swe) has [Java](http://52north.org/communities/sensorweb/sos/) and [Python](http://istsos.org/) based implementation. Python based implementation I worked with is easy to apply. It has capability even to address travelling monitoring stations and can able to address shifting input data.

...ahem ahem... application of SOS was part of my PhD study,

**Comment by jflasher** [comment]
@nishadhka that's very interesting, hadn't heard of that project previously! Can you actually open it as a separate issue on https://github.com/openaq/openaq-api since it seems more in line there? Going to close this issue here as I don't think there's any immediate action.
