### ISSUE TITLE
Use new averagingPeriod style across all sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#25]
Originaly @jflasher 's issue.

**Comment by abarciauskas-bgse** [comment]
From what I can tell there is no longer an "averagingPeriod" in the sources response schema, looking at https://u50g7n0cbj.execute-api.us-east-1.amazonaws.com/v2/sources?limit=100&page=1&offset=0&sort=asc&order_by=sourceName
