### ISSUE TITLE
About external geo data sources

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#251]
Some data sources don't easily provide their details. Station coordinates, city names, etc.

For example, Queensland (#249) doesn't have their coordinates, or city names in their feed. Coordinates are taken from a separate resource and hard coded in the adapter. For city names, if you don't want to manually browse a map, you'll have to turn to external data sources, like [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/start).

The general idea is that there could be some kind of integration with external geodata API that helps with the fetch process. If the source is open and reliable, we don't even need to use it in fetch, but integrate into the OpenAQ API itself.

This is an issue for discussing on the idea, so feel free to comment on it.

**Comment by dolugen** [comment]
This looks interesting: https://github.com/openaddresses/openaddresses

**Comment by dolugen** [comment]
Check this out: http://www.geonames.org/export/client-libraries.html

**Comment by dolugen** [comment]
I think this relates nicely to #234.

**Comment by dolugen** [comment]
I'm going to make two examples about picking `city` from addresses. These are reverse query results from OpenStreetMap's Nominatim, via `geopy`. The querying process is omitted here.

**Address:**
Howard Smith Drive, Lytton, Bulwer Island, QLD, 4178, Australia

**Raw:**
```
{u'address': {u'country': u'Australia',
              u'country_code': u'au',
              u'hamlet': u'Bulwer Island',
              u'postcode': u'4178',
              u'road': u'Howard Smith Drive',
              u'state': u'QLD',
              u'suburb': u'Lytton'},
 u'boundingbox': [u'-27.4037086',
                  u'-27.4026371',
                  u'153.1554734',
                  u'153.1628682'],
 u'display_name': u'Howard Smith Drive, Lytton, Bulwer Island, QLD, 4178, Australia',
 u'lat': u'-27.40348',
 u'licence': u'Data \xa9 OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright',
 u'lon': u'153.1591265',
 u'osm_id': u'30977997',
 u'osm_type': u'way',
 u'place_id': u'72222960'}
```
In this case, I could pick `Lytton` suburb as `city`.

**Address:**
Gallo, Potsdamer Platz, Tiergarten, Mitte, Berlin, 10785, Deutschland

**Raw result:**
```
{u'address': {u'bakery': u'Gallo',
              u'city_district': u'Mitte',
              u'country': u'Deutschland',
              u'country_code': u'de',
              u'postcode': u'10785',
              u'road': u'Potsdamer Platz',
              u'state': u'Berlin',
              u'suburb': u'Tiergarten'},
 u'boundingbox': [u'52.5095543', u'52.5096533', u'13.3762472', u'13.3763307'],
 u'display_name': u'Gallo, Potsdamer Platz, Tiergarten, Mitte, Berlin, 10785, Deutschland',
 u'lat': u'52.5095858',
 u'licence': u'Data \xa9 OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright',
 u'lon': u'13.376284871687',
 u'osm_id': u'464904422',
 u'osm_type': u'way',
 u'place_id': u'202676283'}
```
`Berlin` is obviously the `city` here, because we know it. But it's a `state` in the system.

With the current structure, where there's no `city` given from source, we could do reverse queries like these, but we'd have to determine which name to put in the `city` field. We probably could make queries for each country and see how it differs. Still, it feels like our addressing system needs some improvement.

**Comment by jflasher** [comment]
Thanks for looking into this! My gut instinct is to drop the city field altogether and maybe make coordinates mandatory. If someone searches for a city via the API, then we could do a geocode and do a coordinates search.  

I'm a bit worried about getting non-exact coordinates from something like OSM on fetch. It'd be getting us away from only storing source information when we do fetches.

**Comment by abarciauskas-bgse** [comment]
Believe from @sruti  coordinates are now mandatory so closing as obsolete
