### ISSUE TITLE
Create migration for new coordinates index

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#270]
We now have an index of 

`create index concurrently measurements_location_coordinates_not_null_index on measurements (location) where coordinates is not null;`

on the production database. We need to create a migration for it similar to https://github.com/openaq/openaq-fetch/blob/develop/migrations/20161116191003_indexes.js

**Comment by abarciauskas-bgse** [comment]
I believe the production database has recently been upgraded to support the low-cost sensor platform so closing this as obsolete.

@sruti @jflasher please correct me if I'm wrong.
