### ISSUE TITLE
Tuzla, Bosnia AQ data

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#276]
We received a request while in Tuzla, Bosnia to add this data source:

http://monitoringzrakatk.info/bkc-today.html

If someone is interested in writing an adapter for this source and would like to also connect to the individual who recommended the source, let me know and I will connect you by email.

**Comment by dolugen** [comment]
Can I take this?

I'm not sure what this means:
`*** Nisu propisane satne granične vrijednosti`
Google translated: `*** not required hourly limit values`

**Comment by RocketD0g** [comment]
That would be awesome, @dolugen! Folks in Tuzla who are currently recording these data by hand will be very excited about this.

For: 
` *** Nisu propisane satne granične vrijednosti
Google translated: *** not required hourly limit values `

I'm double checking with Bosnian colleagues, but I'm pretty sure it just means that those pollutants don't have official hourly limits (as opposed to SO2 and NO2 hourly, listed below it). I'm double checking with Bosnian colleagues.

**Comment by RocketD0g** [comment]
Another community member confirms the above comment is a correct interpretation of that translation, @dolugen.

**Comment by dolugen** [comment]
One of the active stations: `Mjerna stanica Mobilna: Gradačac`. We're not tracking mobile stations, right?

**Comment by RocketD0g** [comment]
Good q - that's correct, we don't track mobile stations, so we should not include this one. I was wondering if it was truly a fixed location (sometimes places are labelled 'mobile', but are actually fixed), but I also see there are no coordinates for this station so best to not include.
