### ISSUE TITLE
Station outside Delhi. Rohtak

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq-fetch#277]
http://www.cpcb.gov.in/CAAQM/frmCurrentDataNew.aspx?StationName=Rohtak&StateId=9&CityId=360

This is not in the archive yet.

Thanks,
Sarath

**Comment by jflasher** [comment]
Looks like we do have this at https://openaq.org/#/location/MD%20University%2C%20Rohtak%20-%20HSPCB

Same place?

**Comment by urbanemissions** [comment]
my apologies; this is correct.
