### ISSUE TITLE
Update Norway adapter to use toTime instead of fromTime

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#278]
https://github.com/openaq/openaq-fetch/blob/develop/adapters/norway.js#L61

Related to https://github.com/openaq/openaq-api/issues/313

**Comment by sourabhtk37** [comment]
Where is this source data?
https://github.com/openaq/openaq-fetch/blob/develop/adapters/norway.js#L57

**Comment by jflasher** [comment]
Can see it at https://github.com/openaq/openaq-fetch/blob/develop/sources/no.json#L3
