### ISSUE TITLE
Must change data feed for AirNow Data (NOTE: This excludes data from US dip facilities in China)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#279]
Two members of our community (one in India, one in Kosovo) brought to our attention that the RSS data feeds for US Embassies and Consulates (e.g. [here's Delhi's](http://stateair.net/dos/RSS/NewDelhi/NewDelhi-PM2.5.xml)) that report PM2.5 concentration were significantly differing from the historical hourly average PM2.5 concentrations in files posted later on the [AirNow site](airnow.gov).

It turns out that the 'conc' field in the RSS Feed is what I'd call for lack of a better term a "NowCast Virtual Concentration," derived from [this formula (page 6)](https://www3.epa.gov/airnow/ani/pm25_aqi_reporting_nowcast_overview.pdf). It is paired with the 'AQI' in each field. 

We have confirmed this with folks at the EPA, who have been very responsive to our inquiry.
They will work on updating the RSS Feed in the future to include the physical concentration, but for now have pointed us to using this JSON feed, which aggregates *physical, hourly* PM2.5 concentration data (again, minus US dip facilities in China - these data should be fine):

https://www.airnowtech.org/dos/AllPosts24Hour.json

Please also see this related issue: #280

**Comment by RocketD0g** [comment]
Great thing is, EPA just let us know that they actually just changed the <conc> field to indicate the true physical concentration. This is great, and means we don't need to change the code in our system at all. 

For those interested, the "NowCast Virtual Concentration" above is now called <NowCastConc> in the xml file. 

Hats off to EPA for the fast change and to those of you who let us know about the problem!

(Issue #280 still must be dealt with)

**Comment by jflasher** [comment]
💃
