### ISSUE TITLE
Dakar Data - May not be available in real-time or currently at all yet

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#290]
From a community member:

AQ monitoring in Dakar:
http://www.air-dakar.org/stations/station-de-bel-air.html

"…looks like they were producing reports monthly in addition to daily reporting, but they haven’t produced the reports in about a year"

***
These data are not yet readily available in a form for us to ingest, but if anyone is interested in digging into this some more, let us know.

**Comment by abarciauskas-bgse** [comment]
Unfortunately, it doesn't look like this website air-dakar.org is maintained any longer, so closing as can't do
