### ISSUE TITLE
New Data Source - Bath

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#300]
Source:
https://data.bathhacked.org/Environment/-Live-Air-Quality-Sensor-Data/hqr9-djir

Have not explored whether all pieces of data format (e.g. coordinates, etc) are available yet.
https://github.com/openaq/openaq-data-format

**Comment by majesticio** [comment]
Thanks for finding this potential data source. The provider appears to have gone stale, last being updated in 2019.
