### ISSUE TITLE
Emilia-Romagna (Italy) data

### ISSUE THREAD

**Issue by jobonaf** [openaq/openaq-fetch#302]
near-real-time data:
https://dati.arpae.it/dataset/qualita-dell-aria-rete-di-monitoraggio/resource/a1c46cfe-46e5-44b4-9231-7d9260a38e68

to decode the parameters codes:
https://dati.arpae.it/dataset/qualita-dell-aria-rete-di-monitoraggio/resource/6fb8af6d-a3cc-4cf7-b098-ed95c5744cee?inner_span=True

stations (coordinates are EPSG:25832):
https://dati.arpae.it/dataset/qualita-dell-aria-rete-di-monitoraggio/resource/6b1c73c6-2fa9-40b2-854a-d3f822d1451a?inner_span=True

**Comment by RocketD0g** [comment]
Thanks, @jobonaf! To confirm, this appears to be Italian government-collected data. Is that correct?

**Comment by jobonaf** [comment]
Yes. In Italy air monitoring is decentralized, managed by the regional environment protection agencies. The regional EPA of Emilia-Romagna is **arpae**

**Comment by jobonaf** [comment]
as far as I know, in the next months three other regions in Italy are expected to publish their air quality data in open data portals: Lombardy, Sardinia and the Autonomous Province of Bolzano/Bozen

**Comment by RocketD0g** [comment]
Hi again @jobonaf - Quick question, I couldn't get this link to work to decode the parameters:

> to decode the parameters codes:
> https://dati.arpae.it/dataset/qualita-dell-aria-rete-di-monitoraggio/resource/6fb8af6d-a3cc-4cf7-b098-ed95c5744cee?inner_span=True

Do you know where else we might find this info? Thanks again.

**Comment by jobonaf** [comment]
Hi @RocketD0g 
Try this:
https://dati.arpae.it/dataset/qualita-dell-aria-rete-di-monitoraggio/resource/65faaf03-f2fc-4f8a-b9cb-c771907644ce

**Comment by RocketD0g** [comment]
Thanks! Now labelling `ready for dev`.

**Comment by dolugen** [comment]
How to search the CKAN API
======================

The search URL is: `https://dati.arpae.it/api/action/datastore_search?resource_id={uuid}`

For example, the NRT resource is at: https://dati.arpae.it/api/action/datastore_search?resource_id=a1c46cfe-46e5-44b4-9231-7d9260a38e68

How to search on CKAN? http://docs.ckan.org/en/latest/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search

An example query for a specific station's specific parameter data sorted by date, in descending order: https://dati.arpae.it/api/action/datastore_search?resource_id=a1c46cfe-46e5-44b4-9231-7d9260a38e68&limit=100&sort=reftime%20desc&filters={%22station_id%22:%222000219%22,%20%22variable_id%22:%20%227%22}

Use the SQL!
-----------------

Well, we'd like to read the data from the last 24 hours, and that isn't possible with the Datastore Search method. But we can try that with the Datastore Search SQL method. Let's write the above query in SQL with the date ranges:

```
https://dati.arpae.it/api/action/datastore_search_sql?sql=SELECT * from "a1c46cfe-46e5-44b4-9231-7d9260a38e68" WHERE station_id=2000219 AND variable_id=7 AND reftime >= '2017-09-28T00:00:00' AND reftime <= '2017-09-29T00:00:00' ORDER BY reftime DESC LIMIT 100
```

Looks good. But I should query for all stations with all variables, and I'm not getting any pagination or metadata to derive pages from (unlike the normal query method), I should probably read ALL of them in one go if possible:

```
https://dati.arpae.it/api/action/datastore_search_sql?sql=SELECT * from "a1c46cfe-46e5-44b4-9231-7d9260a38e68" WHERE reftime >= '2017-09-28T00:00:00' AND reftime <= '2017-09-29T00:00:00' ORDER BY reftime DESC
```

Yes, it works!

**Comment by dolugen** [comment]
Actually, simple search was enough with the date filter. Thanks to the CKAN API, it took fewer lines compared to others (Arpalazio!).

**Comment by dolugen** [comment]
> Actually, simple search was enough with the date filter.

You were wrong.

**Comment by dolugen** [comment]
> Data updated daily on the issue of the bulletin. WARNING: the date in ISO format refers to solar time Italy (UTC +1.00)

A note from the resource page (Google translated). I'm assuming Italy's observing DST right now, so +02:00?

**Comment by jflasher** [comment]
I saw that too and assumed it was wrong or just not updated.

**Comment by jobonaf** [comment]
According to Italian and European laws, air quality data must refer to the local time **without** Daylight Saving Time. Therefore, for Italy it is always UTC +1.00

**Comment by dolugen** [comment]
Good to know! Thanks for clearing that out.
