### ISSUE TITLE
SO2 data from Delhi stations

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq-fetch#305]
https://api.openaq.org/v1/measurements?city=Delhi&parameter=so2&date_from=2017-06-01&date_to=2017-06-06&format=csv

No data shows for Delhi; same with Faridabad

The main site show data
http://www.dpccairdata.com/dpccairdata/display/rkPuramView15MinData.php
http://www.cpcb.gov.in/CAAQM/frmCurrentDataNew.aspx?StationName=Sector16A%20Faridabad&StateId=9&CityId=365

**Comment by dolugen** [comment]
Thanks for submitting this, @urbanemissions!

I see that this is a similar issue with #233 and #237. I gather the CPCB data is collected from various secondary sources, and it looks like they have differing spellings for SO2: "Sulphur [...]" and "Sulfur [...]". The "Sulfur" spelling and related data was being ignored.

I will push a fix for this shortly.
