### ISSUE TITLE
New station - NOIDA (India)

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq-fetch#306]
http://www.cpcb.gov.in/CAAQM/frmCurrentDataNew.aspx?StationName=Sector-125&StateId=28&CityId=555

**Comment by dolugen** [comment]
Hi, @urbanemissions!

The CPCB adapter expects the station to have related details, such as city name and coordinates. The NOIDA station currently have no such information on its details page, thus the measurements are considered invalid and not added. I'd hope that the website admin fill in their information, so the station data would be added to OpenAQ automatically.
