### ISSUE TITLE
Remaining EEA data sources (I think)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#309]
Here's the list of remaining EEA sources to pull (I believe). I'm closing any other issues that overlap with this.

* Andorra - AD
* Lithuania - LT
* Luxembourg - LU
* Latvia - LV
* Malta - MT
* Portugal - PT
* Serbia - RS
* Slovenia - SI
* Slovakia - SK

cc: @jflasher

**Comment by olafveerman** [comment]
A slightly different list will be added through: https://github.com/openaq/openaq-fetch/pull/375

- ch - switzerland
- lt - lithuania
- lu - luxemburg
- lv - latvia
- mt - malta
- pt - portugal
- rs - serbia
- sk - slovakia

**Comment by espenairmine** [comment]
Hi @sruti  - is this to be closed?

**Comment by sruti** [comment]
Yes, closing in favor of the more recent issue #677
