### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#313]
From build checks in #312.

The following line with `docker-compose` command fails:

```
$ touch local.env && docker-compose --project openaq run fetch npm test
```

It may be related to them upping the docker version in the OS image:

```diff
-    "docker-engine": "1.12.3-0~trusty",
+    "docker-ce": "17.03.1~ce-0~ubuntu-trusty",
```

Travis blog: [The new Ubuntu Trusty 14.04 images are now live!](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch)

**Comment by dolugen** [comment]
This fixed it:
```diff
-   --project
+   --project-name
```

I've pushed the fix along with the moment-timezone update, hope that's ok.

**Comment by jflasher** [comment]
Fixed in https://github.com/openaq/openaq-fetch/pull/312
