### ISSUE TITLE
Help dumping output of API to CSV

### ISSUE THREAD

**Issue by urbanemissions** [openaq/openaq-fetch#323]
API function is showing a file with data
https://api.openaq.org/v1/measurements?city=Delhi&parameter=pm25&date_from=2017-07-12&date_to=2017-07-13&format=csv
However, using the curl function in the program, running every 30 minutes, is not getting any data

curl https://api.openaq.org/v1/measurements?city=Delhi&parameter=pm25&date_from=2017-07-12&date_to=2017-07-13&format=csv' > temp.csv

Do you have any suggestions?

With regards,
Sarath

**Comment by jflasher** [comment]
Is this still an issue? Seems to work fine for me, could've been an intermittent issue?

I'll also note that the command as written above has a trailing `'` which could be causing an issue.

**Comment by dolugen** [comment]
As @jflasher noted, could be the unclosed quote. This works for me:

```
curl "https://api.openaq.org/v1/measurements?city=Delhi&parameter=pm25&date_from=2017-07-12&date_to=2017-07-13&format=csv" > temp.csv
```

**Comment by urbanemissions** [comment]
Good morning. We can close this. I have been using the API for more than 6 months. July 10-11-12, intermittently, I suppose, the pulls were not responding at well, even though the csv download from the web were working okay.

the unclosed quote in the comment was a typo.

The pull functions are operational now.
