### ISSUE TITLE
Data from Mongolian provincial AQ stations

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#332]
AQ data from provincial capitals, reported twice a day: http://tsag-agaar.gov.mn/observation/environment-monitoring/air-data

Country wide coverage started in 2013/2014 according to [this article](http://tsag-agaar.gov.mn/observation/environment-monitoring/%D0%B0%D0%B3%D0%B0%D0%B0%D1%80%D1%8B%D0%BD-%D1%87%D0%B0%D0%BD%D0%B0%D1%80%D1%8B%D0%BD-%D1%82%D0%BB%D0%B2-%D0%B1%D0%B0%D0%B9%D0%B4%D0%BB%D1%8B%D0%BD-%D0%B6%D0%B8%D0%BB%D0%B8%D0%B9%D0%BD-%D0%BC%D1%8D%D0%B4%D1%8D%D1%8D-2014-%D0%BE%D0%BD).

It says that there are a total of 35 stations, which 11 of them are in UB. We have an adapter for the UB stations (`Agaar.mn`), so we'd get 24 new stations, one for each province and a few more. Edit: There are some overlap for UB stations from Agaar.mn and this source.

The country stations report NO2, SO2, and PM10.

![mn-aq-network](https://user-images.githubusercontent.com/194381/28487941-a9db52c8-6ed0-11e7-8293-92a662b90015.png)

(There's also a dedicated AQDB website, but looks like it is rarely used: http://eic.mn/airpollution/airpollution.php)

**Comment by dolugen** [comment]
I didn't know about this country-wide coverage until last May, and talked with @RocketD0g about it. Only now I thought of submitting it as a source here.

I just wonder why they're not integrated into agaar.mn already.

**Comment by dolugen** [comment]
Reaching out to a contact to get the coordinates info on the stations. Should get something next week.

**Comment by dolugen** [comment]
Finally got my hands on the contacts, will update the adapter soon.

**Comment by dolugen** [comment]
Got locations of the most of the stations: [uploaded here](https://github.com/dolugen/mn-aq-stations/blob/master/mn-aq-stations.csv). A couple of stations are missing locations, and the coordinates need to be converted to decimal degrees.

**Comment by dolugen** [comment]
OK, got all of the coordinates ready. Now just need to let the adapter know about them.

**Comment by dolugen** [comment]
`Бор-Өндөр` is probably `Өндөрхаан` in this case. Checking with upstream.

**Comment by dolugen** [comment]
To keep the city name aligned with the existing data, I'm using "Ulaanbaatar" instead of "Улаанбаатар". Other cities all use Mongolian name, except Erdenet.

**Comment by jflasher** [comment]
@dolugen thanks for this, just getting to look at it now. I know you kept the UB stations that overlap with Agaar.mn, but I don't think we can do that. I think we need to try to avoid duplicates in the system as it'll throw off any future calculations of averages and such. What's the best way to try and keep this from happening in this case?

**Comment by dolugen** [comment]
Narrowing down by sourceName comes to mind, but we don't have that today. I could let it skip a couple of stations by name.

**Comment by jflasher** [comment]
I guess maybe skip the ones we know are included elsewhere? We do have a unique index on location, city, parameter, date but I'm not sure if those would be exactly the same between the two sources?

**Comment by dolugen** [comment]
There are two locations that come from both sources:

* "УБ-2" is "Baruun 4 zam"
* "УБ-8" is "Urgakh naran"

They are now skipped.

**Comment by jflasher** [comment]
👍 I'll take a look.
