### ISSUE TITLE
Improving aggregation performance

### ISSUE THREAD

**Issue by kamicut** [openaq/openaq-fetch#355]
Right now, aggregations take a very long time and happen in the database, requiring large memory compute instances. I've explored with @jflasher a solution to offload the work to other data processing mechanisms.

## Adding fetch data to S3
I've created a pull request (#354) that allows the fetch process to push each fetch's measurements to a CSV file on S3. This gives us two things:
1. Archiving the fetch data granularly and time stamping it.
2. Publishing fetch data to allow for any type of downstream analysis 
3. Offloading aggregations from the database to S3 aggregations 

## AWS Athena
Using AWS Athena on the CSV data, i've found that we can significantly reduce aggregation times to minutes. This is a possible improvement to (#182). 

## Backfilling
For openaq.org, if we start archiving the data to S3 right now, we need a mechanism to backfill the bucket with the historical data. Since the data is not timestamped, I think we would need to dump the DB to an s3 file and start the new fetch code from that checkpoint. There might be some manual process to delete duplicates here. Any ideas @jflasher ?

## Future enhancements
- Right now fetch adds data every 10 minutes, and a CSV file would be created every 10 minutes. One optimization could be to have a separate concurrent process that concatenates the fetch data downstream into "daily" files, to reduce the amount of files published.
- Instead (or alongside) of CSV, we could use a columnar format like Parquet or ORC which allows for more efficient downstream processing

**Comment by jflasher** [comment]
This has been deployed so closing this.
