### ISSUE TITLE
AirNow Data Source listed on Country Card for Mexico?

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#357]
Currently, all Mexican data comes from 91 locations from the US EPA AirNow source. These are clearly identified on each location card and hyperlinked, e.g.,

![screen shot 2017-08-03 at 12 35 52 pm](https://user-images.githubusercontent.com/13404290/28932674-5497fc2c-7848-11e7-9115-d1081022255a.png)

However, on the main country card, it says "0" source.

![screen shot 2017-08-03 at 12 34 41 pm](https://user-images.githubusercontent.com/13404290/28932692-66e20cba-7848-11e7-9e55-675505420160.png)

I assume this might be the case because the source does not come from Mexico? Is there a way to make this say '1' source? We have received some feedback that some individuals have thought we accessed this data in a non-public way, and wondering if this is, in part, why they thought this. 

At any rate, if this small tweak of '0' to '1' is easy to make, it'd be awesome to adjust it.

**Comment by dolugen** [comment]
Yeah, it's because the Airnow source doesn't have country data filled in. What do you think of making the source JSON support multiple countries? /cc @jflasher

**Comment by jflasher** [comment]
My initial inclination would be to continue how we're doing it with other sources. So basically, there'd be a mx.json, us.json and ca.json, all calling to the AirNow adapter. The adapter would somehow know to only grab/insert the data for that country. Would that actually fix the issue?

I feel like multiple countries in the us.json would be confusing down the line.

**Comment by dolugen** [comment]
If it's possible to fetch individual country data with AirNow adapter, I concur with you.
