### ISSUE TITLE
Station Locations of Historical Canadian data

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#414]
From a community member:

Canada's historic sampling sites based on NAPS archived data (e.g. http://maps-cartes.ec.gc.ca/rnspa-naps/data.aspx?lang=en).

The map layer shows all their available sites (hence those with missing data haven't been fully screened). 

https://spartan.carto.com/builder/ad83db50-0bf6-4886-a4b7-59ebadda7f16/embed

Clicking on a particular point leads to a link to a bare-bones page with static plots for that city and accompanying links to csv files (annual and monthly averages) for SO2, NOx, O3, and PM2.5.

**Comment by majesticio** [comment]
As the first url no longer resolves, and the second url's map points don't have coordinates and links lead to 'forbidden' pages I am closing this issue pending further information
