### ISSUE TITLE
Use S3 as authoritative source, store less in database

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#416]
After the recent work to have realtime data showing up on S3, we now have two running copies of the realtime data (~110 million records as of this ticket), one is in the postgres database, the other is in S3. **I propose that we drop the database to only storing data for 3 months and keep S3 as the long-term store of the data.** A few consequences and thoughts below.

- Dropping the database down to 3 months will decrease the amount of processing power needed for the database saving money as well as speeding up the API responses (which has been an issue lately). So decreased costs and improved performance. It should be about 40 million records for a rolling 3 month period, which seems high, but somewhere around there.

- This means the API could no longer provide data older than 3 months (or at least not without modifying it to pull from S3 somehow). I think this is fine as the majority of the API access is for the most recent data. See below for exception.

- Exception to below is the CSV downloads which is generally for older data and more of it. This could be accomplished by providing similar functionality pulling right from the S3 data.

- We'd need to figure out how we message aggregated data now. I think the best way to do this will be to have the `/measurements` endpoint just gets its data from the database like it does now and the aggregation endpoints pull from S3 as they do now. This means if someone does something like `/locations?location=foo` and sees a count, it'd be different than `/measurements?location=foo`. I don't think that's an issue as both are internally consistent and can be explained in docs.

In summary, no data would become unavailable, it's just that the older data would be available in a different mechanism. The API was never intended as a mechanism to download all the data anyways, we should have a different method for that. 

I'm interested in hearing any thoughts. Are there people that **need** access to older data via the API specifically (versus another mechanism)?

- [ ] Update documentation to lay out difference between `/measurements` and aggregated endpoints
- [ ] Update website to make it more obvious where the data is coming from and the historical timeliness
- [ ] Come up with some sort of tooling or demo to help people access the full historical data on S3 (using Athena or similar)
- [x] Make sure website doesn't pull from /measurements for total number (https://github.com/openaq/openaq.org/pull/237)

**Comment by RocketD0g** [comment]
From a cost and performance perspective, I think this would be fantastic. Interested to hear user perspectives, as well as thoughts on 3 months versus 1 month versus 5 months, etc.

**Comment by RocketD0g** [comment]
Will post any twitter/other media feedback about the potential change in here :)

![screen shot 2017-10-31 at 11 11 06 am](https://user-images.githubusercontent.com/13404290/32231552-4b309b88-be2c-11e7-8940-6a1b894f9d42.png)

**Comment by jflasher** [comment]
Based on feedback, going to move forward with this. We'll need to add some communication points to the docs and website to reflect this. Edited the initial ticket overview with some todos. 

Have a backup of the full database as of this comment writing that'll stay there in case it's needed. Starting to remove items slowly now to see what affect it has.

**Comment by AreteY** [comment]
For those interested in the historical/older data, please let us know if accessing from S3 is okay. Maybe one thing to add to our Community Wish List is something that allows a user to access the older data for a specific location (ie., something that returns the data over one index=location).

**Comment by jflasher** [comment]
I think this would be a great thing to have! We should still provide an easy way to get at this data and it could still be done through the API, just not via the database anymore.

**Comment by JHvdZ** [comment]
Can you please let me know how I can download the historical data (older than 3 months). I tried to find out how to get data from the S3 database, but wihtout success until now. My problem is that I use the datafiles for a data analysis assignment for a class with international students here at The Hague University of Applied Sciences and the students are working on it these weeks. 
Thanks in advance,
Hans van der Zwan.

**Comment by RocketD0g** [comment]
Hi @JHvdZ! Thanks for your q! I'm going to copy and paste some language that I _just_ updated on our FAQ [page](https://github.com/openaq/openaq-info/blob/master/FAQ.md#90days): 

> **14.5 Why can I only access data for the last 90 days? Where's the rest of the data?**
> 
> Second question first! Don't worry, the full archives data are still stored and available through the following mechanisms:
> 
> 
> - Go here for access to the data as it's added to our system: https://openaq-fetches.s3.amazonaws.com/index.html. This data is updated every 10 minutes when a new fetch runs. This source also contains all the information for each measurement.
> - Go here for access to a daily archive of the data: https://openaq-data.s3.amazonaws.com/index.html. This is an older data format and while it contains most of the information you'd be looking for, it does not contain all the fields for each measurement.
>
> We are working to provide additional, more accessible-friendly ways to access these older data. If you have ideas, share them with us (via: info@openaq.org, a [GitHub Issue](https://github.com/openaq), or discussion on our [Slack Channel](https://openaq-slackin.herokuapp.com/)).
> 
> So why can you only access the last 90 days through the API and download portal on the OpenAQ website?
> 
> It comes down to keeping costs down and maintaining API responsiveness. As the number of our data records grew upwards of 100 million, it posed a challenge to make all of that information available through an efficiently running API (which also powers the download portal on the site). It also costs us a chunk of change to support a big database, so like a lot of open data projects, we opted to store older data in a more cost effective method that lets our API run more reliably and our database be smaller.

Let us know if you have other questions/feedback! Thanks!

**Comment by JHvdZ** [comment]
Dear Christa,

Thanks a lot for your answer; the good news is that the data is stille available.
The not so good news for me is that it is ordere by day.
I am thinking about how, in an easy way, my students can collect the data for a city of there choice for a whole year.
If you have any suggestions I would be pleased; but even if that’s not the case, thanks very much for your reply.

Kind regards,
Hans van der Zwan
(The Hague, Netherlands)

**Comment by jflasher** [comment]
This has been running for some time now, so closing this issue.

I also wrote up a gist showing off how to use Athena to query all the data. We should look to include this somewhere more prominent.

https://gist.github.com/jflasher/573525aff9a5d8a966e5718272ceb25a
