### ISSUE TITLE
Hong Kong AQ data!

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#418]
Looks like station-level AQ data in physical units is available for Hong Kong here: 

http://www.aqhi.gov.hk/en/aqhi/past-24-hours-pollutant-concentration.html

Pollutants and units are defined, as well as include station names. 

Historical measurements are available through download here:
http://epic.epd.gov.hk/EPICDI/air/station/?lang=en

I'm not sure on coordinates, but may be able to be grabbed from the map?
http://epic.epd.gov.hk/EPICDI/air/station/?lang=en
Or from here: http://www.aqhi.gov.hk/en/monitoring-network/air-quality-monitoring-stations.html

Addresses of the stations also appear to be available here (Appendix B1):
http://www.aqhi.gov.hk/api_history/english/report/files/AQR2016e_final.pdf

If someone wants to build the adapter, we can create a list of the stations based on those station addresses.

**Comment by dolugen** [comment]
It would be nice to have the coordinates ready. Any way to find out what they are?

**Comment by RocketD0g** [comment]
Asking a colleague who mentioned this data/site.

**Comment by RocketD0g** [comment]
@dolugen - No update on this, but I'm going to see if a volunteer would be up for creating this list of coordinates given the info above.

**Comment by ymhuang0808** [comment]
According to the data portal in Hong Kong, the air quality data source is XML format. It would be better for parsing.

**Comment by ymhuang0808** [comment]
I'm working on the HK adapter to fetch the [measurements](https://data.gov.hk/en-data/dataset/hk-epd-airteam-past24hr-pc-of-individual-air-quality-monitoring-stations) from HK open data. And I need a few time to implement it.
