### ISSUE TITLE
Create a list of coordinates for Hong Kong Stations

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#422]
This issue helps address solve #418 

We need a volunteer to go through the stations  mentioned [here](http://www.aqhi.gov.hk/en/aqhi/past-24-hours-pollutant-concentration.html).

And manually determine the coordinates by reconciling those station names with the addresses listed [here](http://www.aqhi.gov.hk/en/monitoring-network/air-quality-monitoring-stations.html). 

Google maps (or a similar service) can be used to convert addresses to coordinates and they can be visually verified with the AQ site's map.

Other resources for this issue:
- http://epic.epd.gov.hk/EPICDI/air/station/?lang=en
- Addresses of the stations also appear to be available [here](http://www.aqhi.gov.hk/api_history/english/report/files/AQR2016e_final.pdf) (Appendix B1):

If you take up this issue, please say so, so there aren't multiple people working on this, duplicating each other's work.

**Comment by ymhuang0808** [comment]
Accroding to [the data portal in Hong Kong](https://data.gov.hk/en-data/dataset/hk-epd-airteam-past24hr-pc-of-individual-air-quality-monitoring-stations/resource/3964dffc-b095-47bb-a538-8a78a18c4bee), the data source is XML format. It would be better for parsing.

**Comment by ymhuang0808** [comment]
Sorry, I replied in wrong issue.

**Comment by ymhuang0808** [comment]
I would like to work on this issue. Does the list of coordinates should be generated automatically?

**Comment by dolugen** [comment]
> I would like to work on this issue.

That would be great! Thanks for stepping up!

> Does the list of coordinates should be generated automatically?

It depends on the source. For data sources that doesn't incorporate coordinates along with AQ data, we tend to compile the location and coordinates mapping from other sources, and keep it in the adapter file. So for the HK source you just linked, we'd have to prepare the locations list from somewhere else.

Let me know if you have any other questions!

**Comment by ymhuang0808** [comment]
I found there is a CSV file for air quality stations from [Hong Kong GeoInfo Map](http://www1.map.gov.hk/gih3/view/index.jsp). The CSV file is in "Map Tools" > "Data Download" > "Air Quality Monitoring Network of Hong Kong".

The file contains station names and coordinates in degrees minutes seconds format. I will process the CSV file by NodeJS.

**Comment by ymhuang0808** [comment]
I think the the stations list may looks like:

```
[
  {
    "name": "Eastern",
    "coordinates": {
      "longitude": 114.21944444444445,
      "latitude": 22.282777777777778
    }
  },
  {
    ..
  }
]
```

**Comment by ymhuang0808** [comment]
@dolugen I generated the coordinates of HK stations into [here](https://github.com/ymhuang0808/hk-air-quality-stations/tree/master/data).

**Comment by dolugen** [comment]
Thank you @ymhuang0808! That would help completing #418. Are you interested in making an adapter for HK?

**Comment by ymhuang0808** [comment]
Sure. I'm glad to implement an adapter for Hong Kong!

**Comment by dolugen** [comment]
Great. As you know, the HK adapter is at #418.
