### ISSUE TITLE
Slovakia country code saved as lowercase

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#427]
The country code is saved as "sk", but the API country code conversion library expects "SK", so no name is shown in the countries list. I'm reporting it here because I think the error is probably in the adapter.

**Comment by jflasher** [comment]
Yeah, we've got some lowercase 'sk' floating around in the data. It was changed back in https://github.com/openaq/openaq-fetch/commit/895940ab294ec849afa17e0d4b6a6da8bb2d7b88#diff-c1d323ef4e1e1f1d5d122427efc7c01d but is there in the S3 data which is what the aggregations run on, hence it sticks around. https://github.com/openaq/openaq-api/pull/367 should fix this visually, but we need to come up with a programatic way to apply updates to the data sitting on S3, will open an issue for that.
