### ISSUE TITLE
Ulaanbaatar - Data Source - US Embassy

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#43]
http://www.stateair.mn

They also have hourly historical data going back to October.

Think I might be able to do this with Kimono and will give it a shot. If not, will add 'help wanted' shortly.

**Comment by jflasher** [comment]
Does anyone know if agaar.mn is planning on pulling this in? Ideally, they'd handle it since we already get all the other MN data from there.

**Comment by RocketD0g** [comment]
Now addressed in #45
