### ISSUE TITLE
New data: Ilijaš, Bosnia (in Sarajevo Canton, should require only tweaks to existing adapter)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#433]
Community member shared: 

> There is new governmental automatic station in Sarajevo Canton, in town Ilijaš
> http://80.65.164.218/article/site-index

![screen shot 2017-12-22 at 2 00 43 pm](https://user-images.githubusercontent.com/13404290/34311044-88e6d178-e720-11e7-8537-7685e70d80b7.png)

We pull other Bosnian data from [here](http://www.fhmzbih.gov.ba/latinica/AKTUELNI/A-zrak.php).

And this site (Ilijaš) also appears on there. I presume this will be a modification of the existing Bosnian [adapter](https://github.com/openaq/openaq-fetch/blob/develop/adapters/fhmzbih.js).

**Comment by jflasher** [comment]
We actually get the data from http://www.fhmzbih.gov.ba/latinica/AKTUELNI/zrak2.php which does not have the Ilijaš data. If we can get it added there, it'll show up in the system (though we will need to add coordinates).

**Comment by majesticio** [comment]
I am closing this issue as all these sources have gone dark and we have newer Bosnia adapters.
