### ISSUE TITLE
Source from China National Environmental Monitoring Centre 

### ISSUE THREAD

**Issue by nickolasclarke** [openaq/openaq-fetch#453]
I've been working with @geoinsights and @jflasher to opensource and integrate https://github.com/geoinsights/ChinaAQIData/ into openAQ. This project pulls data from cnemc.cn's silverlight application and transforms it into xml as well as json. This will bring data from 1495+ stations covering all of China into the project. 

This project, as written, is a combination of python and shell scripts that pulls wcf binary xml, and converts it to XML and JSON. This relies on the https://github.com/ernw/python-wcfbin lib in order to to this. As such, this will not integrate easily as an adapter for openaq-fetch. 

However, I have found at least one node based lib that claims to do the same as python-wcfbin, https://github.com/tumick/wcf2xml. In order to incorporate this data properly, we would ideally want to port the geoinsights project to node, using this wcf2xml npm module, or try to reimplement ourselves. Until that time, it is my understanding that @jflasher will deploy the original ChinaAQIData project and then use the generic JS adapter to pull this data into openAQ. 

Thoughts on how to best port this project to node and/or PRs are welcome.

**Comment by nickolasclarke** [comment]
This should hopefully resolve #39

**Comment by jflasher** [comment]
@nickolasclarke and @geoinsights thanks for all the work so far! As @nickolasclarke said, I think a good first step will be to deploy the Python code as a standalone thing, have it write data to a private S3 bucket that `openaq-fetch` can access and then write a JS adapter as normal. Other option is to try and include the Python code in `openaq-fetch` and run via a Node shell execution, but that feels not great. 

I know there were some concerns with previous China data sources since they were coming from elsewhere, but given that this is open source code pulling from an official source, I think we're all good there, but happy to hear any other comments around that.

**Comment by RocketD0g** [comment]
This is fantastic; it will be unbelievable to have Chinese AQ data in the system. It's especially cool that the code is open-source and pulls directly from government sources. It will be good eventually to figure out how we should properly cite this, giving attribution to the open-source code and the originating government source.

**Comment by jflasher** [comment]
Just a note that we now have https://github.com/openaq/lambda-chinaaqidata and https://github.com/openaq/ChinaAQIData. It's running on a 30 minute interval and putting the latest data into a private S3 Bucket (`openaq-chinaaqidata`) that we can query via an adapter.

Thanks again to @geoinsights for all the work on the package and to @nickolasclarke for bringing it to our attention. We should hopefully be able to get this data in soon.

Note: We should figure out if this is going to duplicate any CN data we are already bringing in.

**Comment by nickolasclarke** [comment]
@jflasher I suspect all the adapters outside of the US consulates and the SPARTAN network will be dupes. Those from BJ, Anhui, etc.

**Comment by jflasher** [comment]
Cool yeah, in my branch I disabled all the Anhui adapters which I believe are the only live duplicate sources.


On February 21, 2018 at 3:56:52 AM, Nick Clarke (notifications@github.com) wrote:

@jflasher I suspect all the adapters outside of the US consulates and the SPARTAN network will be dupes. Those from BJ, Anhui, etc.

**Comment by nickolasclarke** [comment]
@jflasher Any help still needed on this at the moment? It looks like this has still not gone live.

**Comment by jflasher** [comment]
Hi @nickolasclarke thanks for checking. We're just holding on https://github.com/openaq/openaq-fetch/pull/479 to bring down the overall memory footprint and make sure this amount of data doesn't have an adverse affect on the stability of the system. Don't need any additional help on this adapter specifically, thanks!

**Comment by jflasher** [comment]
Just created the https://github.com/openaq/openaq-fetch/tree/china branch which contains the adapter for this data. @MichalCz this should be good for you whenever you want to look at it. Note that it pulls from a private S3 bucket and I'll need to give you credentials that'll allow you to test the adapter, just let me know whenever you want them.

**Comment by jflasher** [comment]
Closed with #524
