### ISSUE TITLE
Create a more optimized fetches data store on S3

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#455]
Currently, we've got the `/realtime` key space in the `openaq-fetches` S3 bucket. We're running the aggregations off of this via Athena and it's working fine, but we could be doing it better. We should investigate making a more optimized store of the data. This would probably include

- gzipping the underlying CSV
- potentially partitioning (https://docs.aws.amazon.com/athena/latest/ug/partitions.html)
- convert to something like Parquet and/or ORC?

This should make the Athena aggregations less expensive and quicker. This is great not only for us, but also for anyone else running the Athena queries.

Related: we should put out a blog post showing people how to run Athena queries on top of the fetches data!

**Comment by jflasher** [comment]
Just some notes here as I investigate this. Using the `test-realtime` keyspace as a test dataset (~100 fetches) and the following aggregation to test

`select * from fetches.fetches_realtime_staging as db join (select max(from_iso8601_timestamp(date.utc)) max_date, location, city, parameter from fetches.fetches_realtime_staging group by location, city, parameter) as temp on db.location = temp.location and db.city = temp.city and db.parameter = temp.parameter and from_iso8601_timestamp(db.date.utc) = max_date`

Non-zipped: 160.4MB storage, 1.98s query time, 305.95MB data scanned
gzipped: 4.8MB storage, 2.39s query time, 9.24MB data scanned

So just looking at zipped vs non-zipped, expected time increase for decompression, but much lower amount of data scanned. Athena is priced based on data scanned, so even just implementing this piece would be a 97% price savings (though we would be paying a bit to store more data in S3, but should be negligible).

**Comment by dolugen** [comment]
This is great! Can we do more stuff with Athena now? 😄

**Comment by jflasher** [comment]
@dolugen yeah, I think it'd be worth looking at it again as a method to access the historical data, since that cost should've come way down.

**Comment by jflasher** [comment]
Closing this for now as there is no more immediate work that needs done. Investigating partitioning or alternate file formats is nice, but not needed at the moment.
