### ISSUE TITLE
Update cities for older EEA data

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#478]
Per #234, older data in the system has incorrect city names due to unclear data fields in source data. This is resolved with the new EEA adapter but needs to be cleaned up for older data.

Depends on #430

**Comment by RocketD0g** [comment]
Per a community member's input, this may be a persistent issue with the updated adapter, as well: https://openaq.org/#/locations?countries=DE&page=5&_k=4om6ul

**Comment by majesticio** [comment]
@russbiggs  this is related to #430. If we are settled on a method of updating data we could find some time to update the city names for older EEA data. However, perhaps we can roll this into the larger issue of using geocoding to fill in or update country, city/location values where data is null or inaccurate.

**Comment by russbiggs** [comment]
we can close this since we'll move to using city and countries names from the geocoding service instead of from the fetch system
