### ISSUE TITLE
Bosnia AQ data site changed

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#493]
An AQ Agency official in Bosnia notified me that the AQ website has changed: 

> Institute changed web site so opeaq lost connection with bosnian data.
> new adress is:
>  http://www.fhmzbih.gov.ba/latinica/ZRAK/vrijednostiPolutanata.php
> 
> also, we have new station - Ilijas (Ilijaš)  
> which is located on: Λ 18° 16 '09'' E 
>                                 Φ 43° 57' 36'' N 
>                                  h 459 m

**Comment by jflasher** [comment]
Closing is favor of https://github.com/openaq/openaq-fetch/issues/504
