### ISSUE TITLE
UK data timestamps

### ISSUE THREAD

**Issue by rickpeltier** [openaq/openaq-fetch#499]
It appears the UK-based data, at least for ozone, might have a date/time issue.  If one plots the data as a diurnal time plot (average for each hour of day), one would expect a peak concentration in early afternoon, when sun intensity is strongest.  But for at least a half dozen sites in the UK that I've checked, this peak occurs at 18:00.  if you plot data from the US, europe, or asia, you find the peak concentration of ozone occurs at midday as expected (or whatever GMT time is for local mid day time, depending on where you look).

![image](https://user-images.githubusercontent.com/36851453/39371637-2df93544-4a3a-11e8-9448-b9b5d2c3e2f4.png) (West Coast, USA.  Time is GMT, or peak concentration around 14:00 local).

versus:

![image](https://user-images.githubusercontent.com/36851453/39371769-81693e04-4a3a-11e8-9c50-675f4f92ea54.png) (London, Kensington, time is also GMT, which is local time as well.  Peak concentration around 18:00)

**Comment by majesticio** [comment]
Upon review, the data is being ingested correctly as reported by DEFRA. While the behavior of the o3 peak is anomalous, we can only use the data as provided by the source. Closing issue until more information is discovered.
