### ISSUE TITLE
NL adapter date looks to be off by one hour

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#50]
According to http://www.timeanddate.com/worldclock/netherlands/amsterdam, should be +1 UTC, but recent data looks like 

```json
{
"_id": "56744fa651dc60c200e1969d",
"date": {
"utc": "2015-12-18T19:00:00.000Z",
"local": "2015-12-18T19:00:00+00:00"
},
"parameter": "so2",
"location": "Amsterdam-Hoogtij",
"value": 2.3,
"unit": "µg/m³",
"city": "Amsterdam",
"coordinates": {
"latitude": 52.428,
"longitude": 4.77348
},
"country": "NL"
}
```

**Comment by dolugen** [comment]
It looks like the source XML has UTC dates, while the server is configured with Europe/Amsterdam (UTC+1).

For example, `2016012706-CO.xml` file has `Last Modified: 27-Jan-2016 06:50` while "start" and "end" date in the file is 05:00 and 06:00. I'd think the file for 06:00 would be created at 05:50.

**Comment by olafveerman** [comment]
Ups, hadn't seen this issue. Fix in above commit. Thanks for bringing this up again @dolugen
