### ISSUE TITLE
Official (QA/QC'ed) Rio de Janeiro data (not in real-time)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#501]
See message below and attachment. 

(First this issue must be dealt with: https://github.com/openaq/openaq-data-format/issues/17)

> Please use the following link - http://portalgeo.rio.rj.gov.br/output/RioNASA/Rio_AQ_Data.zip - to download Rio air quality data from the years 2012 to 2017. In this zip file you will also find an excel spreadsheet which works as a data dictionary. At last, attached to this e-mail you will find a .txt file with the coordinates (WGS84 Geographic Coordinate System) of the monitoring stations.

Attached coordinates: 
[Coordinates.txt](https://github.com/openaq/openaq-fetch/files/1956485/Coordinates.txt)

**Comment by dolugen** [comment]
How do you go about entering non realtime data into the API? Do you convert it to a CSV that can be imported to the DB?

**Comment by jflasher** [comment]
Yeah, to date, I've made an ndjson file of the data, stuck it in the bucket and let it be queried for aggregation by Athena. If it's older than 90 days, never goes into the database. 

An example is the `daily/manual/accra.ndjson` file at https://openaq-fetches.s3.amazonaws.com/index.html

**Comment by majesticio** [comment]
@russbiggs @caparker I think this relates to our new ingestion process. What is our current method off ingesting older data? Is it still true that data that is older than 90 days it will not get added to the database?

**Comment by caparker** [comment]
@majesticio 
Currently we are not removing older data from the ingest process. As of today, the best way to get data that has been manually downloaded ingested would be to shape it to match either the realtime-fetch or lcs-fetch process and then just add it to the respective folder. 

For a file in the realtime format it would go in `openaq-fetches/realtime-gzipped`  and would be a ndjson.gz file. This format includes both the measurement and the station information so there is no need to load a separate station file.

For a file in the lcs format it would go in `openaq-fetches/lcs-etl-pipeline/measures` and would be a csv.gz file. In addition to this file you would also need to add a station/metadata file if you were loading data for a station that doesnt currently exist. The new lcs ingest method SHOULD create the new station if provided just the measurements file but it would have only limited meta data.

**Comment by majesticio** [comment]
I see, thanks for the clarification.  Closing this issue as the sources are no longer available.
