### ISSUE TITLE
How can I upload my data?

### ISSUE THREAD

**Issue by Coconaut11** [openaq/openaq-fetch#502]
Hi, I’m doing a project for school which involves creating an air contamination sensor and the plan is for it to update the results automaticly to some air contamination database, so I think OpenAQ would be perfect. After a little bit of research, I haven’t figured out how to upload the results to OpenAQ. Do I have to register and get an specific API to do so? Or the normal API would work? Thanks.

**Comment by jflasher** [comment]
Hi @Coconaut11 thanks for reaching out! We don't currently have a mechanism to insert low-cost sensor data into our platform. You can find more info at https://github.com/openaq/openaq-info/blob/master/FAQ.md#suggestions
