### ISSUE TITLE
iconv dependency causing install error

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#513]
I recall this happening on Windows, now I'm seeing this on Mac. `npm install` fails with `node-gyp rebuild` error from `iconv`. The package is only used in the currently disabled Moscow adapter. So I propose to remove the dependency for now (We have no idea when the updated Moscow source will be ready).

**Comment by dolugen** [comment]
Oh, looks like you need to remove the adapter too.

**Comment by jflasher** [comment]
Let's actually hold on this. @MichalCz is looking at a different way to handle the adapters which wouldn't load unused ones. For historical purposes, I'd rather not remove unused adapters. Though I guess they'd still be in the git history... Anyways, let's hold and see what @MichalCz wants to do with adapter loading.

**Comment by MichalCz** [comment]
I actually made iconv work regardless. But yes, adapters can be loaded as modules with their own package.json. This can be a directory or a separate module from another repo or even npm.

**Comment by sval-dev** [comment]
On Windows, I needed to install VS 2015 build tools and use "npm config set msvs_version 2015" to get iconv to install. On OS X using node 10, I needed to upgrade nan before installing iconv to get the install to proceed.

**Comment by MichalCz** [comment]
@sval-dev can you post the precise version of "nan" - I'll upgrade and package-lock it in my branch.

**Comment by sval-dev** [comment]
I'm at 2.10.0 on OS X.

**Comment by MichalCz** [comment]
Ok, I'll use that. :)

**Comment by MichalCz** [comment]
In my branch iconv@2.3.0 and nan@2.11.0. :)

**Comment by MichalCz** [comment]
@sval-dev the changes fixing this issue have been merged. Can you confirm?

**Comment by dolugen** [comment]
No problem installing with current trunk, closing this.
