### ISSUE TITLE
India - additional sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#52]
## **UPDATE: 20 Mar 2016: Please see my comment below (also timestamped 20 Mar 2016) for updated information and formatting of this issue.**

Note: While several sources are listed, none are straightforward. If you'd like a straightforward new data issue, visit this issue for adding data sources from Tehran, Iran: https://github.com/openaq/openaq-fetch/issues/51

Below are listed potential other sources in India, contributed by the OpenAQ Community:
These are listed as high priority because members of the community suggested them.

(1) http://www.cpcb.gov.in/CAAQM/frmUserAvgReportCriteria.aspx
Note: Several Sites around India. I have not been able to access any data yet from this link with any combination of places I have put in. I'm also uncertain if it yields AQI or physical concentrations yet.

(2) http://164.100.160.234:9000/
Note: Several sites around India. These values are in AQI.

(3) http://www.cpcb.gov.in/CAAQM/mapPage/frmindiamap.aspx (same presumed sources as (1), just different view)
Note: Several sites around India. To date, we've had issues programmatically accessing these data - something to do with a timeout issue perhaps? Do you recall,@jflasher? 

(4) http://mpcb.gov.in/envtdata/demoPage1.php
Note: Several sites around India. Looks like daily-averaged data. Unclear if data are available in real-time.

**Comment by masalmon** [comment]
Hi,

I have suggested some of these sources which I know are not that easy. Thanks for creating the issue!

(1) What have you tried exactly? I attach an example of a query for which I could get data.
![data1](https://cloud.githubusercontent.com/assets/8360597/12016890/b33e502e-ad50-11e5-8f4d-8b9e02a53cb5.png)
![data2](https://cloud.githubusercontent.com/assets/8360597/12016891/b354db6e-ad50-11e5-8ee7-1fb00c5f8f0b.png)

(2) A problem with the AQI is that one cannot get values for the past (at least I couldn't)

(3)Yes this is the same source as (1) but you also get the data availability. http://www.cpcb.gov.in/CAAQM/Auth/frmViewReportNew.aspx However I do not know how good it is (using it I could e.g. see when the 2 stations in Hyderabad started working but I haven't used it much).

**Comment by RocketD0g** [comment]
**Updating and reformatting from original issue above:** 

- **Country of data source:** India
- **Specific coverage within country:** Several cities within India

- **URL:** The url's of interest are nested and laid out accordingly:

_Map with coverage across India from CPCB:_
http://www.cpcb.gov.in/CAAQM/mapPage/frmindiamap.aspx

_Clicking on a state, there is finer, city-level coverage on the map. Example:_
http://www.cpcb.gov.in/CAAQM/mapPage/frmuttarpradesh.aspx?stateID=28

Then, clicking on a given city, a pop-up will be generated that gives a choice of accessing data or station details (e.g. coordinates) for a list of stations within the city (example):
http://www.cpcb.gov.in/CAAQM/frmStationdetails.aspx?cityID=136

_Data for a given station is shown as (example):_
http://www.cpcb.gov.in/CAAQM/frmCurrentDataNew.aspx?StationName=BTM&StateId=13&CityId=136

- **Pollutants measured:** Differing combinations of PM10, PM2.5, NO2, CO, SO2 (perhaps others)

- **Are units of measurement clearly indicated (e.g. do you see 'AQI', 'ppm' or 'ug/m^3'?) Note: We cannot directly input AQI, API, AQHI, etc. values directly into our system.**
Yes

- **Comments about units: [ex. 'They are viewable on {this page}, see the table]**
They are clearly listed in the table.

- **Are there date+timestamps for pollutant measurements?** 
Yes, and please note ,they are in running 24hr averages.

- **Are time intervals otherwise indicated on the site (e.g. 'Measurements are 15 minute averages'):**
Yes, 24 hr running averages updated at intervals.

- **Are coordinates for the stations clearly indicated or discernible? Comment. (e.g. do you see a map or a list of coordinates):**
Yes, these are viewable when you click on the "view details" page here:
http://www.cpcb.gov.in/CAAQM/frmStationdetails.aspx?cityID=136

- **Are you with the host agency and may we contact you?:** No.

[OPTIONAL]Your name/contact info/interest in open air quality data: n/a
