### ISSUE TITLE
New measurement count showing up in fetches table even though new data is not actually inserted

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#528]
Looking at the fetches table, the total count and count of new items inserted within the `results` object is being incremented even if there is no new data inserted.

You can test by running something like `node index.js -s StateAir_Hanoi` twice in a row. The first time, you should expect to see 24, the second time you would expect 0 (or maybe 1 if you hit the time just right). Instead, 24 is showing up for the `count` and in `results` object in fetches table.

@MichalCz could you look into this? It's not super urgent since I don't believe any new data is being inserted incorrectly, just the counts are off. Thanks!

**Comment by MichalCz** [comment]
Hi Joe,

Yes it seems that [this line](https://github.com/openaq/openaq-fetch/blob/develop/lib/measurement.js#L74) causes it - if there are some inserted values the count will be correct, but if there's 0 (i.e. all are filtered) the condition will evaluate to counts.total. I'll create a fix pull request in couple minutes.

M.
