### ISSUE TITLE
AQ Data from Medellin, Colombia (API available)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#540]
From Santiago Jaramillo of SIATA:

API services for the PM2.5 official network of Medellin:

- List of all the stations with hourly data and its corresponding data-quality flag, updated automatically and periodically (each day). In this example we show last 24 hours, but it can be increased for a longer period of time: https://siata.gov.co/EntregaData1/Datos_SIATA_Aire_pm25.json

Data published via this service should be displayed when the data Quality Flag <= 2.5 (which is our categorization for good quality data). If the Quality Flag is 2.6 or bigger (>= 2.6) the PM2.5 data is not qualified as good by our data validation team or is marked as missing.

- PM2.5 average of a 24-hours period for all the stations. 
The general link is: http://siata.gov.co:8089/estacionesAirePM25/token/
We use different "token" for specific authentication to the service (we can generate a new token on the web service specifically for your applications), for example, the next link provides an example token for the service so it can be accessed:
http://siata.gov.co:8089/estacionesAirePM25/cf7bb09b4d7d859a2840e22c3f3a9a8039917cc3/

_[If you take this issue, please be sure to assign this to yourself to let others know you are working on it.]_

**Comment by camilo-trujillo-siata** [comment]
We at SIATA are not very proficient using node.js so making an adapter for our data can take us some time. However we have deployed some new endpoints using the openaq-data-format over the following URLs (we think it should be easier to make an adapter and integrate our data from these endpoints than the previous ones):

http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_co.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_no.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_no2.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_ozono.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_pm1.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_pm10.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_pm25.json
http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_so2.json

We are deploying the last 6 months of hourly data for each of our stations/variables in these endpoints (from the current hour when the request is made). We can also provide larger or smaller datasets if needed. We are not sure how to integrate the information quality flags in the structure so for now we are only giving good quality information values as responses on the endpoints (-9999 as missing data when data is missing or has bad quality).

We also think we could merge this issue with #318 (we are the same source of data mentioned in the issue)

**Comment by RocketD0g** [comment]
Awesome! Tagging @jflasher in case he has comments.

**Comment by jflasher** [comment]
@camilo-trujillo-siata , thanks, this looks great! Thank you for matching it to the data format we use, it'll make it much easier to integrate. My only question is around the length of time the data is provide for. We check for new data every 10 minutes, so we do not need to receive the full 6 month history every time, that will just be more data transfer on both our sides. Is there any way to provide a `date_from` type of variable on the request? We could provide that when making the request to make sure we're only asking for the data we need. Or we could always have the endpoint only return the last day of data and could handle all the older data separately? Thanks!

**Comment by jflasher** [comment]
Thanks for all the work here! The adapter is in https://github.com/openaq/openaq-fetch/pull/548. I'll check it on staging first, but this should be going up shortly. 

Note that there are a few minor differences between your JSON output and our 
 format (https://github.com/openaq/openaq-fetch/pull/548/files#diff-8e33eefd6fbaf1a640990ee4dd28b437R46) but please do not change anything on your side or it'll break our adapter. Should hopefully be seeing this on the map later tonight.

**Comment by yaazkal** [comment]
Glad to see this working :)

**Comment by jordan-hernandez** [comment]
What should I do if I want to take the data for 2021?Thanks

**Comment by russbiggs** [comment]
@jordan-hernandez this repo is for the fetching process for openaq, not for data access from the platform. To access data from the platform view the API documentation at docs.openaq.org

**Comment by jordan-hernandez** [comment]
@russbiggs  Yes, I have data from 2020 but from 2021 the data is incomplete. For example, for the months of March to June there is no data in the application, as you can verify here. But I want to know if I can use the SIATA api to access the complete 2021 data. Because in this link (http://siata.gov.co/EntregaData1/Datos_SIATA_Aire_AQ_co_Last.json ) are the data from November 2021 to March 2023

**Comment by jordan-hernandez** [comment]
@camilo-trujillo-siata Can you help me with this problem? Thanks.

**Comment by jordan-hernandez** [comment]
@russbiggs Do you know why there's no data for that period of time?
