### ISSUE TITLE
 Help needed in making separate issues for several AQ sources not yet in our system

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#542]
A Community member shared a list of government AQ sources they know that are not yet included on the OpenAQ System. 

We need help with the task of parsing this information into separate issue.

To do that, each source below should be checked to:

-  Make sure it doesn't already exist as an issue (e.g. I think the SAAQIS source below already does)

- For appropriateness (e.g. we can't ingest AQI), 

- See if a minimum amount of data and meta data are shared to meet the required [OpenAQ data format](https://github.com/openaq/openaq-data-format). 

And if those items check out, a separate issue should be created for each source with the "new data" and "help wanted" tags.

*****
~Saudi Arabia (daily AQI: https://www.pme.gov.sa/Ar/Environment/EnvironmentSector/AirQuality/Pages/AirQuality.aspx  There is a national and three regional reports accessible from the left tool bar.~
(UPDATE: See below. Currently doesn't meet raw concentration requirements)

~Iran (daily and hourly, as AQI): http://aqms.doe.ir/Home/Index~
(UPDATE: Doesn't meet raw concentration requirements, also SEE #51) 

Belarus (daily PM and hourly other pollutants, reported as % of “mean acceptable level” = MAC): http://rad.org.by/monitoring/air.html
(NEEDS INVESTIGATION)

~Ukraine (selected pollutants, 4 times daily): http://cgo-sreznevskyi.kiev.ua/index.php?fn=lsza&f=lsza~ 
(UPDATE: Doesn't exist anymore, SEE #743 for new source)

~Japan, national air quality reporting system: http://soramame.taiki.go.jp/~ 
(SEE: #20)

~South Korea, national air quality platform: http://www.airkorea.or.kr/index~
(SEE: #555)

~Mongolia (rest of nation besides Ulaan Bataar): http://tsag-agaar.gov.mn/observation/environment-monitoring/air-data  Various pollutants, most are measured 3 times daily.~
(NEEDS INVESTIGATION, this source is already in the system but the adapter appears to have broken 5 months ago)

Real-time national monitoring by Kazhydromet (Kazakhstan).  No URL for data.  If you are interested in this, I can give you some pointers, but it is complicated. 
(NEEDS INVESTIGATION)

~UAE: https://www.adairquality.ae/~ 
(SEE: #435)

~Israel: http://svivaaqm.net/~
(SEE #483)  

Cyprus: http://www.airquality.dli.mlsi.gov.cy/
(NEEDS INVESTIGATION, might already be in the system through EEA) 

~Turkey: http://www.havaizleme.gov.tr/~ 
(SEE #19)

Romania: http://www.calitateaer.ro/public/assessment-page/map-page/?__locale=en 
(NEEDS INVESTIGATION, might already be in the system through EEA)

~South Africa: https://saaqis.environment.gov.za/~
(SEE: #722)

~Estonia: http://airviro.klab.ee/~
(SEE: #677) 

~Mexico (national network): https://sinaica.inecc.gob.mx/~
(SEE #672)

Real-time national monitoring Philippines.  No URL for data.  If you are interested in this, I can give you some pointers, but it is complicated. 
(NEEDS INVESTIGATION)

~Thailand: http://aqmthai.com/index.php?lang=en~ 
(SEE: #664)

~Iceland: https://www.ust.is/einstaklingar/loftgaedi/maelingar/~
(UPDATE: It's in the [platform](https://openaq.org/#/countries/IS?_k=qzas6d)!)

~New Zealand: https://www.lawa.org.nz/~ 
(UPDATE: See below. Can potentially get data from regional sources)

**Comment by charian** [comment]
Check this issue for South Korea
https://github.com/openaq/openaq-fetch/issues/555

**Comment by andrewharvey** [comment]
> New Zealand: https://www.lawa.org.nz/

This collates data country wide, but no easy data export/api and no open license. I've sent an email though just in case I've missed it.

**Comment by RocketD0g** [comment]
Thanks, @andrewharvey! It would be great to get NZ on the OpenAQ map!

**Comment by andrewharvey** [comment]
> This collates data country wide, but no easy data export/api and no open license. I've sent an email though just in case I've missed it.

They said:

> Unfortunately we do not have the ability to share real-time air quality data yet.  
> 
> Your best option is to contact councils directly to see if they have any data sharing options for the air quality data.

So looks like for now NZ data will need to be sourced from individual councils instead of one countrywide source.

**Comment by sruti** [comment]
Update on Saudi Arabia: Looks like the link has moved and a map of data (in AQI format) is at https://www.pme.gov.sa/Ar/Environment/AirQuality/Pages/AQ-Dashboard.aspx

And they are publishing daily PDF reports like [this one](https://www.pme.gov.sa/Ar/Environment/AirQuality//AQReports/%D8%AA%D9%82%D8%A7%D8%B1%D9%8A%D8%B1%20%D8%A7%D9%84%D8%A5%D8%AF%D8%A7%D8%B1%D8%A9/%D8%AA%D9%82%D8%A7%D8%B1%D9%8A%D8%B1%20%D9%8A%D9%88%D9%85%D9%8A%D8%A9/%D8%AA%D9%82%D8%A7%D8%B1%D9%8A%D8%B1%20%D9%85%D9%83%D8%A9%20%D8%A7%D9%84%D9%85%D9%83%D8%B1%D9%85%D8%A9/Jan%202020/12-1-2020%20%20%D8%AA%D9%82%D8%B1%D9%8A%D8%B1%20%20%D9%85%D9%83%D8%A9%20%D8%A7%D9%84%D9%85%D9%83%D8%B1%D9%85%D8%A9.pdf) but without knowing some Arabic it's hard to tell if there's raw data in an easier format.

**Comment by sruti** [comment]
Made an issue for Mexico #672

**Comment by majesticio** [comment]
Opening new issues for remaining data sources.
