### ISSUE TITLE
Add better filtering for large data sources

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#547]
If we can add better filtering for ChinaAQIData and Arpalazio, I think it'd go a ways towards avoiding timeouts. My guess is that some of the timeouts (when fetch doesn't finish in time) are happening because we're trying to save a lot of measurements to the database (even if they're duplicates).

**Comment by MichalCz** [comment]
Joe, just thinking out loud, but on arpalazio I think it may be a small change in line 131 - from `filter` to `until`... I'll check that out. Ideally not the whole file would get loaded...

**Comment by MichalCz** [comment]
Well... that doesn't work well with `request` - sadly it crashes because of ending the piped stream before the data is consumed...

I must think of that scenario on newer versions. So this is not really an option. :(

**Comment by majesticio** [comment]
I'm closing this issue because these adapters aren't currently being used and the fetch process has been updated since this issue was created.
