### ISSUE TITLE
New data source for Thailand 

### ISSUE THREAD

**Issue by nishadhka** [openaq/openaq-fetch#553]
New data source for [Thailand](http://aqmthai.com/index.php?lang=en). There are about 50+ station with hourly data for PMs, CO, NO2, O3 and, SO2. The data is given in non API, simple tabular form with most of metadata on openaq-data-format

**Comment by tverilytt** [comment]
@nishadhka There already seems to be an adapter for this?!
https://github.com/openaq/openaq-fetch/blob/develop/adapters/thailand.js

**Comment by jflasher** [comment]
@tverilytt thanks for looking into this. @nishadhka as @tverilytt pointed out, looks like we already have this source in place. Is there any other work to be done here or can we close this issue?

**Comment by nishadhka** [comment]
Sorry @tverilytt, missed to verify with available adaptors. @jflasher yes, can be closed
