### ISSUE TITLE
AirNow ozone data not reported after 10/13/2018

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#556]
Issue made on behalf of a community member:

> I wanted to check in as we noticed that many 
> stations which report O3 on AirNow (e.g., US, Canada, US embassies) to 
> openaq say their last reading was on 2018/10/13 and I was wondering if 
> you knew if there was a reason for this loss in reporting or observing data?

Given the data from the AirNow and the embassies flow differently, not sure why both aren't reporting ozone...@jflasher doesn't think this has to do with the recent streamlining of adapters to the system.

**Comment by jflasher** [comment]
@MichalCz this is happening because ppb conversion is commented out at https://github.com/openaq/openaq-fetch/blob/develop/lib/utils.js#L32-L35. Do you remember why this was done?

**Comment by MichalCz** [comment]
I'm not sure. I'll check the log little later today.

M.

**Comment by MichalCz** [comment]
@jflasher it's in fact the issue of which `ppb` we're using here - is it the long ppb or short ppb... Here's our conversation: `https://github.com/openaq/openaq-fetch/pull/520#issuecomment-420810863`.

So the question is what we should do with the unit if we get it - should it be treated as `1 particle / 1,000,000,000,000 particles` (so there's a *milliard* between *million* and *billion*) or is it `1 particle / 1,000,000,000 particles` (where there isn't).

What I've read is that both scales are actually used and I'm not sure if some kind of distinguishing factor should be taken into account - like a custom `pplb` unit which would indicate the *long scale*.

M.

**Comment by RocketD0g** [comment]
In general, let's assume ppb = parts per billion = 1/1E9. Perhaps we can indicate in the data format page that we mean 1 per billion. In AQ monitoring, I haven't encountered the other interpretation (this doesn't mean it doesn't happen though).
