### ISSUE TITLE
Kosovo AQ data - all necessary data and meta data appear available

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#572]
Here is a website that share AQ data for Kosovo: http://kosovo-airquality.com/secure/index2.html

Unfortunately, to my knowledge there does not appear to be a programmatic means to access the data, so looks like it would need to be scraped.

The physical data appears when you hover over a given station. It has units, and I am told the data are hourly. 

I believe the coordinates would have to be gotten by hand, by comparing the station locations and a source like Google Maps. I can help out with that if someone is able to take this adapter on.

I labelled this a high priority because Kosovo - and especially Pristina - experience severe AQ in the wintertime.

**Comment by tverilytt** [comment]
Hi Christa :-)

I looked closer into this and wrote up a simple Node.js JavaScript function to parse out the measureemnt data from the HTML.
It is by far not bullet-proof, but as long as the HTML page structure stays the same, it should be able to get to the data.

See below for links to data and code.

I am happy to assist to get things into Open AQ Fetch.

I put the code on RunKit, it can be found here:
https://runkit.com/tverilytt/kosovoaq

And the data endpoint is here:
https://kosovoaq-l8ngdmhxli2a.runkit.sh/

**Comment by MichalCz** [comment]
Hi @tverilytt,

Take a look at [adapter documentation for OpenAQ](https://github.com/openaq/openaq-fetch/blob/develop/docs/adapter.md). It should be fairly simple to implement intially - just export your async method from L109 as fetchStream and double check if your format is ok.

Of course consult @RocketD0g to make sure the units and quality of the data is ok... I know way less about that than I wished I had. :)

**Comment by tverilytt** [comment]
@MichalCz Thanks for that :-) I have read up a bit on adapters, sources, and looked at some adapter implementations too. E.g. the one for Norway, which I know pretty well.

I have a question regarding the architecture on adapters, maybe @jflasher or others can elaborate a bit?!

Who hosts the adapters, and where? Open AQ on AWS?
I run on RunKit as of now, since it is so convenient for Node.js stuff in a browser...

I can work on the data format to fit Open AQ reqs, and test locally with streams. Then maybe check back here for assistance for including adapter, if desired...

Cheers
-jo

**Comment by tverilytt** [comment]
@RocketD0g I have used Google Maps to get location coordinates, great if someone wants to double-check :-)

const coordinates = {
  Drenas : { // 42.62551717860738,20.896225734037785
    latitude : 42.62552,
    longitude : 20.89623
  },
  Gjilan : { // 42.46100366178403,21.467255332788113
    latitude : 42.46100,
    longitude : 21.46726
  },
  'Hani i Elezit' : { // 42.153772879592786,21.296323467845127
    latitude : 42.15377,
    longitude : 21.29632
  },
  Mitrovice : { //  42.89165029364315,20.868949929916425
    latitude : 42.89165,
    longitude : 20.86895
  },
  Peje : { //  42.65959450714422,20.284551553936808
    latitude : 42.65959,
    longitude : 20.28455
  },
  'Prishtine - IHMK' : { // 42.64869532066342,21.1371357574585
    latitude : 42.64869,
    longitude : 21.13714
  },
  'Prishtine, Rilindje' : { // 42.65939498964757,21.157230867398084
    latitude : 42.65939,
    longitude : 21.157230
  },
  Prizren : { // 42.21585246455938,20.741575823942526
    latitude : 42.215852,
    longitude : 20.74158
  }
};

**Comment by tverilytt** [comment]
Updated version now on RunKit, hopefully data format is up to Open AQ requirements now.
fetchData legacy version at the moment, will add the stream version.

**Comment by jflasher** [comment]
Thanks @tverilytt! You can see more info at https://github.com/openaq/openaq-fetch/blob/develop/docs/adapter.md but basically, you'll provide a new source entry in https://github.com/openaq/openaq-fetch/blob/develop/sources/xk.json and then an adapter in https://github.com/openaq/openaq-fetch/tree/develop/adapters to handle that source. All the code will be run by OpenAQ. It is run on AWS, but you don't need to worry about that. The adapters are written in Node.js and each gets run independently. To test, you can run locally with a command like `node . -dvs sourceName' to run for just the source you added. And it'll print out all the data the system would try to save to the database and let you know if it's seeing certain common errors with the data.

**Comment by MichalCz** [comment]
Hi jo,

You can simply return the array like this:

    return getKosovoAQ();

Scramjet is not needed here, any stream or array will do.

**Comment by tverilytt** [comment]
@MichalCz Cool, thanks a lot!
I think it is getting closer now, latest RunKit version shold (always) be here:https://runkit.io/tverilytt/kosovoaq/branches/master

I will pull the repo and try out locally.

Cheers
-jo

**Comment by tverilytt** [comment]
The adapter seems to pass the dry run test now with: 'node . -dvs kosovo'.

Is next step to create a PR?!

Cheers
-jo

**Comment by jflasher** [comment]
If you’re seeing the data you expect, then yep!

**Comment by tverilytt** [comment]
Cool.
sources/xs.json already exists, so I though adding this entry to it. Probably need some verification...

    {
        "url": "http://kosovo-airquality.com/secure/ValueTable.html",
        "adapter": "kosovo",
        "name": "Kosovo",
        "city": "",
        "country": "XK",
        "description": "Kosovo data from kosovo-airquality.com",
        "sourceURL": "http://kosovo-airquality.com/secure/index2.html",
        "contacts": [
            "info@openaq.org"
        ],
        "active": true
    }
