### ISSUE TITLE
Data not saving to S3

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#579]
@MichalCz heads up that I think there may be an issue arising from the recent update in scramjet or scramjet-core. It looks like the code to save to S3 is not getting run after the update. I tested before and after the updates locally to try and narrow down. Looks like scramjet-core@4.16.17 works but scramjet-core@4.17.0 does not. Trying to peg the version now via hotfix.

**Note for anyone else looking at this issue, this will affect new data not showing up on the map.**

**Comment by MichalCz** [comment]
Will check today.

**Comment by jflasher** [comment]
Thanks! I reverted so data is flowing back in again. Pulling the hotfix down to staging. Whenever you think you've got it fixed, let me know and we can look to push the changes again. Doesn't need to be today, next few days would be great if possible.

**Comment by jflasher** [comment]
Closing this issue as the immediate cause was remedied, we'll handle other items in another PR.

**Comment by MichalCz** [comment]
I have a lead on what could be causing this, but I need to check the code in fetch. I believe that a fix in scramjet-core uncovered an error in an async function used in fetch.

**Comment by MichalCz** [comment]
@jflasher it seems that I did manage to outsmart myself and use some non-documented feature in `scramjet` which lead to the problem.

Luckily the fix adds just two lines of code. I'll create a pull request later today.
