### ISSUE TITLE
Switch to using DynamoDB

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#59]
Related to https://github.com/openaq/openaq-api/issues/141, trying to first get writing to DynamoDB working. I'm writing to a table (yay!), but there are some weird behaviors (boo). Specifically, using `Texas` and `Sao Paulo` data sources as examples, if I write all the `Texas` data, it saves fine, but then when I go to write `Sao Paulo` data into the same table, I seem to be losing some of the `Texas` data. I have no idea how writing more data into the database can make other data disappear. I thought I could be accidentally overwrite `Texas` data with `Sao Paulo` data, but I have done a few things to convince myself that this isn't the case, so not sure what it is at the moment.

Example output before and after a `Sao Paulo` data source looks like below

```shell
Brizo: ~
$ aws --profile openaq dynamodb scan --table-name measurements --filter-expression 'country = :country' --expression-attribute-values {\":country\":{\"S\":\"US\"}} --select COUNT
{
    "Count": 1366, 
    "Items": [], 
    "ScannedCount": 1366, 
    "ConsumedCapacity": null
}

Brizo: ~
$ aws --profile openaq dynamodb scan --table-name measurements --filter-expression 'country = :country' --expression-attribute-values {\":country\":{\"S\":\"US\"}} --select COUNT
{
    "Count": 899, 
    "Items": [], 
    "ScannedCount": 3045, 
    "ConsumedCapacity": null
}
```

The total number of records does increase, but doesn't seem to get to the right amount. And now even weirder, when I try to insert records in batches after each other, the total number of records in the database decreases? Craziness!

**Comment by jflasher** [comment]
Ok, this is all down to user error :) Apparently the request below that I was using to verify item count is paged and so I wasn't getting real total item counts. :-1: 

```
$ aws --profile openaq dynamodb scan --table-name measurements --select COUNT
{
    "Count": 3045, 
    "Items": [], 
    "ScannedCount": 3045, 
    "ConsumedCapacity": null
}
```

Did a check by doing the below and it all looks good

```
            dyno.scanStream()
              .on('data', function () { count++; })
              .on('end', function () {
                console.log(`Datebase count: ${count}`);
              });
```

h/t @rclark

**Comment by RocketD0g** [comment]
What? No :-1:! Mystery of the not-so-disappearing data is solved, so I give this a :+1:!

**Comment by jflasher** [comment]
Yeah, the :-1: was mostly for me!
