### ISSUE TITLE
Data on agaar.mn (Mongolian AQ data) no longer shares physical values

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#598]
A representative from the National Agency of Meteorology and Environmental Monitoring in Mongolia contacted me, letting us know that the data on agaar.mn, where we pull in Mongolian data, is no longer physical data, but Mongolian Air Quality Index data. 

I'm seeking to learn if the physical data are shared elsewhere and also the date at which this change occurred (roughly October 2018).

For now, we should stop this adapter from ingesting new data. cc: @jflasher

**Comment by jflasher** [comment]
Source is now disabled.

**Comment by RocketD0g** [comment]
As an update, a Mongolian air quality agency official has let us know the physical data to AQI data change occurred in Feb 2019. This means that data recorded in Feb 2019 until the source was disabled (see comment above) should be treated as invalid data.

**Comment by robertritz** [comment]
Thanks for keeping on top of these things! Would it be possible to reverse engineer the physical values?

It does appear they are reporting PM2.5 and other pollutants separately. I may be wrong but it would seem to be possible to "go backwards" through the Mongolia AQI formula to derive the physical values. AQI using only one pollutant is calculated relatively simply. I'm going to see if I can find the Mongolian AQI formula and test it out.

It appears AirVisual is still reporting these numbers (only PM2.5 though it seems). This is odd as some stations don't have PM2.5 sensors but AirVisual is only reporting PM2.5.

People in Need, a Czech international NGO, recently installed a new network of sensors in areas outside the city center. I've been told by People in Need that they are working on a web portal where all data will be accessible for researchers and the public.

**Comment by jflasher** [comment]
@robertritz this has come up before with other sources and we have always decided not to convert from AQI. The formula may change or requires multiple time points (I believe the EPA does this) but basically, it means we'd be making assumptions around the data that's being provided directly by the source. We try to only capture what is actually provided by the source. Our hope instead would be to encourage agencies to make the data available as physical values (more on that [here](https://medium.com/@openaq/why-looking-beyond-air-quality-index-values-matters-d903bf773e1)). 

Sounds great about the Czech data, please ask them to provide physical values and have an API! 😁 We only store reference- and research-grade data. If this matches that description, please make an issue when the data is available and we can look at adding it, always great to make more data available.

**Comment by robertritz** [comment]
Thanks for the fast response. I definitely understand why OpenAQ wants to have the best quality data and in general I agree with your stance. I believe this move by agaar.mn is designed to obfuscate things for researchers and the public. 

When I know more about the People in Need platform I will let you know. From my understanding, they will have an API. Currently, their sensors are reporting to AirVisual as physical values, but they do not have an open API. Once it launches that will change though I believe. 

Thanks again.

**Comment by sruti** [comment]
Closing this since it has been resolved! 

@robertritz Regarding People in Need, if it's not reference-grade data, we're piloting a low cost sensor platform and would love to have them be involved. More info can be found [here](https://medium.com/@openaq/were-partnering-with-edf-and-development-seed-on-low-cost-sensing-653fe0a4ef46).
