### ISSUE TITLE
New Data Source - Slovenia

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#61]
Data submitted by someone from the Source Google form for Slovenia: 

Hourly: http://www.arso.gov.si/xml/zrak/ones_zrak_urni_podatki_zadnji.xml
Daily: http://www.arso.gov.si/xml/zrak/ones_zrak_dnevni_podatki_zadnji.xml"

**Comment by dolugen** [comment]
Anyone working on this?

Although I don't know Slovene, this is far better than the Indian source.

@RocketD0g Could you confirm that they're using the standard units?

Some phrases translated with Google:

Slovene | English | OpenAQ usage
-----------|-----------|--------------------
vir | source | attribution name?
datum priprave | date of preparation | date
postaja | station 
sifra | cipher
dolzina | length | longitude
sirina | width | latitude
nadm visina | height above sea
merilno mesto | measuring point | location name, source name
datum od | date from
datum do | to date

**Comment by RocketD0g** [comment]
No one's working on this to my knowledge, but having trouble confirming
values. Prob best to hold on this.

On Wed, Feb 24, 2016 at 12:06 AM, Dolugen Buuralda <notifications@github.com
> wrote:

> Anyone working on this?
>
> Although I don't know Slovene, this is far better than the Indian source.
>
> @RocketD0g <https://github.com/RocketD0g> Could you confirm that they're
> using the standard units?
>
> Some phrases translated with Google:
> Slovene English OpenAQ usage
> vir source attribution name?
> datum priprave date of preparation date
> postaja station
> sifra cipher
> dolzina length longitude
> sirina width latitude
> nadm visina height above sea
> merilno mesto measuring point location name, source name
> datum od date from
> datum do to date
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaq/openaq-fetch/issues/61#issuecomment-188073660>.
>



-- 

507.246.2097

**Comment by RocketD0g** [comment]
Also, @jflasher is hoping to add in EU data via an API from the EEA soon,
and slovenia may be a place where we're getting data from, but I can't
confirm 100% at this moment. I guess another reason to hold on this.

On Wed, Feb 24, 2016 at 6:21 AM, Christa Hasenkopf <
christa.hasenkopf@gmail.com> wrote:

> No one's working on this to my knowledge, but having trouble confirming
> values. Prob best to hold on this.
>
> On Wed, Feb 24, 2016 at 12:06 AM, Dolugen Buuralda <
> notifications@github.com> wrote:
>
>> Anyone working on this?
>>
>> Although I don't know Slovene, this is far better than the Indian source.
>>
>> @RocketD0g <https://github.com/RocketD0g> Could you confirm that they're
>> using the standard units?
>>
>> Some phrases translated with Google:
>> Slovene English OpenAQ usage
>> vir source attribution name?
>> datum priprave date of preparation date
>> postaja station
>> sifra cipher
>> dolzina length longitude
>> sirina width latitude
>> nadm visina height above sea
>> merilno mesto measuring point location name, source name
>> datum od date from
>> datum do to date
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openaq/openaq-fetch/issues/61#issuecomment-188073660>
>> .
>>
>
>
>
> --
>
> 507.246.2097
>



-- 

507.246.2097

**Comment by dolugen** [comment]
OK, got it.

**Comment by dolugen** [comment]
@RocketD0g I've added a new label for blocked issues, hope you don't mind.

**Comment by RocketD0g** [comment]
On the contrary - good idea, @dolugen!

**Comment by ddbk** [comment]
This is actually an official API of the Slovenian Environment Agency.

I can confirm[1] the units for this data source:
PM10, SO2, O3, NO2 are in µg/m³
CO is in mg/m³

[1] http://www.arso.gov.si/zrak/kakovost%20zraka/podatki/dnevne_koncentracije.html (in Slovene only)

**Comment by jflasher** [comment]
Thanks for the link @ddbk. Did a little digging and it looks like we've got three sources.

- http://www.arso.gov.si/zrak/kakovost%20zraka/podatki/dnevne_koncentracije.html looks to be most clear, but I don't see any lat/lon for stations?
- http://www.arso.gov.si/xml/zrak/ones_zrak_urni_podatki_zadnji.xml has lat/lon but no units for pollutants
- [EEA](https://tableau.discomap.eea.europa.eu/t/Aironline/views/Airquality_E2a_monitoring/DashboardE2a?:embed=y&:showShareOptions=true&:display_count=no&:showVizHome=no) They show they're getting data from SI, but they aren't getting PM10, both of which these other two sources have.

I think there is a bunch of data here, we just need to figure out what's in EEA versus these other sources so we don't duplicate anything.

**Comment by jure** [comment]
I speak JS and Slovene and would be willing to add these sources. :)

For the hourly data there is a description of the data in the XML (http://www.arso.gov.si/xml/zrak/ones_zrak_urni_podatki_zadnji.xml), with all the units:
http://www.arso.gov.si/zrak/kakovost%20zraka/podatki/opis_ones_zrak_urni_xml.pdf

This source is as official as it gets and looking at the data sent to EEA (there's a 5 day data gap right now, for unknown reasons), I think this one is better and more reliable.

In addition to this source, there's another one for capital Ljubljana (with two stations):
http://www.ljubljana.si/si/zivljenje-v-ljubljani/okolje-prostor-bivanje/stanje-okolja/zrak/?source=vosnjakova-tivolska

http://www.ljubljana.si/si/zivljenje-v-ljubljani/okolje-prostor-bivanje/stanje-okolja/zrak/?source=bezigrad

**Comment by jflasher** [comment]
Hi @jure, don't worry, I asked for more details on an issue I opened less than a week ago, happens to the best of us! 

If the data is reporting to EEA, our preference would be to get it from there. If it's reporting slowly or not accurately, our goal is to bring that to people's attention and try and help that get fixed. Basically, we're not trying to circumvent the EEA system (same is true for other big national aggregators), but we'd like to work with them as a community of interested parties to make sure the whole ecosystem is working better. 

The Ljublijana sources (if not going up to EEA) would be an interesting add though.

**Comment by jure** [comment]
@jflasher I reached out to ARSO (Slovenian Environment Agency) about the data gap at EEA, currently 5 days, and haven't gotten a response yet. I did get a response on why they're not including PM10 data in the submissions to EEA, and they said, translated: "We're submitting this data yearly, since our real-time method is not referential". I'm sure this doesn't mean the measurements are bad, but they're probably lacking certain tests that make a method referential. 

In any case, that means that the advantage of #232 over EEA is currently two-fold: 1. updated vs 5 day gap, 2. includes PM10.

The source has been stable since December 2011.

I can make the PR report only PM10 measurements (not available on EEA), and we open a separate issue where we work on getting ARSO to reduce/remove the gap in uploads to EEA.

Ljubljana I'll add as a separate source/PR. I still need to lat/lon for the two stations.

**Comment by jflasher** [comment]
> I can make the PR report only PM10 measurements (not available on EEA), and we open a separate issue where we work on getting ARSO to reduce/remove the gap in uploads to EEA.

@jure this would be my preference, but would be good to get some others' opinions as well. 

cc/ @RocketD0g @olafveerman

**Comment by dolugen** [comment]
Maybe @jure is unavailable and someone can pick up where he left off.
