### ISSUE TITLE
Should we no longer accept measurements without coordinates?

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#619]
Somewhat related to https://github.com/openaq/openaq-api/issues/398 but also, measurements without coordinates are way less useful. I'm in favor of no longer fetching/storing measurements without coordinates. 

Anyone have any thoughts there?

cc/ @RocketD0g

**Comment by olafveerman** [comment]
I agree with @jflasher 

Is there even a use case for a measurement that has no location? Or only a very approximate location like city name?

**Comment by RocketD0g** [comment]
Yeah, agree with @jflasher and @olafveerman on no longer storing measurements without coordinates. 

Sure, some folks might want to just know x amount of data is produced by country y, and perhaps we know the country (or city) but not the coordinates for some subset of measurements. But I don't think that is enough of a use-case to justify including measurements without coordinates. 

Also, by not including such points anymore, I think it sends a clearer message that its way more valuable to include coordinates with any data that an entity is producing.

**Comment by majesticio** [comment]
@russbiggs can we close this? I don't think we ingest anything without location data

**Comment by russbiggs** [comment]
yeah new database setup requires lat,lng so we can close
