### ISSUE TITLE
Data from luftdaten sensors

### ISSUE THREAD

**Issue by KhurramFHassan** [openaq/openaq-fetch#624]
I made 2 air quality sensors following the excellent instructions at luftdaten.info site. These sensors are already reporting data to the luftdaten map and opensensemap for Pakistan. I would like to contribute this data to openaq as well. How can I do this?
Thanks
Khurram

**Comment by jflasher** [comment]
Hi @KhurramFHassan, sorry for the slow response, this initially ended up in my spam folder. We're currently figuring out how to best work with these types of sources. You can see a bit more info at https://github.com/openaq/openaq-info/blob/master/FAQ.md#suggestions.
