### ISSUE TITLE
Polish Adapter data missing

### ISSUE THREAD

**Issue by MichalCz** [openaq/openaq-fetch#629]
Hi,

It seems that the data from the GIOS adapter is missing on the website (update 22 days ago it says). I'll try to find some time to check and fix if needed, but can you perhaps check what the error is and paste it, so I can somehow make sense of it before I can run the code? This may take me a couple days before I have some decent slot.

M.

**Comment by majesticio** [comment]
Upon inspection it appears that data has been added in. If this issue needs to be reopened I am leaving this link to [download](https://powietrze.gios.gov.pl/pjp/archives) historical data and fill in gaps if needed.
