### ISSUE TITLE
China ozone observations delay or stall

### ISSUE THREAD

**Issue by ReaRuiRay** [openaq/openaq-fetch#631]
It seems that most of the ozone observations in China are updated every few hours. PM2.5 observations are updated much more frequently. I am pretty sure that the ozone concentrations are not up to date since nighttime ozone can't be so high. 

The image was captured from https://openaq.org/#/location/%E5%BE%90%E6%B1%87%E4%B8%8A%E5%B8%88%E5%A4%A7?parameter=o3&_k=9vj9y7

![image](https://user-images.githubusercontent.com/11169226/68251708-adbd1f80-005e-11ea-8029-a9a729f06724.png)

**Comment by jflasher** [comment]
Hi @ReaRuiRay, in this instance, I think we're really dependent on both the source and the library we use to get the data which is https://github.com/geoinsights/ChinaAQIData. We are a couple of commits behind the main branch of that library but I looked and there is nothing that'd affect the data values. 

If we can provide data that the values being captured by https://github.com/geoinsights/ChinaAQIData are not correct, I think we can probably open up a ticket over there? I believe the underlying source site structure makes it very hard to do this for non-Chinese speakers however.

**Comment by ReaRuiRay** [comment]
Thanks @jflasher for giving more insights! I will try their scraper and open a ticket there if I found the same problem.
