### ISSUE TITLE
Victoria, Australia new source

### ISSUE THREAD

**Issue by andrewharvey** [openaq/openaq-fetch#641]
Victoria, Australia provides air quality data through their EPA AirWatch program: https://www.epa.vic.gov.au/for-community/airwatch

Currently this data doesn't appear to be released under an open license, so I believe that means it can't be included for now.

I've sent off a request to ask for it to be released under CC BY 4.0, will see how that pans out.

In the meantime I've drafted a PR to add this source and adaptor #639

**Comment by sruti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review Andrew's GH activity](https://trello.com/c/kFVxOEIG/26-review-andrews-gh-activity)

**Comment by andrewharvey** [comment]
EPA Victoria has confirmed that this data is covered by the CC BY 4.0 license noted at https://discover.data.vic.gov.au/dataset/airwatch-data.
