### ISSUE TITLE
document develop/master branch

### ISSUE THREAD

**Issue by andrewharvey** [openaq/openaq-fetch#656]
The contributing and readme docs don't really mention the difference between the `develop` and `master` branch, so it's unclear when making a PR if it should be based of `develop` or `master`, we should document this.

There is a reference that `master` get's auto-deployed but the process to move from `develop` to `master` isn't documented.

**Comment by majesticio** [comment]
Fair point. The readme doc has been updated to reflect that we are currently using the lambda-deployment branch for deployment.
