### ISSUE TITLE
New Thai data source

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#664]
A colleague shared this data source - including PM2.5 for Thailand): http://air4thai.pcd.go.th/webV2/history/

(A reminder that a previous colleague in #542 also shared this one: http://aqmthai.com/index.php?lang=en )

**Comment by sruti** [comment]
- [x] Programmatic access
Data in air4thai table is pulled from API like so: http://air4thai.pcd.go.th/webV2/history/api/data.php?stationID=02t&param=PM25&type=hr&sdate=2020-05-07&edate=2020-05-07&stime=00&etime=18

- [x] Units + Station coordinates
Found through this API: http://air4thai.pcd.go.th/services/getNewAQI_JSON.php?stationID=02t

- [ ] Hourly averaged data?
Pretty sure, would be good to confirm from the Air Quality and Noise Management Bureau [info page](http://air4thai.pcd.go.th/webV2/aqi_info.php) (but it's in Thai)

This is pretty much read to go!

**Comment by RocketD0g** [comment]
Awesome! Just reached out to the original colleague who shared this and another one from Thailand to see if we can get insight on that last point.

**Comment by RocketD0g** [comment]
Response from Thai AQ professor:

The PCD of Thailand has hourly data for the parameters. They report data according to the standard.

The website you gave may have some error. See this website instead. You can see the averaging time there: http://air4thai.pcd.go.th/webV2/region.php?region=1

**Comment by RocketD0g** [comment]
Update from original source: (I believe this agrees with the above comment)

> Just got response from my contact in Thailand and he confirmed that it is hourly measurements, which are accessible from the following portal:

 

>http://air4thai.pcd.go.th/webV2/history/
