### ISSUE TITLE
Austrian adapter currently turned off - Looking OK to turn back on?

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#674]
The Austrian source file was set to inactive per the link to the commit below, but then all the other associated EEA countries that were also set to inactive were subsequently added back in. 

[Current state of Austrian source:](https://github.com/openaq/openaq-fetch/blob/develop/sources/at.json)
![Screen Shot 2020-02-10 at 1 22 19 PM](https://user-images.githubusercontent.com/13404290/74177805-74212500-4c08-11ea-8353-9f46c2c2bd95.png)

I believe Austria may have been meant to be turned back on, looking at the title of this commit by @jflasher and the other data sources being turned back on. @jflasher do you think that's correct and we should be OK to turn on?

https://github.com/openaq/openaq-fetch/pull/475/commits/01d23727e2a7850299beab8c88f4240068880de8

![Screen Shot 2020-02-10 at 1 23 24 PM](https://user-images.githubusercontent.com/13404290/74177915-a599f080-4c08-11ea-997d-86940b7bc9b2.png)

**Comment by jflasher** [comment]
Any of the EEA sources can likely be turned back on yep!
