### ISSUE TITLE
Bermuda shows up on OpenAQ Map for AQ data when there are no data

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#675]
Currently, OpenAQ is reporting data from the country of Bermuda. 

This is in error - the data are really coming from Rangoon, Myanmar. 

It looks like the [Airnow Monitoring Site Location file](https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/monitoring_site_locations.dat) located [here](https://files.airnowtech.org/?prefix=airnow/today/) has the incorrect country code form Myanmar (BM instead of the correct MM). 

![Screen Shot 2020-02-10 at 1 35 57 PM](https://user-images.githubusercontent.com/13404290/74179767-18f13180-4c0c-11ea-8f40-818fe4b260e4.png)

I've reported the issue to AirNow. (But note, this doesn't resolve [the issue here](https://github.com/openaq/openaq-fetch/issues/671), which describes both AirNow and StateAir adapters overlapping in non-US data sources.

**Comment by RocketD0g** [comment]
Wow, I got a reply back from EPA AirNow and they've already fixed it...in two hours! 

Can confirm  it is corrected by looking [here](https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/monitoring_site_locations.dat) too.

**Comment by RocketD0g** [comment]
Unfortunately, AirNow notified me that they've now changed the country code _back_ to what appears as the ISO two-letter country code for Bermuda (and changed the two-letter code for several countries - see below). This is because they are actually using FIPS (a US federal two-letter code for countries) instead of ISO. 

Here was the reply from AirNow:

> The CountryCode field follows FIPS formatting, and that is set to BG for Bangladesh, which is the correct 2 digit FIPS code (BD is the ISO country code for Bangladesh).
> I also reviewed the rest of our country codes. There were a few that were incorrectly using ISO country codes, and one that was incorrect entirely. Here are the changes
> Vietnam from VN to VM (FIPS)
> Myanmar from MM (ISO) back to BM (FIPS). This was the original request in this ticket.
> Gabon from GA (ISO) to GB (FIPS)
> Ivory Coast from CI (ISO) to IV (FIPS)
> Guinea from GN (ISO) to GV (FIPS) 

Side note: We may want to make the AirNow adapter no longer accept non-US, Mexico gov, and Canadian gov data and rely on StateAir for US diplomatic data? Seems kind of janky, but this would also resolve #671.

This also affects issue #680.

**Comment by olafveerman** [comment]
That's great to know. Should be simple to address with a converter based on something like: https://www.npmjs.com/package/country-code-lookup

**Comment by majesticio** [comment]
We are working on a geocoding solution to the country code problem
