### ISSUE TITLE
Peru AQ data has moved to a different spot on the same website

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#678]
Looks like Peruvian data has moved to a different spot on the same website. It is now here:

https://www.senamhi.gob.pe/?&p=calidad-del-aire

I'm not sure how useful [the old adapter](https://github.com/openaq/openaq-fetch/blob/develop/adapters/senamhi.js) will be, but hopefully it is just a matter of a simple move - looks like the url difference is 'de' versus 'del'!

@jflasher tagging you since you made the previous adapter...fingers-crossed it is that one small adjustment.

**Comment by jflasher** [comment]
Had to do some digging and updates, but https://github.com/openaq/openaq-fetch/pull/679 should fix the Peru data source.
