### ISSUE TITLE
Bangladesh data appearing in Denmark - Underlying Source Issue (reported)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#680]
Currently, OpenAQ is reporting data from the country of Denmark when the data actually originates from Bangladesh. This has to do with the wrong country code (DK vs BD <--the correct one) being used at the source, AirNow.

I've reported the issue to AirNow. (But note, this doesn't resolve Issue #671, which describes both AirNow and StateAir adapters overlapping in non-US data sources.

**Comment by RocketD0g** [comment]
Same underlying issue: https://github.com/openaq/openaq-fetch/issues/675#issuecomment-585652756

**Comment by majesticio** [comment]
We are working in a solution that uses geocoding to correct or fill in country codes
