### ISSUE TITLE
New data: Kosovo (more info needed before ready for development)

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#683]
Ran across Kosovo data. Despite its presumed currently unsuitable state for ingestion in OpenAQ, making an issue to acknowledge this real-time source exists.

Source: 
http://ihmk-rks.net/?page=2,5

As far as I can tell: 

- :x: AQI reported
- :x: unclear time-average interval
- :x: lacking location coordinates
- not in a machine readable format

Before this can be developed, the site needs to be explored for more data (it currently appears as RT data on aqicn, but this may or may not mean we have enough metadata to add) OR someone may need to reach out to the source.

**Comment by russbiggs** [comment]
Kosovo has a new reporting site here: https://airqualitykosova.rks-gov.net/en/

**Comment by majesticio** [comment]
Resolved with PR #933
