### ISSUE TITLE
New data: Mali from US Emb in Bamako

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#684]
Bamako, Mali PM2.5 data now available [here](http://dosairnowdata.org/dos/RSS/Bamako/Bamako-PM2.5.xml)

- Can be easily added to stateair.js adapter and source file created
- Doesn't appear to be added yet to AirNow (but could be a future issue, if it is, per #671

**Comment by sruti** [comment]
Added in #691. Closing the issue
