### ISSUE TITLE
Moscow, Russia - Data Sources

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#7]
48 hour Moscow data
http://mosecom.ru/air/air-today/station/spirid/table.html

**Comment by olafveerman** [comment]
Moving to this one, now SF is not needed anymore

**Comment by olafveerman** [comment]
Some notes from an initial investigation:

- http://mosecom.ru/air/air-today/ contains a list with all stations with links to the raw data
- the same page contains a map from which we can fetch the coordinates. It may be easier to fetch them here: https://maps.google.ru/maps/ms?hl=ru&ie=UTF8&oe=UTF8&msa=0&msid=204062887446841627595.0004c50733c2e9ae98dff&start=0&num=200&t=m&ll=55.752622,37.563629&spn=0.618278,0.95993&z=10&source=embed
- each station has two individual pages with predictable routes. In the case of Zelenograd 11:
  1. http://mosecom.ru/air/air-map/zelen_11/ -> metadata about the station
  2. http://mosecom.ru/air/air-today/station/zelen_11/table.html -> the raw data


This list includes **mobile stations**. Should we exclude these @RocketD0g?

**Comment by olafveerman** [comment]
How will we go about translation? Will we translate the location names?

**Comment by jflasher** [comment]
For the naming, we've kept local names but they've generally all been Latin based (with accents at times like [this](https://api.openaq.org/v1/locations?location=Pu%C5%82askiego)). I could see us using romanicised names, I think in some sense that might be nicer, but that might just be me. If we did that, seems like making sure they always get converted (and properly) might be difficult, especially if we're just picking up whatever new stations are on a site? For Mongolia and Thailand, we're already using romanicised names, but it wasn't some large decision that had been made, just what I grabbed.

Seems like having local names seems more proper, but I wonder if it's at the expense of the overall usability of the data. Maybe we could store both? Also seems difficult.

**Comment by dolugen** [comment]
Any updates on this since 2015?

**Comment by jflasher** [comment]
I think we've come to a general pattern with naming in the system now, so can probably look to bring these in.

**Comment by dolugen** [comment]
Continuing from Olaf's investigation:

* Should ignore the station pages (e.g. http://mosecom.ru/air/air-map/zelen_11/), as they don't have useful information to parse.
* Should ignore the mobile stations, as discussed with @RocketD0g (forgot where we talked)
* Olaf suggested getting the coordinates off of the Google Maps. Don't know how to do that right now, I'll get to that later. If you know how to do it, let me know.

**Comment by RocketD0g** [comment]
Awesome, @dolugen! 

I just exported their base map from kml and converted to a csv file. It has the station name transliterated in English and the lat/long:
https://www.dropbox.com/s/z5tsi0tnnel2oq4/russianstations.csv?dl=0

The cyrillic version is available in the xslx file. If that's preferable, let me know.
https://www.dropbox.com/s/i3jlbsh1e3xrsap/russianstations.xlsx?dl=0

In general and as a heads up, this list also appears to include historical stations that may no longer report data.

**Comment by dolugen** [comment]
Thanks! How are you exporting these files? I'd like to do them in the adapter, if possible. I've looked at the Excel file in Dropbox, but I don't see the Cyrillic names? I'd like the Cyrillic names. Maybe you were talking about your local file.

**Comment by dolugen** [comment]
Ok, I got it:

1. There's a `mid` parameter related to the embedded Google Maps tags. Look for it in the Iframe's head tag.
2. Go to `https://google.com/maps/d/kml?mid={mid}`
3. Extract the KMZ as a zip file and read the KML
