### ISSUE TITLE
Switch to using iconv-lite

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-fetch#714]
We can save some package weight and build time by using https://www.npmjs.com/package/iconv-lite instead of `iconv`. If https://github.com/openaq/openaq-fetch/blob/develop/sources/ru.json#L2 is deactivated for good, we may just want to remove the package altogether.

**Comment by dolugen** [comment]
Good idea. That package was giving me trouble when setting the project up on various OSes :-D

Speaking of, looks like the new Moscow source is up now.

**Comment by dalipkumar703** [comment]
I will look into it.
