### ISSUE TITLE
EEA for Italy does not pull anymore

### ISSUE THREAD

**Issue by magsyg** [openaq/openaq-fetch#749]
Italy is not currently pushing its data to EEA, I am not sure if we should switch to the more regional sources for this country instead of EEA. 
I am not sure if this issue is temporary, but I have looked at the map of the EEA stations: https://airindex.eea.europa.eu/Map/AQI/Viewer/ , and it looks like a lot of countries different stations are not reporting to the EEA at the moment.
Could then be more wise to switch to the more consistent regional sources

**Comment by majesticio** [comment]
It's true, many regions in Italy (and other countries) do not report to the EEA. We are currently making a list of regional sources and will begin adding them in soon. Thanks for bringing it up!
