### ISSUE TITLE
Issue with Mongolian AQ data appearing in Madagascar

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#757]
From a community member, it appears to be a country letter code related to https://github.com/openaq/openaq-fetch/issues/675#issuecomment-585652756

> I just checked out your data for Madagascar and wanted to let you know that when you search for data at these links:
> 
> https://openaq.org/#/locations?&_k=xkvxck  
> 
> https://openaq.org/#/countries?_k=8r5hen
> 
> it brings up data that is actually from Mongolia (Ulaanbaatar) and not Madagascar. It doesn’t appear to be a problem on the Map page. I don’t know if it’s an AirNow issue or a programming mistake on your side, but I thought you’d like to know.

**Comment by dolugen** [comment]
Looks like another AirNow country name mapping issue. AirNow's using MG for Mongolia, but on OpenAQ MG is Madagascar.

**Comment by dolugen** [comment]
This is fixable by compiling a mapping of country codes between AirNow and OpenAQ. (There should be another issue with details about this).

But the question is, what do you do with records already in S3 and database?

**Comment by majesticio** [comment]
We are working on a global solution that will use geocoding to fill in/fix country codes that are null or inaccurate.
