### ISSUE TITLE
Iceland - additional function in API to get a specific date

### ISSUE THREAD

**Issue by Stalfur** [openaq/openaq-fetch#775]
Hello, we have previously opened up an API for Iceland AQ data in #552 

There you could only fetch the last 24 hours, we have now added a new function there, getDate which loads the data for the selected date.

Example: https://api.ust.is/aq/a/getDate/date/2018-01-01

This is using the same structure as getLatest, the only difference is the input parameter (none for getLatest, valid date for getDate)

**Comment by majesticio** [comment]
Thanks, we are now using the api!
