### ISSUE TITLE
New Data: Quito

### ISSUE THREAD

**Issue by sruti** [openaq/openaq-fetch#776]
We have a new data source from the government of Quito, with an API!

- [X]  Data is ‘raw’ and reported in physical concentrations not in an 'Air Quality Index' or equivalent (e.g. AQI, PSI, API) format, with units (ug/m3 or ppm)

- [X] Data is at the ‘station-level' with geographic coordinates, not aggregated into a higher (e.g. city) level (coordinates found by clicking on each location)

- [X] Data is from measurements averaged between 10 minutes and 24 hours, and we know whether the timestamp is for the beginning or end of the measurement period

- [X] Programmatic access!

API call to get all stations and metadata: http://www.aqvisor.net:9090/openaq/location

**Comment by sruti** [comment]
# API Documentation
## for integration REMMAQ-OpenAQ

_Valeria Díaz, Juan Salvador, Paul Romero_

October 30th, 2020 - v 0.8

---

## `dataset`


This API will return a dataset where every record 
contains surveyed data for vector: 
**local time, magnitudes,** and **observation point**
in the format:

```
    {
        "date": {
            "local": "2020-10-21T04:00:00.000-05:00",
            "utc": "2020-10-21T04:00:00.000Z"
        },
        "parameter": "PM 10",
        "unit": "µg/m³",
        "value": 2.27346,
        "averagingPeriod": {
            "value": 24,
            "unit": "hours"
        },
        "location": "Carapungo",
        "city": "Quito",
        "country": "EC",
        "coordinates": {
            "latitude": -0.09548,
            "longitude": -78.44988
        },
        "sourceType": "government",
        "sourceName": "IMQ-AMBIENTE-REMMAQ",
        "mobile": "false",
        "attribution": [
            {
                "name": "REMMAQ",
                "url": "http://www.quitoambiente.gob.ec/ambiente"
            },
            {
                "name": "Secretaría del Ambiente"
            },
            {
                "name": "Municipio del Distrito Metropolitano de Quito"
            }
        ]
    }
```

#### Parameters

* **`magnitude`**

Is one of the parameters required by openaq.org: PM 2.5, PM 10, CO, NO2, SO2, O3. Please, note that **REMMAQ does not process BC**. 

If you don't specify this parameter, your dataset will return records for all 6 magnitudes.

If the parameter `magnitude` has a value different from the required, you will get
an error and message:

```
    {
        "message": "Parameter [magnitude] must be one of [PM 2.5, PM 10, CO, NO2, SO2, O3]. You also have the option of not using the parameter [magnitude].",
        "error": 400
    }
```   

*Examples:*

```
    http://aqvisor.net:9090/openaq?magnitude=PM+2.5&...
    http://aqvisor.net:9090/openaq?magnitude=CO&...
```

* **`location`**

This is the parameter containing the observation point (AQ monitoring station) `abbreviation` or `name`.
Should be on of the next list:

|abbreviation |name             |
|-------------|-----------------|
|CML          |El Camal         |
|COT          |Cotocollao       |
|GUA          |Guamani          |
|TUM          |Tumbaco          |
|LCH          |Los Chillos      |
|SAP          |San Antonio      |
|CAR          |Carapungo        |
|BEL          |Belisario        |
|CEN          |Centro           |

If you don´t specify this parameter, your dataset will return records for all observation points.

If the parameter magnitude has a value different from the required, you will get
an error and message:

```
    {
        "message": "Parameter [location] must be one of [CML, COT, GUA, TUM, LCH, SAP, ITC, CAR, JIP, BEL, CEN] or [El Camal, Cotocollao, Guamani, Tumbaco, Los Chillos, San Antonio, ITCHIMBIA, Carapungo, Jipijapa, Belisario, Centro]. You also have the option of not using the parameter [magnitude].",
        "error": 400
    }
```

*Examples:*

```
    http://aqvisor.net:9090/openaq?magnitude=SO2&location=LCH&...
    http://aqvisor.net:9090/openaq?magnitude=CO&location=LOS+CHILLOS&...
```

* **`year`**

The parameter `year` to conform the reference date and time, should be a number
in the range 2004 to current year. This parameter is mandatory.

* **`month`**

The parameter `month` to conform the reference date and time. Is a number in 
the range 1 to 12, 1 for January, 2 for February, .... This parameter is mandatory. 

* **`dom`**

The parameter `dom` (day of month) to conform the reference date and time. Is
a number in the range 1 to 28, 29, 30 or 31 depending on the month.

* **`hour`**

The parameter `hour` to conform the reference date and time. Is
a number in the range 0 to 23. This parameter is not mandatory, so its
default value is `0`.


  **Important**:

  **Individual Parameters `year`, `month`, `dom` and `hour` if not well defined,** 
    you'll get a 400 error with a message.
    
  **Parameters `year`, `month`, `dom` and `hour` must conform a valid date and time** if not
  you'll get a 400 error:

```
    {
        "message": "params [year, month, dom, hour] don't conform a valid reference date and time.",
        "error": 400
    }
```

*Examples:*

```
    http://aqvisor.net:9090/openaq?magnitude=PM+2.5&opoint=LCH&&year=2019&month=12&dom=32&...
```

* **`itvl`**

It's the time interval that defines the period of time to extract data from database.
Each record on the dataset has a "date" part of the period. The
valid values of this obligatory parameter is one of:

|value of parameter| range                   |
|:-----:|:------------------------|
|   1 hour |[reference date time - 1 hour later]|    
|  -1 hour |[1 hour before - reference date time]|
|   2 hours|[reference date time - 2 hours later]|
|  -2 hours|[2 hours before - reference date time]|
|   4 hours|[reference date time - 4 hours later]|
|  -4 hours|[4 hours before - reference date time]|
|  8 hours|[reference date time - 8 hours later]|
|  -8 hours|[8 hours before - reference date time]|
|  24 hours|[reference date time - 24 hour later]|
| -24 hours|[24 hour before - reference date time]|
|  72 hours|[reference date time - 72 hour later]|
| -72 hours|[72 hour before - reference date time]|
|  1 week |[reference date time - 1 week later]|
|  -1 week |[1 week before - reference date time]|
|  1 month|[reference date time - 1 month later]|
|  -1 month|[1 month before - reference date time]|


*Examples:*

```
http://aqvisor.net:9090/openaq/dataset?magnitude=PM+10&location=los+chillos&year=2020&month=1&dom=27&itvl=-8+hours 
```

---

## `location`

Render all data about param location:

for the command:

```
    http://aqvisor.net:9090/openaq/location?location=lch
```

or

```
    http://aqvisor.net:9090/openaq/location?location=los+chillos
```

the rendered outpùt is:

```
    {
        "abbr": "LCH",
        "location": "Los Chillos",
        "city": "Quito",
        "country": "EC",
        "sourceType": "government",
        "sourceName": "IMQ-AMBIENTE-REMMAQ",
        "mobile": "false",
        "coordinates": {
            "latitude": -0.29693,
            "longitude": -78.45555
        },
        "srid": "4326"
    }
```

#### Parameters

* **`location`**

This is the parameter containing the observation point (AQ monitoring station) `abbreviation` or `name`.
Should be on of the next list:

|abbreviation |name             |
|-------------|-----------------|
|CML          |El Camal         |
|COT          |Cotocollao       |
|GUA          |Guamani          |
|TUM          |Tumbaco          |
|LCH          |Los Chillos      |
|SAP          |San Antonio      |
|CAR          |Carapungo        |
|BEL          |Belisario        |
|CEN          |Centro           |

if you don't specify any parameter:

```
    http://aqvisor.net:9090/openaq/location
```

then, what you get is an array of all locations:

```
[
    {
        "abbr": "CML",
        "location": "El Camal",
        "x": -78.51713,
        "y": -0.25192,
        "srtid": "4326",
        "city": "Quito",
        "country": "EC",
        "sourceType": "government",
        "sourceName": "IMQ-AMBIENTE-REMMAQ",
        "mobile": "false",
        "coordinates": {
            "latitude": -0.25192,
            "longitude": -78.51713
        }
    },
    {
        "abbr": "COT",
        "location": "Cotocollao",
        "x": -78.49953,
        "y": -0.11072,
        "srtid": "4326",
        "city": "Quito",
        "country": "EC",
        "sourceType": "government",
        "sourceName": "IMQ-AMBIENTE-REMMAQ",
        "mobile": "false",
        "coordinates": {
            "latitude": -0.11072,
            "longitude": -78.49953
        }
    },
    
    ...

]
```

---

## `magnitudes`

This API renders a list of all magnitudes required by OpenAQ.org
using the command:

```
    http://aqvisor.net:9090/openaq/magnitudes
```

render a list of magnitudes:

```
[
    {
        "magnitude": "PM 2.5",
        "original_unit": "µg/m³",
        "factor": null,
        "unit": "µg/m³",
        "magnitude_id": 10,
        "averagingPeriod": {
            "value": 1,
            "unit": "hours"
        }
    },
    {
        "magnitude": "PM 10",
        "original_unit": "µg/m³",
        "factor": null,
        "unit": "µg/m³",
        "magnitude_id": 3,
        "averagingPeriod": {
            "value": 24,
            "unit": "hours"
        }
    },


    ...

]
```

#  Suggested Procedure

* On normal conditions VISOR system is updating **every 2 hours starting at 01:30AM**
. So, our first recommendation in to run the next commands every 2 hours
starting at 02H00 ending at 22H00

```
    http://aqvisor.net:9090/openaq/dataset?location=CML&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=COT&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=GUA&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=TUM&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=LCH&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=SAP&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=CAR&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=BEL&year=****&month=*&dom=*&hour=*&itvl=-8+hours
    http://aqvisor.net:9090/openaq/dataset?location=CEN&year=****&month=*&dom=*&hour=*&itvl=-8+hours
```

please match the `year`, `month`, `dom` and `hour` with valid City of Quito date and time values.

For example, if the server consuming data is in London, a valid Quito time is the London time less
5 hours. That is a valid *reference date and tine*. The `-8 hours` value of the `ìtvl` parameter
means that dataset correspond to 8 hours before reference date and time. 

* REMMAQ may fix or load data that were not available. This process is run by
VISOR System every Tuesday and Saturday. To synchronize with
updated REMMAQ data we suggest to run every Sunday night (by 10PM)

```
    http://aqvisor.net:9090/openaq/dataset?location=CML&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=COT&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=GUA&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=TUM&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=LCH&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=SAP&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=CAR&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=BEL&year=****&month=*&dom=*&hour=*&itvl=-1+week
    http://aqvisor.net:9090/openaq/dataset?location=CEN&year=****&month=*&dom=*&hour=*&itvl=-1+week
```


* If ypu want to get data set for a whole month, for example Feb 2020, tha reference dat is
`&year=2020&month=2&dom=1&hour=0` and the interval is 1 month:`&itvl=1+month`

```
    http://aqvisor.net:9090/openaq/dataset?location=CML&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=COT&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=GUA&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=TUM&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=LCH&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=SAP&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=CAR&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=BEL&year=2020&month=2&dom=1&hour=0&itvl=1+month
    http://aqvisor.net:9090/openaq/dataset?location=CEN&year=2020&month=2&dom=1&hour=0&itvl=1+month
```

* We recommend not using the APIs described here, between 23H00 and 01H00 
(City of Quito time, UTC -5h). Because a very intense database backup process.


*Complete examples*

Getting `CO` dataset for location `Los Chillos` 24 hours starting at 3 PM, the 27th of January 2020

```
http://aqvisor.net:9090/openaq/dataset?magnitude=CO&location=los+chillos&year=2020&month=1&hour=15&dom=27&itvl=24+hours
```

The same for all locations:

```
http://aqvisor.net:9090/openaq/dataset?magnitude=CO&year=2020&month=1&hour=15&dom=27&itvl=24+hours
```

or all magnitudes for locatin `Los Chillos`


```
http://aqvisor.net:9090/openaq/dataset?location=los+chillos&year=2020&month=1&hour=15&dom=27&itvl=24+hours
```

It's no possible to avoid both parameters, `magnitude` and `location` at the same time. It's obligatory
to specify one of them, or both. If both paramers were avoided, you'll get the next 400 message:

```
    {
        "message": "[magnitude] or [location] must be defined, or both.",
        "error": 400
    }
```




--------------
Juan Salvador

Oct 31st, 2020

**Comment by fred-sch** [comment]
FYI @sruti: I found that some of the Quito-data report incorrect times.

For example, the file https://openaq-fetches.s3.amazonaws.com/realtime/2021-11-10/1636530069.ndjson, which corresponds to November 10, 2021 7:41:09 AM GMT, contains measurements at Carapungo in the future like this
```json
{
  "date": {
    "utc": "2021-11-10T21:00:00.000Z",
    "local": "2021-11-10T16:00:00-05:00"
  },
  "parameter": "pm25",
  "value": 0,
  "unit": "µg/m³",
  "averagingPeriod": {
    "value": 1,
    "unit": "hours"
  },
  "location": "Carapungo",
  "city": "Quito",
  "country": "EC",
  "coordinates": {
    "latitude": -0.09548,
    "longitude": -78.44988
  },
  "attribution": [
    {
      "name": "REMMAQ",
      "url": "http://www.quitoambiente.gob.ec/ambiente"
    },
    {
      "name": "Secretaría del Ambiente"
    },
    {
      "name": "Municipio del Distrito Metropolitano de Quito"
    }
  ],
  "sourceName": "Quito REMMAQ",
  "sourceType": "government",
  "mobile": false
}
```
