### ISSUE TITLE
New Data: South-Africa

### ISSUE THREAD

**Issue by smalber** [openaq/openaq-fetch#790]
Good Day,

I have built my own Air Quality Sensor with the PMS5003 module and a ESP8266, using this project as source:
https://how2electronics.com/interfacing-pms5003-air-quality-sensor-arduino/

I'm ready to Push/Post my sensor data to the openaq.org platform as a private contributor.

I have used the OpenAQ Browser (https://dolugen.github.io/openaq-browser/#/countries) to navigate the data. I don't see a country=South-Africa and city=Centurion entry in your data fetched data.

What location,city,country,province and other information do you require from me?

My plan is to deploy similar PMS5003 based sensors around the country.

Regards
Reno Smalberger
reno.smalberger@gmail.com

**Comment by majesticio** [comment]
@smalber Thanks for reaching out! Sorry it took so long for a response. Currently we are not ingesting data from DIY sensors. We have to write an adapter for each source, right now we have ~50 sources that are reporting data for ~50,000 monitors. I do encourage you to continue though. You may find creating your own dashboard useful, I suggest looking at node red if you are using MQTT. We just released our new [explorer](https://explore.openaq.org/) if you want to see data in your area so you know where to place new sensors.
