### ISSUE TITLE
New Data: London Air Quality Network

### ISSUE THREAD

**Issue by sruti** [openaq/openaq-fetch#792]
API exists! Documentation is here: http://api.erg.ic.ac.uk/AirQuality/Information/Documentation/pdf

**Comment by abarciauskas-bgse** [comment]
As far as I can tell, this data source is not currently in the platform so is still worth investigating.

**Comment by dabutvin** [comment]
👋  I just took a stab at this one with #796

**Comment by sruti** [comment]
@lstanton428 That may be a good idea. Also, it looks like the units for the measurements aren't labelled. @dabutvin was able to infer from [this script](https://github.com/davidcarslaw/openair/blob/master/R/importKCL.R) but we should definitely confirm before ingesting the data.
