### ISSUE TITLE
Missing Stations in Cyprus 

### ISSUE THREAD

**Issue by sruti** [openaq/openaq-fetch#802]
Looks like we aren't pulling all the available stations in Cyprus from the [EEA adapter](https://github.com/openaq/openaq-fetch/blob/develop/adapters/eea-direct.js). All stations can be viewed here: https://www.airquality.dli.mlsi.gov.cy/all_stations_data_PM. 

This might be related to the problem with the [Battuta service no longer working](https://github.com/openaq/battuta/issues/8).

**Comment by russbiggs** [comment]
Cyprus no longer seems to be providing data to EEA. Closing this issue in favor of new data ticket for new Cyprus government API #948
