### ISSUE TITLE
Figure out Chinese AQI Algorithm

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#89]

**Comment by RocketD0g** [comment]
The Chinese AQI is very similar to the US AQI calculation in the below: 

![screen shot 2016-02-29 at 1 45 05 pm](https://cloud.githubusercontent.com/assets/13404290/13407344/f5ebaff8-def5-11e5-8158-6d47e0347c7d.png)

IAQI = the AQI calculated for an individual pollutant (e.g. CO, PM2.5, etc.)

_Equation Source: From Page 9: http://are.berkeley.edu/~sberto/BeijingJuly16.pdf_

Here is the US EPA version (On page 16 of this EPA publication: http://www3.epa.gov/ttn/oarpg/t1/memoranda/rg701.pdf), as mentioned by @olafveerman in #79 (and same variable definitions besides IAQI as the above): 
![image](https://cloud.githubusercontent.com/assets/13404290/13407670/ae37c474-def7-11e5-934e-adcf11224365.png)



The main difference between the Chinese AQI and the US EPA version is that there are different breakpoints between AQI categories. Here are the most recent Chinese AQI breakpoints:
![screen shot 2016-02-29 at 3 07 45 pm](https://cloud.githubusercontent.com/assets/13404290/13407398/3c636502-def6-11e5-945b-e4d31bdd4cae.png)
_Source: http://www.livefrombeijing.com/wp-content/uploads/images/chinese-iaqi-cutpoints-jan-2013.png , with secondary confirmation source here on Page 10: http://are.berkeley.edu/~sberto/BeijingJuly16.pdf _

Another difference is the averaging time intervals for Ci. The averaging time intervals  that should be used for the Chinese AQI are indicated on the table above for the different pollutants.

**Comment by nickolasclarke** [comment]
@RocketD0g let me know specifics of what you need on this and I can get the info for you.

**Comment by RocketD0g** [comment]
@nickolasclarke - to be honest, I should have closed this earlier. At one point, we considered back-calculating the Chinese AQ physical data from AQI, but have decided this is not a best practice on our end to rely on and now stipulate we will only directly mirror physical AQ data as it is available.

**Comment by nickolasclarke** [comment]
yeah, that's probably for the best.
