### ISSUE TITLE
OpenAQ data not updating

### ISSUE THREAD

**Issue by mheimbinder** [openaq/openaq-fetch#891]
OpenAQ data hasn't updated since 3/22/22

**Comment by russbiggs** [comment]
Hi @mheimbinder we are aware of the issue and working on resolving. the best place to keep up known outages is on our Slack workspace, specifically in the #dev channel. 

https://join.slack.com/t/openaq/shared_invite/zt-yzqlgsva-v6McumTjy2BZnegIK9XCVw
