### ISSUE TITLE
Develop standardized format for submitting new sources as issues

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-fetch#90]
Intended to help more clearly communicate what data exists and doesn't exist on a site so people can take the issue and more easily run with it and not run into dead ends.

**Comment by olafveerman** [comment]
Great idea.

Also, if you think that submitting sources through Github issues may prevent non-technical people to contribute, we can set up a simple form that accepts submissions and automatically creates a GH issue from it.

**Comment by RocketD0g** [comment]
That'd be awesome! Currently, we've got a google form linked off the main
site for people to put stuff in, here:
https://docs.google.com/forms/d/1Osi0hQN1-2aq8VGrAR337eYvwLCO5VhCa3nC_IK2_No/viewform

It's not ideal how it is set up, and when someone puts stuff in, there's no
automatic notification. A form that automatically generates an issue (with
more optional input for more detail than that form we have now) would be so
cool!


On Fri, Feb 26, 2016 at 11:34 AM, Olaf Veerman <notifications@github.com>
wrote:

> Great idea.
>
> Also, if you think that submitting sources through Github issues may
> prevent non-technical people to contribute, we can set up a simple form
> that accepts submissions and automatically creates a GH issue from it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaq/openaq-fetch/issues/90#issuecomment-189361214>.
>



-- 

507.246.2097

**Comment by RocketD0g** [comment]
**Proposed draft format: **

ALL Questions are OPTIONAL:

-Country of data source:
-Specific coverage within country: 

-URL:
-Comments on URL: [Ex. You have to click on x, then y to see values]

-Pollutants measured:

-Are units of measurement clearly indicated (e.g. do you see 'AQI', 'ppm' or 'ug/m^3'?) _Note: We cannot directly input AQI, API, AQHI, etc. values directly into our system_ 
[yes][no][unsure]
-Comments about units: [ex. 'They are viewable on {this page}, see the table]

-Are there date+timestamps for pollutant measurements? [yes][no][unsure]

-Are time intervals otherwise indicated on the site (e.g. 'Measurements are 15 minute averages')

-Are coordinates for the stations clearly indicated or discernable? (e.g. do you see a map or a list of coordinates): [yes][no][unsure]

-Are you with the host agency and may we contact you? [yes, here's my email _____]

-Any other comments about this source:

[OPTIONAL]Your name/contact info/interest in open air quality data:

****
Thinking all q's are optional because for a given case, we may just need the host agency contact + country, not the URL. For others, while it would be nice to have additional info, it would be great to just have the URL (and don't want to deter people from inputting sources just because the timestamps, coordinates and specific pollutant q's overwhelm them). 

Other thoughts/edits?

**Comment by abarciauskas-bgse** [comment]
PR opened #793
