### ISSUE TITLE
Türkiye CO values

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#926]
It looks like the CO mass values are being incorrectly ingested. The standard unit is µg/m3 but it looks like (based on the entry in the wiki) Türkiye is reporting mg/m3. Though this doesnt make sense based on the values. @majesticio

**Comment by majesticio** [comment]
should be resolved with PR #928

**Comment by majesticio** [comment]
CO values in Turkiye have returned to normal ranges after PR #928. Closing issue
