### ISSUE TITLE
New data provider - Japan

### ISSUE THREAD

**Issue by majesticio** [openaq/openaq-fetch#931]
URL: https://soramame.env.go.jp

related to #20 
refer to the [wiki](https://github.com/openaq/openaq-fetch/wiki/Soramame-Japan-Environmental-Agency) for details

**Comment by majesticio** [comment]
The adapter for Japan is nearly complete, however from the website it looks like they have site-wide rate limiting:
- "Regarding the use of the API, please refrain from using it with high frequency access so that many users can use it. Requests may be restricted if we detect high-frequency access that affects other users."

**Comment by majesticio** [comment]
While running requests in parallel we are getting an error:
`message: 'Failure to load data url (https://soramame.env.go.jp/soramame/api/data_search?Start_YM=202209&End_YM=202210&TDFKN_CD=39&SKT_CD=39201350)'`
I believe this is due to rate limiting on their end.

**Comment by russbiggs** [comment]
this is the core of the error currently 

```
Error: aborted
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.socketCloseListener (node:_http_client:441:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:757:14
    at TCP.done (node:_tls_wrap:584:7) {
  code: 'ECONNRESET'
}
```

which reads more as an abrupt socket closing due to overloading, not exacly rate limiting, but rate limiting on our side would probably be a good idea

**Comment by russbiggs** [comment]
This library has an interesting model to control concurrency which may be helpful for the current issue:

https://github.com/sindresorhus/p-queue
