### ISSUE TITLE
New data - Cyprus

### ISSUE THREAD

**Issue by russbiggs** [openaq/openaq-fetch#948]
The Republic of Cyprus provide air quality monitoring data via an API here:

https://www.airquality.dli.mlsi.gov.cy/all_stations_data_PM

There are 11 stations currently in the API measuring PM₂.₅,PM₁₀,O₃,SO₂,NO₂,NO, NOx. Data seems to be updated hourly. General information is available here (Greek): https://www.data.gov.cy/dataset/%CF%84%CF%81%CE%AD%CF%87%CE%BF%CF%85%CF%83%CE%B5%CF%82-%CE%BC%CE%B5%CF%84%CF%81%CE%AE%CF%83%CE%B5%CE%B9%CF%82-%CE%B1%CF%84%CE%BC%CE%BF%CF%83%CF%86%CE%B1%CE%B9%CF%81%CE%B9%CE%BA%CF%8E%CE%BD-%CF%81%CF%8D%CF%80%CF%89%CE%BD-api

**Comment by majesticio** [comment]
merged in #953
