### ISSUE TITLE
Fix city names in the Sao Paulo adapter

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#97]
From openaq/openaq-api#175 as reported by @masalmon:

> From https://github.com/ropensci/onboarding/issues/24
> 
> "Also, I know that this is probably the fault of the API and not your package, but the places named in brz$location are not places in city of Sao Paulo, but cities in the state of Sao Paulo. Yet the resulting data frame has "Sao Paulo" listed for all rows, in the column "city"."

The Sao Paolo adapter is for the "Estado de Sao Paulo" not the city of that state. And the station names are named in various ways (PlaceName or City-PlaceName), so we'll need to figure out the cities for each station. A little bit of geography lesson.

As well as the adapter fix, the existing data should have their city names fixed with a migration script.

**Comment by masalmon** [comment]
Thanks for tackling it and good luck with the geography lesson!

**Comment by dolugen** [comment]
The stations are named after subprefectures, parks, cities (municipality), etc.

1. Station Name - Original station names in the source
2. City Name - City/Municipality the station exists in, same as station name if not present

This table is based on info from EN and PT wikipedia. If someone with knowledge of South America/Brazil could have a look at it, that'd be nice.

Station Name | City Name (if different) | Comments
------------------|------------------------------|---------------
Americana | 
Araçatuba |
Araraquara | 
Bauru | 
Campinas-Centro | Campinas
Campinas-Taquaral | Campinas
Campinas-V.União | Campinas
Capão Redondo |  São Paulo | district
Carapicuiba | 
Catanduva | 
Cerqueira César | 
Cid.Universitária-USP-Ipen | São Paulo | university
Congonhas | São Paulo | airport
Cubatão-Centro | Cubatão
Cubatão-V.Parisi | Cubatão
Cubatão-Vale do Mogi | Cubatão
Diadema | 
Guarulhos-Paço Municipal | Guarulhos | city hall
Guarulhos-Pimentas | Guarulhos
Ibirapuera | São Paulo | park
Interlagos | São Paulo | neighbourhood
Itaim Paulista | São Paulo | district/subprefecture
Itaquera | São Paulo | district/subprefecture
Jacareí | 
Jaú | 
Jundiaí | 
Limeira | 
Marg.Tietê-Pte Remédios | São Paulo | highway section
Marília |
Mauá |
Mooca |  São Paulo | district/subprefecture
N.Senhora do Ó | São Paulo | church
Osasco |
Parelheiros | São Paulo | district/subprefecture
Parque D.Pedro II | São Paulo | park
Paulínia |
Paulínia Sul |
Pinheiros | São Paulo | district/subprefecture
Piracicaba |
Presidente Prudente |
Ribeirão Preto |
S.André-Capuava | Santo André
S.André-Paço Municipal | Santo André
S.Bernardo-Centro | São Bernardo do Campo
S.Bernardo-Paulicéia | São Bernardo do Campo
S.Caetano | São Caetano do Sul
S.José Campos | São José dos Campos
S.José Campos-Jd.Satélite | São José dos Campos
S.José Campos-Vista Verde | São José dos Campos
Santa Gertrudes |
Santana | São Paulo | district/subprefecture
Santo Amaro | São Paulo | district/subprefecture
Santos |
Santos-Ponta da Praia | Santos | neighbourhood
São José Do Rio Preto |
Sorocaba |
Taboão da Serra |
Tatuí |
Taubaté |
