### ISSUE TITLE
Create migration to add Sao Paulo coordinates

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-fetch#98]
There is a page in Sao Paulo source that shows you the station addresses.

http://ar.cetesb.sp.gov.br/configuracao-da-rede-automatica/

We can get the approximate coordinates from the addresses. Can we use such inferred coordinates? @jflasher @RocketD0g

Ninja edit by @jflasher to update outstanding tasks:
- [x] Update adapter to add coordinates
- [ ] Create migration to add coordinates to older data

**Comment by RocketD0g** [comment]
Ideally, we'd get the exact coordinates. At least for me, when I've typed in the addresses to google maps, I don't get an exact place (or any place) for several of them. I've just tweeted something out and will continue to ask through other sources. I don't see a way to contact the agency directly, though perhaps Portuguese-speaker @olafveerman may see something I don't. Agreed, @dolugen - It *would* be really nice to get these!

**Comment by dolugen** [comment]
Yeah if we could get the info from the organization itself, that'd be helpful.

**Comment by oranzani** [comment]
Hi, it is my first time in github, I am sorry for not being familiar on how to handle it. I will try to help with the stations' geocoding.

I would like to know from where you get the data? From CETESB, which means São Paulo State, in Brazil? 
Does it came from "http://qualar.cetesb.sp.gov.br/" ?
Looking in the stations at the https://openaq.org/#/countries/BR?_k=c3tqd0, I could not understand why some stations (same name) are in duplicate... are the stations from the CETESB automatic monitoring stations?
Thank you

**Comment by RocketD0g** [comment]
Too awesome, @oranzani! Thanks so much. 

The data come from: http://sistemasinter.cetesb.sp.gov.br/Ar/php/ar_dados_horarios.php

It looks to me that the duplicates have to do with fixing errors in the location name awhile back. As in, once the error was fixed, the data began being aggregated under the fixed location name instead of the old. Maybe @jflasher or @dolugen can confirm or deny my guess.

Please reach out with any questions, and appreciate your willingness to help out on this a lot.

**Comment by dolugen** [comment]
Thanks @oranzani for taking the time to look into it.

The duplicates of Brazil data should be fixed soon (with #317).

**Comment by oranzani** [comment]
Hi dear colleagues,
thank you for the replies.

I did it. 
I am uploading a .csv file with the lat and lon data for the São Paulo Stations.

Briefly: you are gathering data from the automatic continuous monitoring stations from CETESB (they do have other stations with manual measures and other random measures). I got the exact position from the QUALAR system (after logging in, open source data). These data are also available in this report (http://ar.cetesb.sp.gov.br/wp-content/uploads/sites/37/2013/12/relatorio-ar-2016.pdf), tables in "Anexo 2", starting page 142. But the data are in UTM format, datum SIRGAS 2000 (similar to WGS84).

In the R script, I used the packages sp and rgdal to convert to lat/lon. I also checked with the raw addresses, using the geocode function from ggmap (it do neet adaptions for googlemap capture all them) (script available here: https://github.com/oranzani/saopaulo_stationsgis/blob/master/cetesb_stations.R)

I am uploading the txt file (https://github.com/oranzani/saopaulo_stationsgis/blob/master/saopaulo_stationsgeo.txt)

I hope it helped,
Cheers,
Otavio

**Comment by RocketD0g** [comment]
This is so awesome, @oranzani! Thanks so much! Once they're incorporated on the map, I'll send you a message. Thanks for not only providing the coordinates, but letting us know how you sourced them!

**Comment by jflasher** [comment]
Thanks @oranzani! I converted the data into JSON and updated the adapter to this will get added for new records. We'll still need to handle adding to previous data via a migration. Updating initial item to indicate that.

**Comment by oranzani** [comment]
Hi dear colleagues,
fantastic. I am happy we could do it! I just look at the real-time map, and the stations are there ;)!

Thanks,
Otavio

**Comment by dolugen** [comment]
We can start preparing the migration, but it'll probably be applied after the other migrations (#316, #317).

**Comment by majesticio** [comment]
All entries for Sao Paulo and São Paulo have coordinates. Closing issue, but feel free to reopen with new information.
